// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.shared.graphics

enum class RenderingCullMode {
    FRONT,
    BACK,
    NONE,
}
