// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from packer.djinni

import type { RectI, Vec2I } from "@djinni/maps-core/graphics/common/common"
import type { TextureHolderInterface } from "@djinni/maps-core/graphics/objects/graphicsobjects"

export interface /*record*/ RectanglePackerPage {
    uvs: Map<string, RectI>;
}

export interface RectanglePacker {
}
export interface RectanglePacker_statics {
    pack(rectangles: Map<string, Vec2I>, maxPageSize: Vec2I, spacing: number): Array<RectanglePackerPage>;
}

export interface /*record*/ TextureAtlas {
    uvMap: Map<string, RectI>;
    texture?: TextureHolderInterface;
}

export interface Packer_statics {
    RectanglePacker: RectanglePacker_statics;
}
