// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common.djinni

package ch.ubique.mapscore.shared.graphics.common

data class Vec3F(
    var x: Float,
    var y: Float,
    var z: Float,
)