// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from shader.djinni

#include "NativeInterpolationShaderInterface.h"  // my header
#include "Marshal.hpp"
#include "NativeAlphaShaderInterface.h"

namespace djinni_generated {

NativeInterpolationShaderInterface::NativeInterpolationShaderInterface() : ::djinni::JniInterface<::InterpolationShaderInterface, NativeInterpolationShaderInterface>("io/openmobilemaps/mapscore/shared/graphics/shader/InterpolationShaderInterface$CppProxy") {}

NativeInterpolationShaderInterface::~NativeInterpolationShaderInterface() = default;


CJNIEXPORT void JNICALL Java_io_openmobilemaps_mapscore_shared_graphics_shader_InterpolationShaderInterface_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::InterpolationShaderInterface>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT void JNICALL Java_io_openmobilemaps_mapscore_shared_graphics_shader_InterpolationShaderInterface_00024CppProxy_native_1updateFraction(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jfloat j_value)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::InterpolationShaderInterface>(nativeRef);
        ref->updateFraction(::djinni::F32::toCpp(jniEnv, j_value));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_io_openmobilemaps_mapscore_shared_graphics_shader_InterpolationShaderInterface_00024CppProxy_native_1asAlphaShaderInterface(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::InterpolationShaderInterface>(nativeRef);
        auto r = ref->asAlphaShaderInterface();
        return ::djinni::release(::djinni_generated::NativeAlphaShaderInterface::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
