// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#pragma once

#include "StretchShaderInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeStretchShaderInterface final : ::djinni::JniInterface<::StretchShaderInterface, NativeStretchShaderInterface> {
public:
    using CppType = std::shared_ptr<::StretchShaderInterface>;
    using CppOptType = std::shared_ptr<::StretchShaderInterface>;
    using JniType = jobject;

    using Boxed = NativeStretchShaderInterface;

    ~NativeStretchShaderInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeStretchShaderInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeStretchShaderInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeStretchShaderInterface();
    friend ::djinni::JniClass<NativeStretchShaderInterface>;
    friend ::djinni::JniInterface<::StretchShaderInterface, NativeStretchShaderInterface>;

};

} // namespace djinni_generated
