// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#pragma once

#include "StretchShaderInfo.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeStretchShaderInfo final {
public:
    using CppType = ::StretchShaderInfo;
    using JniType = jobject;

    using Boxed = NativeStretchShaderInfo;

    ~NativeStretchShaderInfo();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeStretchShaderInfo();
    friend ::djinni::JniClass<NativeStretchShaderInfo>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/openmobilemaps/mapscore/shared/graphics/shader/StretchShaderInfo") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(FFFFFFFFFFLio/openmobilemaps/mapscore/shared/graphics/common/RectD;)V") };
    const jfieldID field_scaleX { ::djinni::jniGetFieldID(clazz.get(), "scaleX", "F") };
    const jfieldID field_stretchX0Begin { ::djinni::jniGetFieldID(clazz.get(), "stretchX0Begin", "F") };
    const jfieldID field_stretchX0End { ::djinni::jniGetFieldID(clazz.get(), "stretchX0End", "F") };
    const jfieldID field_stretchX1Begin { ::djinni::jniGetFieldID(clazz.get(), "stretchX1Begin", "F") };
    const jfieldID field_stretchX1End { ::djinni::jniGetFieldID(clazz.get(), "stretchX1End", "F") };
    const jfieldID field_scaleY { ::djinni::jniGetFieldID(clazz.get(), "scaleY", "F") };
    const jfieldID field_stretchY0Begin { ::djinni::jniGetFieldID(clazz.get(), "stretchY0Begin", "F") };
    const jfieldID field_stretchY0End { ::djinni::jniGetFieldID(clazz.get(), "stretchY0End", "F") };
    const jfieldID field_stretchY1Begin { ::djinni::jniGetFieldID(clazz.get(), "stretchY1Begin", "F") };
    const jfieldID field_stretchY1End { ::djinni::jniGetFieldID(clazz.get(), "stretchY1End", "F") };
    const jfieldID field_uv { ::djinni::jniGetFieldID(clazz.get(), "uv", "Lio/openmobilemaps/mapscore/shared/graphics/common/RectD;") };
};

} // namespace djinni_generated
