// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#pragma once

#include "SphereProjectionShaderInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSphereProjectionShaderInterface final : ::djinni::JniInterface<::SphereProjectionShaderInterface, NativeSphereProjectionShaderInterface> {
public:
    using CppType = std::shared_ptr<::SphereProjectionShaderInterface>;
    using CppOptType = std::shared_ptr<::SphereProjectionShaderInterface>;
    using JniType = jobject;

    using Boxed = NativeSphereProjectionShaderInterface;

    ~NativeSphereProjectionShaderInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSphereProjectionShaderInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSphereProjectionShaderInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSphereProjectionShaderInterface();
    friend ::djinni::JniClass<NativeSphereProjectionShaderInterface>;
    friend ::djinni::JniInterface<::SphereProjectionShaderInterface, NativeSphereProjectionShaderInterface>;

};

} // namespace djinni_generated
