if(EXISTS "/home/runner/work/maps-core/maps-core/_codeql_build_dir/shared/test/tests-b12d07c_tests.cmake")
  include("/home/runner/work/maps-core/maps-core/_codeql_build_dir/shared/test/tests-b12d07c_tests.cmake")
else()
  add_test(tests_NOT_BUILT-b12d07c tests_NOT_BUILT-b12d07c)
endif()
