// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#pragma once

#include "ComputeObjectInterface.h"
#include <memory>
#include <vector>

class ComputePassInterface {
public:
    virtual ~ComputePassInterface() = default;

    virtual std::vector</*not-null*/ std::shared_ptr<::ComputeObjectInterface>> getComputeObjects() = 0;
};
