// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

#pragma once

#include <cstdint>
#include <utility>

struct Coord final {
    int32_t systemIdentifier;
    double x;
    double y;
    double z;

    friend bool operator==(const Coord& lhs, const Coord& rhs);
    friend bool operator!=(const Coord& lhs, const Coord& rhs);

    friend bool operator<(const Coord& lhs, const Coord& rhs);
    friend bool operator>(const Coord& lhs, const Coord& rhs);

    friend bool operator<=(const Coord& lhs, const Coord& rhs);
    friend bool operator>=(const Coord& lhs, const Coord& rhs);

    Coord(int32_t systemIdentifier_,
          double x_,
          double y_,
          double z_)
    : systemIdentifier(std::move(systemIdentifier_))
    , x(std::move(x_))
    , y(std::move(y_))
    , z(std::move(z_))
    {}
};
