// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from coordinate_system.djinni

#pragma once

#include <string>

struct Coord;

class CoordinateConverterInterface {
public:
    virtual ~CoordinateConverterInterface() {}

    virtual Coord convert(const Coord & coordinate) = 0;

    virtual std::string getFrom() = 0;

    virtual std::string getTo() = 0;
};
