// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from global_loader.djinni

#pragma once

#include "DataLoaderResult.h"
#include "FontLoaderInterface.h"
#include "Future.hpp"
#include "LoaderInterface.h"
#include "TextureLoaderResult.h"
#include <memory>
#include <optional>
#include <string>

/** only needed for web */
class GlobalLoaderInterface {
public:
    virtual ~GlobalLoaderInterface() = default;

    static /*not-null*/ std::shared_ptr<GlobalLoaderInterface> create();

    virtual /*not-null*/ std::shared_ptr<::LoaderInterface> createLoader() = 0;

    virtual /*not-null*/ std::shared_ptr<::FontLoaderInterface> createFontLoader(const /*not-null*/ std::shared_ptr<::LoaderInterface> & loader, const std::string & baseUrl) = 0;

    virtual void processLoadRequests() = 0;

    virtual ::djinni::Future<::DataLoaderResult> enqueueDataLoadRequest(const std::string & url, const std::optional<std::string> & etag) = 0;

    virtual ::djinni::Future<::TextureLoaderResult> enqueueTextureLoadRequest(const std::string & url, const std::optional<std::string> & etag) = 0;

    virtual void cancel(const std::string & url) = 0;
};
