// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from icon.djinni

#pragma once

#include "Coord.h"
#include "TextureHolderInterface.h"
#include "Vec2F.h"
#include <memory>
#include <string>

enum class IconType;

class IconInfoInterface {
public:
    virtual ~IconInfoInterface() {}

    virtual std::string getIdentifier() = 0;

    virtual std::shared_ptr<::TextureHolderInterface> getTexture() = 0;

    virtual void setCoordinate(const ::Coord & coord) = 0;

    virtual ::Coord getCoordinate() = 0;

    virtual void setIconSize(const ::Vec2F & size) = 0;

    virtual ::Vec2F getIconSize() = 0;

    virtual void setType(IconType scaleType) = 0;

    virtual IconType getType() = 0;
};
