// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

#pragma once

#include "RectCoord.h"
#include <cstdint>
#include <utility>

struct MapCoordinateSystem final {
    int32_t identifier;
    RectCoord bounds;
    float unitToScreenMeterFactor;

    MapCoordinateSystem(int32_t identifier_,
                        RectCoord bounds_,
                        float unitToScreenMeterFactor_)
    : identifier(std::move(identifier_))
    , bounds(std::move(bounds_))
    , unitToScreenMeterFactor(std::move(unitToScreenMeterFactor_))
    {}
};
