// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera.djinni

#pragma once

#include "Coord.h"
#include "RectCoord.h"
#include "Vec3D.h"
#include <vector>

class MapCameraListenerInterface {
public:
    virtual ~MapCameraListenerInterface() = default;

    virtual void onVisibleBoundsChanged(const ::RectCoord & visibleBounds, double zoom) = 0;

    virtual void onRotationChanged(float angle) = 0;

    virtual void onMapInteraction() = 0;

    virtual void onCameraChange(const std::vector<float> & viewMatrix, const std::vector<float> & projectionMatrix, const ::Vec3D & origin, float verticalFov, float horizontalFov, float width, float height, float focusPointAltitude, const ::Coord & focusPointPosition, float zoom) = 0;
};
