// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from polygon.djinni

#pragma once

#include "CoordinateConversionHelperInterface.h"
#include "GraphicsObjectFactoryInterface.h"
#include "Polygon2dInterface.h"
#include "PolygonCoord.h"
#include <memory>
#include <vector>

class PolygonMaskObjectInterface {
public:
    virtual ~PolygonMaskObjectInterface() = default;

    static /*not-null*/ std::shared_ptr<PolygonMaskObjectInterface> create(const /*not-null*/ std::shared_ptr<::GraphicsObjectFactoryInterface> & graphicsObjectFactory, const /*not-null*/ std::shared_ptr<::CoordinateConversionHelperInterface> & conversionHelper, bool is3d);

    virtual void setPolygons(const std::vector<::PolygonCoord> & polygons) = 0;

    virtual void setPolygon(const ::PolygonCoord & polygon) = 0;

    virtual /*not-null*/ std::shared_ptr<::Polygon2dInterface> getPolygonObject() = 0;
};
