// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#pragma once

#include <memory>
#include <optional>
#include <utility>
#include <vector>

class RenderPassInterface;
class RenderTargetTexture;

struct RenderTask final {
    /*nullable*/ std::shared_ptr<RenderTargetTexture> target;
    std::vector</*not-null*/ std::shared_ptr<RenderPassInterface>> renderPasses;

    RenderTask(/*nullable*/ std::shared_ptr<RenderTargetTexture> target_,
               std::vector</*not-null*/ std::shared_ptr<RenderPassInterface>> renderPasses_)
    : target(std::move(target_))
    , renderPasses(std::move(renderPasses_))
    {}
};
