// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#pragma once

#include "Color.h"
#include "RectI.h"
#include "Vec2I.h"
#include "Vec3D.h"
#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <vector>

class OpenGlRenderingContextInterface;
class RenderTargetInterface;
enum class RenderingCullMode;

class RenderingContextInterface {
public:
    virtual ~RenderingContextInterface() = default;

    /** Ensure calling on graphics thread */
    virtual void onSurfaceCreated() = 0;

    /** Ensure calling on graphics thread */
    virtual void setViewportSize(const ::Vec2I & size) = 0;

    virtual ::Vec2I getViewportSize() = 0;

    virtual void setBackgroundColor(const ::Color & color) = 0;

    virtual void setCulling(RenderingCullMode mode) = 0;

    virtual void setupDrawFrame(int64_t vpMatrix, const ::Vec3D & origin, double screenPixelAsRealMeterFactor) = 0;

    virtual void preRenderStencilMask() = 0;

    virtual void postRenderStencilMask() = 0;

    virtual void clearStencilMask(int32_t clearMask) = 0;

    virtual void setupStencilWriteMask(int32_t writeMask, int32_t reference) = 0;

    /** optional rectangle, remove scissoring when not set */
    virtual void applyScissorRect(const std::optional<::RectI> & scissorRect) = 0;

    virtual /*not-null*/ std::shared_ptr<RenderTargetInterface> getCreateOffscreenRenderTarget(const std::string & name) = 0;

    virtual void deleteOffscreenRenderTarget(const std::string & name) = 0;

    virtual std::vector</*not-null*/ std::shared_ptr<RenderTargetInterface>> getOffscreenRenderTargets() = 0;

    virtual /*nullable*/ std::shared_ptr<OpenGlRenderingContextInterface> asOpenGlRenderingContext() = 0;
};
