// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

class GraphicsObjectInterface;
class SharedGraphicsObjectInterface;
class TextureHolderInterface;

class SharedTextureGroupInterface {
public:
    virtual ~SharedTextureGroupInterface() {}

    virtual std::shared_ptr<GraphicsObjectInterface> asGraphicsObject() = 0;

    virtual void setObjectsGroup(const std::string & textureId, int64_t groupId, const std::vector<std::shared_ptr<SharedGraphicsObjectInterface>> & objects) = 0;

    virtual void clearObjectsGroup(int64_t groupId) = 0;

    virtual void setTexture(const std::string & textureId, const std::shared_ptr<TextureHolderInterface> & textureHolder) = 0;

    virtual void removeTexture(const std::string & textureId) = 0;
};
