// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

#pragma once

#include <functional>

enum class SymbolAlignment : int {
    MAP = 0,
    VIEWPORT = 1,
    AUTO = 2,
};

constexpr const char* toString(SymbolAlignment e) noexcept {
    constexpr const char* names[] = {
        "MAP",
        "VIEWPORT",
        "AUTO",
    };
    return names[static_cast<int>(e)];
}

namespace std {

template <>
struct hash<::SymbolAlignment> {
    size_t operator()(::SymbolAlignment type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
