// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from task_scheduler.djinni

#pragma once

#include <memory>

class SchedulerInterface;
class ThreadPoolCallbacks;

class ThreadPoolScheduler {
public:
    virtual ~ThreadPoolScheduler() {}

    static std::shared_ptr<SchedulerInterface> create(const std::shared_ptr<ThreadPoolCallbacks> & callbacks);
};
