// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

#pragma once

#include "Color.h"
#include <cstdint>
#include <optional>
#include <string>
#include <utility>
#include <vector>

struct VectorLayerFeatureInfoValue final {
    std::optional<std::string> stringVal;
    std::optional<double> doubleVal;
    std::optional<int64_t> intVal;
    std::optional<bool> boolVal;
    std::optional<::Color> colorVal;
    std::optional<std::vector<float>> listFloatVal;
    std::optional<std::vector<std::string>> listStringVal;

    VectorLayerFeatureInfoValue(std::optional<std::string> stringVal_,
                                std::optional<double> doubleVal_,
                                std::optional<int64_t> intVal_,
                                std::optional<bool> boolVal_,
                                std::optional<::Color> colorVal_,
                                std::optional<std::vector<float>> listFloatVal_,
                                std::optional<std::vector<std::string>> listStringVal_)
    : stringVal(std::move(stringVal_))
    , doubleVal(std::move(doubleVal_))
    , intVal(std::move(intVal_))
    , boolVal(std::move(boolVal_))
    , colorVal(std::move(colorVal_))
    , listFloatVal(std::move(listFloatVal_))
    , listStringVal(std::move(listStringVal_))
    {}
};
