// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loader.djinni

#pragma once

#include "LoaderStatus.h"
#include <memory>
#include <optional>
#include <utility>

class VectorTileHolderInterface;

struct VectorTileLoaderResult final {
    std::shared_ptr<VectorTileHolderInterface> data;
    LoaderStatus status;

    VectorTileLoaderResult(std::shared_ptr<VectorTileHolderInterface> data_,
                           LoaderStatus status_)
    : data(std::move(data_))
    , status(std::move(status_))
    {}
};
