// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wmts.djinni

#pragma once

#include "Tiled2dMapLayerConfig.h"
#include "Tiled2dMapZoomInfo.h"
#include "Tiled2dMapZoomLevelInfo.h"
#include <memory>
#include <vector>

struct WmtsLayerConfiguration;

class WmtsTiled2dMapLayerConfigFactory {
public:
    virtual ~WmtsTiled2dMapLayerConfigFactory() {}

    static std::shared_ptr<::Tiled2dMapLayerConfig> create(const WmtsLayerConfiguration & wmtsLayerConfiguration, const std::vector<::Tiled2dMapZoomLevelInfo> & zoomLevelInfo, const ::Tiled2dMapZoomInfo & zoomInfo);
};
