// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from styling.djinni

package io.openmobilemaps.mapscore.shared.map.layers;

public enum SizeType {
    SCREEN_PIXEL,
    MAP_UNIT,
    ;
}
