// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

package io.openmobilemaps.mapscore.shared.map.layers.line

enum class LineJoinType {
    BEVEL,
    ROUND,
    MITER,
}
