// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

package io.openmobilemaps.mapscore.shared.map.layers.line

import com.snapchat.djinni.NativeObjectManager
import java.util.concurrent.atomic.AtomicBoolean

abstract class LineFactory {

    companion object {
        @JvmStatic
        external fun createLine(identifier: String, coordinates: ArrayList<io.openmobilemaps.mapscore.shared.map.coordinates.Coord>, style: LineStyle): LineInfoInterface
    }

    public class CppProxy : LineFactory {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
            NativeObjectManager.register(this, nativeRef)
        }

        companion object {
            @JvmStatic
            external fun nativeDestroy(nativeRef: Long)
        }
    }
}
