// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

package io.openmobilemaps.mapscore.shared.graphics.common;

public final class Vec2F {


    /*package*/ final float x;

    /*package*/ final float y;

    public Vec2F(
            float x,
            float y) {
        this.x = x;
        this.y = y;
    }

    public float getX() {
        return x;
    }

    public float getY() {
        return y;
    }

    @Override
    public String toString() {
        return "Vec2F{" +
                "x=" + x +
                "," + "y=" + y +
        "}";
    }

}
