// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

package io.openmobilemaps.mapscore.shared.graphics.common;

public final class Vec3D {


    /*package*/ final double x;

    /*package*/ final double y;

    /*package*/ final double z;

    public Vec3D(
            double x,
            double y,
            double z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }

    public double getX() {
        return x;
    }

    public double getY() {
        return y;
    }

    public double getZ() {
        return z;
    }

    @Override
    public String toString() {
        return "Vec3D{" +
                "x=" + x +
                "," + "y=" + y +
                "," + "z=" + z +
        "}";
    }

}
