// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

import type { Coord } from "@djinni/maps-core/map/coordinates/coordinate_system"
import type { ColorStateList, SizeType } from "@djinni/maps-core/map/layers/styling"
import type { LayerInterface } from "@djinni/maps-core/map/core"

export interface LineFactory {
}
export interface LineFactory_statics {
    createLine(identifier: string, coordinates: Array<Coord>, style: LineStyle): LineInfoInterface;
}

export enum LineCapType {
    BUTT = 0,
    ROUND = 1,
    SQUARE = 2,
}

export enum LineJoinType {
    BEVEL = 0,
    ROUND = 1,
    MITER = 2,
}

export interface /*record*/ LineStyle {
    color: ColorStateList;
    gapColor: ColorStateList;
    opacity: number;
    blur: number;
    widthType: SizeType;
    width: number;
    dashArray: Array<number>;
    dashFade: number;
    dashAnimationSpeed: number;
    lineCap: LineCapType;
    lineJoin: LineJoinType;
    offset: number;
    dotted: boolean;
    dottedSkew: number;
}

export interface LineInfoInterface {
    getIdentifier(): string;
    getCoordinates(): Array<Coord>;
    getStyle(): LineStyle;
}

export interface LineLayerCallbackInterface {
    onLineClickConfirmed(line: LineInfoInterface): void;
}

export interface LineLayerInterface {
    setLines(lines: Array<LineInfoInterface>): void;
    getLines(): Array<LineInfoInterface>;
    remove(line: LineInfoInterface): void;
    add(line: LineInfoInterface): void;
    clear(): void;
    setCallbackHandler(handler: LineLayerCallbackInterface): void;
    asLayerInterface(): LayerInterface;
    invalidate(): void;
    resetSelection(): void;
    setSelected(selectedIds: Set<string>): void;
    setLayerClickable(isLayerClickable: boolean): void;
    setRenderPassIndex(index: number): void;
}
export interface LineLayerInterface_statics {
    create(): LineLayerInterface;
}

export interface Line_statics {
    LineFactory: LineFactory_statics;
    LineLayerInterface: LineLayerInterface_statics;
}
