// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMCameraInterface", exact = true)
actual interface KMCameraInterface
{

    actual fun getVpMatrix(): ArrayList<Float>

    actual fun getScalingFactor(): Double

    actual fun getOrigin(): KMVec3D

    actual fun viewportSizeChanged()
}

private class KMCameraInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCCameraInterfaceProtocol) : KMCameraInterface
{

    override fun getVpMatrix(): ArrayList<Float> {
        val result = nativeHandle.getVpMatrix()
        return ArrayList(((result as? List<*>)?.map { (it as platform.Foundation.NSNumber).floatValue } ?: (0 until (result as platform.Foundation.NSArray).count.toInt()).map { idx -> ((result as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as platform.Foundation.NSNumber).floatValue }))
    }

    override fun getScalingFactor(): Double {
        val result = nativeHandle.getScalingFactor()
        return result
    }

    override fun getOrigin(): KMVec3D {
        val result = nativeHandle.getOrigin()
        return (result as MapCoreSharedModule.MCVec3D).asKmp()
    }

    override fun viewportSizeChanged() {
        nativeHandle.viewportSizeChanged()
    }
}

private class KMCameraInterfacePlatformProxy(private val delegate: KMCameraInterface) : NSObject(), MapCoreSharedModule.MCCameraInterfaceProtocol
{

    override fun getVpMatrix(): List<*> {
        val result = delegate.getVpMatrix()
        return ArrayList(result.map { platform.Foundation.NSNumber(float = it) })
    }

    override fun getScalingFactor(): Double {
        val result = delegate.getScalingFactor()
        return result
    }

    override fun getOrigin(): MapCoreSharedModule.MCVec3D {
        val result = delegate.getOrigin()
        return result.asPlatform()
    }

    override fun viewportSizeChanged() {
        delegate.viewportSizeChanged()
    }
}

internal fun KMCameraInterface.asPlatform(): MapCoreSharedModule.MCCameraInterfaceProtocol = when (this) {
    is KMCameraInterfacePlatformWrapper -> this.nativeHandle
    else -> KMCameraInterfacePlatformProxy(this)
}
internal fun MapCoreSharedModule.MCCameraInterfaceProtocol.asKmp(): KMCameraInterface = KMCameraInterfacePlatformWrapper(this)
