// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMColorCircleShaderInterface", exact = true)
actual class KMColorCircleShaderInterface actual constructor(
    internal val nativeHandle: Any,
) {
    private val native = nativeHandle as MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol

    actual fun setColor(red: Float, green: Float, blue: Float, alpha: Float) {
        native.setColor(red, green, blue, alpha)
    }

    actual fun asShaderProgramInterface(): KMShaderProgramInterface {
        val result = native.asShaderProgramInterface()
        return requireNotNull((result as MapCoreSharedModule.MCShaderProgramInterfaceProtocol)).asKmp()
    }
}

internal fun KMColorCircleShaderInterface.asPlatform(): MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol = nativeHandle as MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol
internal fun MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol.asKmp(): KMColorCircleShaderInterface = KMColorCircleShaderInterface(this)
