// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMMapCallbackInterface", exact = true)
actual interface KMMapCallbackInterface
{

    actual fun invalidate()

    actual fun onMapResumed()
}

private class KMMapCallbackInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCMapCallbackInterfaceProtocol) : KMMapCallbackInterface
{

    override fun invalidate() {
        nativeHandle.invalidate()
    }

    override fun onMapResumed() {
        nativeHandle.onMapResumed()
    }
}

private class KMMapCallbackInterfacePlatformProxy(private val delegate: KMMapCallbackInterface) : NSObject(), MapCoreSharedModule.MCMapCallbackInterfaceProtocol
{

    override fun invalidate() {
        delegate.invalidate()
    }

    override fun onMapResumed() {
        delegate.onMapResumed()
    }
}

internal fun KMMapCallbackInterface.asPlatform(): MapCoreSharedModule.MCMapCallbackInterfaceProtocol = when (this) {
    is KMMapCallbackInterfacePlatformWrapper -> this.nativeHandle
    else -> KMMapCallbackInterfacePlatformProxy(this)
}
internal fun MapCoreSharedModule.MCMapCallbackInterfaceProtocol.asKmp(): KMMapCallbackInterface = KMMapCallbackInterfacePlatformWrapper(this)
