// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRasterShaderStyle", exact = true)
actual class KMRasterShaderStyle actual public constructor(
    opacity: Float,
    brightnessMin: Float,
    brightnessMax: Float,
    contrast: Float,
    saturation: Float,
    gamma: Float,
    brightnessShift: Float,
) {
    actual val opacity: Float = opacity
    actual val brightnessMin: Float = brightnessMin
    actual val brightnessMax: Float = brightnessMax
    actual val contrast: Float = contrast
    actual val saturation: Float = saturation
    actual val gamma: Float = gamma
    actual val brightnessShift: Float = brightnessShift
}

internal fun KMRasterShaderStyle.asPlatform(): MapCoreSharedModule.MCRasterShaderStyle = MapCoreSharedModule.MCRasterShaderStyle(
    opacity = opacity,
    brightnessMin = brightnessMin,
    brightnessMax = brightnessMax,
    contrast = contrast,
    saturation = saturation,
    gamma = gamma,
    brightnessShift = brightnessShift,
)
internal fun MapCoreSharedModule.MCRasterShaderStyle.asKmp(): KMRasterShaderStyle = KMRasterShaderStyle(
    opacity = this.opacity,
    brightnessMin = this.brightnessMin,
    brightnessMax = this.brightnessMax,
    contrast = this.contrast,
    saturation = this.saturation,
    gamma = this.gamma,
    brightnessShift = this.brightnessShift,
)
