// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMShaderFactoryInterface", exact = true)
actual interface KMShaderFactoryInterface
{

    actual fun createAlphaShader(): KMAlphaShaderInterface

    actual fun createUnitSphereAlphaShader(): KMAlphaShaderInterface

    actual fun createAlphaInstancedShader(): KMAlphaInstancedShaderInterface

    actual fun createUnitSphereAlphaInstancedShader(): KMAlphaInstancedShaderInterface

    actual fun createLineGroupShader(): KMLineGroupShaderInterface

    actual fun createUnitSphereLineGroupShader(): KMLineGroupShaderInterface

    actual fun createSimpleLineGroupShader(): KMLineGroupShaderInterface

    actual fun createUnitSphereSimpleLineGroupShader(): KMLineGroupShaderInterface

    actual fun createUnitSphereColorShader(): KMColorShaderInterface

    actual fun createColorShader(): KMColorShaderInterface

    actual fun createColorCircleShader(): KMColorCircleShaderInterface

    actual fun createUnitSphereColorCircleShader(): KMColorCircleShaderInterface

    actual fun createPolygonGroupShader(isStriped: Boolean, unitSphere: Boolean): KMPolygonGroupShaderInterface

    actual fun createPolygonPatternGroupShader(fadeInPattern: Boolean, unitSphere: Boolean): KMPolygonPatternGroupShaderInterface

    actual fun createTextShader(): KMTextShaderInterface

    actual fun createTextInstancedShader(): KMTextInstancedShaderInterface

    actual fun createUnitSphereTextInstancedShader(): KMTextInstancedShaderInterface

    actual fun createRasterShader(): KMRasterShaderInterface

    actual fun createUnitSphereRasterShader(): KMRasterShaderInterface

    actual fun createStretchShader(): KMStretchShaderInterface

    actual fun createStretchInstancedShader(unitSphere: Boolean): KMStretchInstancedShaderInterface

    actual fun createIcosahedronColorShader(): KMColorShaderInterface

    actual fun createSphereEffectShader(): KMSphereEffectShaderInterface

    actual fun createSkySphereShader(): KMSkySphereShaderInterface

    actual fun createElevationInterpolationShader(): KMElevationInterpolationShaderInterface
}

private class KMShaderFactoryInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCShaderFactoryInterfaceProtocol) : KMShaderFactoryInterface
{

    override fun createAlphaShader(): KMAlphaShaderInterface {
        val result = nativeHandle.createAlphaShader()
        return requireNotNull((result as MapCoreSharedModule.MCAlphaShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereAlphaShader(): KMAlphaShaderInterface {
        val result = nativeHandle.createUnitSphereAlphaShader()
        return requireNotNull((result as MapCoreSharedModule.MCAlphaShaderInterfaceProtocol)).asKmp()
    }

    override fun createAlphaInstancedShader(): KMAlphaInstancedShaderInterface {
        val result = nativeHandle.createAlphaInstancedShader()
        return requireNotNull((result as MapCoreSharedModule.MCAlphaInstancedShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereAlphaInstancedShader(): KMAlphaInstancedShaderInterface {
        val result = nativeHandle.createUnitSphereAlphaInstancedShader()
        return requireNotNull((result as MapCoreSharedModule.MCAlphaInstancedShaderInterfaceProtocol)).asKmp()
    }

    override fun createLineGroupShader(): KMLineGroupShaderInterface {
        val result = nativeHandle.createLineGroupShader()
        return requireNotNull((result as MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereLineGroupShader(): KMLineGroupShaderInterface {
        val result = nativeHandle.createUnitSphereLineGroupShader()
        return requireNotNull((result as MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createSimpleLineGroupShader(): KMLineGroupShaderInterface {
        val result = nativeHandle.createSimpleLineGroupShader()
        return requireNotNull((result as MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereSimpleLineGroupShader(): KMLineGroupShaderInterface {
        val result = nativeHandle.createUnitSphereSimpleLineGroupShader()
        return requireNotNull((result as MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereColorShader(): KMColorShaderInterface {
        val result = nativeHandle.createUnitSphereColorShader()
        return requireNotNull((result as MapCoreSharedModule.MCColorShaderInterfaceProtocol)).asKmp()
    }

    override fun createColorShader(): KMColorShaderInterface {
        val result = nativeHandle.createColorShader()
        return requireNotNull((result as MapCoreSharedModule.MCColorShaderInterfaceProtocol)).asKmp()
    }

    override fun createColorCircleShader(): KMColorCircleShaderInterface {
        val result = nativeHandle.createColorCircleShader()
        return requireNotNull((result as MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereColorCircleShader(): KMColorCircleShaderInterface {
        val result = nativeHandle.createUnitSphereColorCircleShader()
        return requireNotNull((result as MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol)).asKmp()
    }

    override fun createPolygonGroupShader(isStriped: Boolean, unitSphere: Boolean): KMPolygonGroupShaderInterface {
        val result = nativeHandle.createPolygonGroupShader(isStriped, unitSphere)
        return requireNotNull((result as MapCoreSharedModule.MCPolygonGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createPolygonPatternGroupShader(fadeInPattern: Boolean, unitSphere: Boolean): KMPolygonPatternGroupShaderInterface {
        val result = nativeHandle.createPolygonPatternGroupShader(fadeInPattern, unitSphere)
        return requireNotNull((result as MapCoreSharedModule.MCPolygonPatternGroupShaderInterfaceProtocol)).asKmp()
    }

    override fun createTextShader(): KMTextShaderInterface {
        val result = nativeHandle.createTextShader()
        return requireNotNull((result as MapCoreSharedModule.MCTextShaderInterfaceProtocol)).asKmp()
    }

    override fun createTextInstancedShader(): KMTextInstancedShaderInterface {
        val result = nativeHandle.createTextInstancedShader()
        return requireNotNull((result as MapCoreSharedModule.MCTextInstancedShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereTextInstancedShader(): KMTextInstancedShaderInterface {
        val result = nativeHandle.createUnitSphereTextInstancedShader()
        return requireNotNull((result as MapCoreSharedModule.MCTextInstancedShaderInterfaceProtocol)).asKmp()
    }

    override fun createRasterShader(): KMRasterShaderInterface {
        val result = nativeHandle.createRasterShader()
        return requireNotNull((result as MapCoreSharedModule.MCRasterShaderInterfaceProtocol)).asKmp()
    }

    override fun createUnitSphereRasterShader(): KMRasterShaderInterface {
        val result = nativeHandle.createUnitSphereRasterShader()
        return requireNotNull((result as MapCoreSharedModule.MCRasterShaderInterfaceProtocol)).asKmp()
    }

    override fun createStretchShader(): KMStretchShaderInterface {
        val result = nativeHandle.createStretchShader()
        return requireNotNull((result as MapCoreSharedModule.MCStretchShaderInterfaceProtocol)).asKmp()
    }

    override fun createStretchInstancedShader(unitSphere: Boolean): KMStretchInstancedShaderInterface {
        val result = nativeHandle.createStretchInstancedShader(unitSphere)
        return requireNotNull((result as MapCoreSharedModule.MCStretchInstancedShaderInterfaceProtocol)).asKmp()
    }

    override fun createIcosahedronColorShader(): KMColorShaderInterface {
        val result = nativeHandle.createIcosahedronColorShader()
        return requireNotNull((result as MapCoreSharedModule.MCColorShaderInterfaceProtocol)).asKmp()
    }

    override fun createSphereEffectShader(): KMSphereEffectShaderInterface {
        val result = nativeHandle.createSphereEffectShader()
        return requireNotNull((result as MapCoreSharedModule.MCSphereEffectShaderInterfaceProtocol)).asKmp()
    }

    override fun createSkySphereShader(): KMSkySphereShaderInterface {
        val result = nativeHandle.createSkySphereShader()
        return requireNotNull((result as MapCoreSharedModule.MCSkySphereShaderInterfaceProtocol)).asKmp()
    }

    override fun createElevationInterpolationShader(): KMElevationInterpolationShaderInterface {
        val result = nativeHandle.createElevationInterpolationShader()
        return requireNotNull((result as MapCoreSharedModule.MCElevationInterpolationShaderInterfaceProtocol)).asKmp()
    }
}

private class KMShaderFactoryInterfacePlatformProxy(private val delegate: KMShaderFactoryInterface) : NSObject(), MapCoreSharedModule.MCShaderFactoryInterfaceProtocol
{

    override fun createAlphaShader(): MapCoreSharedModule.MCAlphaShaderInterfaceProtocol? {
        val result = delegate.createAlphaShader()
        return result.asPlatform()
    }

    override fun createUnitSphereAlphaShader(): MapCoreSharedModule.MCAlphaShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereAlphaShader()
        return result.asPlatform()
    }

    override fun createAlphaInstancedShader(): MapCoreSharedModule.MCAlphaInstancedShaderInterfaceProtocol? {
        val result = delegate.createAlphaInstancedShader()
        return result.asPlatform()
    }

    override fun createUnitSphereAlphaInstancedShader(): MapCoreSharedModule.MCAlphaInstancedShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereAlphaInstancedShader()
        return result.asPlatform()
    }

    override fun createLineGroupShader(): MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol? {
        val result = delegate.createLineGroupShader()
        return result.asPlatform()
    }

    override fun createUnitSphereLineGroupShader(): MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereLineGroupShader()
        return result.asPlatform()
    }

    override fun createSimpleLineGroupShader(): MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol? {
        val result = delegate.createSimpleLineGroupShader()
        return result.asPlatform()
    }

    override fun createUnitSphereSimpleLineGroupShader(): MapCoreSharedModule.MCLineGroupShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereSimpleLineGroupShader()
        return result.asPlatform()
    }

    override fun createUnitSphereColorShader(): MapCoreSharedModule.MCColorShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereColorShader()
        return result.asPlatform()
    }

    override fun createColorShader(): MapCoreSharedModule.MCColorShaderInterfaceProtocol? {
        val result = delegate.createColorShader()
        return result.asPlatform()
    }

    override fun createColorCircleShader(): MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol? {
        val result = delegate.createColorCircleShader()
        return result.asPlatform()
    }

    override fun createUnitSphereColorCircleShader(): MapCoreSharedModule.MCColorCircleShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereColorCircleShader()
        return result.asPlatform()
    }

    override fun createPolygonGroupShader(isStriped: Boolean, unitSphere: Boolean): MapCoreSharedModule.MCPolygonGroupShaderInterfaceProtocol? {
        val result = delegate.createPolygonGroupShader(isStriped, unitSphere)
        return result.asPlatform()
    }

    override fun createPolygonPatternGroupShader(fadeInPattern: Boolean, unitSphere: Boolean): MapCoreSharedModule.MCPolygonPatternGroupShaderInterfaceProtocol? {
        val result = delegate.createPolygonPatternGroupShader(fadeInPattern, unitSphere)
        return result.asPlatform()
    }

    override fun createTextShader(): MapCoreSharedModule.MCTextShaderInterfaceProtocol? {
        val result = delegate.createTextShader()
        return result.asPlatform()
    }

    override fun createTextInstancedShader(): MapCoreSharedModule.MCTextInstancedShaderInterfaceProtocol? {
        val result = delegate.createTextInstancedShader()
        return result.asPlatform()
    }

    override fun createUnitSphereTextInstancedShader(): MapCoreSharedModule.MCTextInstancedShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereTextInstancedShader()
        return result.asPlatform()
    }

    override fun createRasterShader(): MapCoreSharedModule.MCRasterShaderInterfaceProtocol? {
        val result = delegate.createRasterShader()
        return result.asPlatform()
    }

    override fun createUnitSphereRasterShader(): MapCoreSharedModule.MCRasterShaderInterfaceProtocol? {
        val result = delegate.createUnitSphereRasterShader()
        return result.asPlatform()
    }

    override fun createStretchShader(): MapCoreSharedModule.MCStretchShaderInterfaceProtocol? {
        val result = delegate.createStretchShader()
        return result.asPlatform()
    }

    override fun createStretchInstancedShader(unitSphere: Boolean): MapCoreSharedModule.MCStretchInstancedShaderInterfaceProtocol? {
        val result = delegate.createStretchInstancedShader(unitSphere)
        return result.asPlatform()
    }

    override fun createIcosahedronColorShader(): MapCoreSharedModule.MCColorShaderInterfaceProtocol? {
        val result = delegate.createIcosahedronColorShader()
        return result.asPlatform()
    }

    override fun createSphereEffectShader(): MapCoreSharedModule.MCSphereEffectShaderInterfaceProtocol? {
        val result = delegate.createSphereEffectShader()
        return result.asPlatform()
    }

    override fun createSkySphereShader(): MapCoreSharedModule.MCSkySphereShaderInterfaceProtocol? {
        val result = delegate.createSkySphereShader()
        return result.asPlatform()
    }

    override fun createElevationInterpolationShader(): MapCoreSharedModule.MCElevationInterpolationShaderInterfaceProtocol? {
        val result = delegate.createElevationInterpolationShader()
        return result.asPlatform()
    }
}

internal fun KMShaderFactoryInterface.asPlatform(): MapCoreSharedModule.MCShaderFactoryInterfaceProtocol = when (this) {
    is KMShaderFactoryInterfacePlatformWrapper -> this.nativeHandle
    else -> KMShaderFactoryInterfacePlatformProxy(this)
}
internal fun MapCoreSharedModule.MCShaderFactoryInterfaceProtocol.asKmp(): KMShaderFactoryInterface = KMShaderFactoryInterfacePlatformWrapper(this)
