// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_layer.djinni

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTiled2dMapVectorSettings", exact = true)
actual class KMTiled2dMapVectorSettings actual constructor(
    tileOrigin: KMTiled2dMapVectorTileOrigin,
) {
    actual val tileOrigin: KMTiled2dMapVectorTileOrigin = tileOrigin
}

internal fun KMTiled2dMapVectorSettings.asPlatform(): MapCoreSharedModule.MCTiled2dMapVectorSettings = MapCoreSharedModule.MCTiled2dMapVectorSettings(
    tileOrigin = tileOrigin.asPlatform(),
)
internal fun MapCoreSharedModule.MCTiled2dMapVectorSettings.asKmp(): KMTiled2dMapVectorSettings = KMTiled2dMapVectorSettings(
    tileOrigin = KMTiled2dMapVectorTileOrigin.fromPlatform((this.tileOrigin as MapCoreSharedModule.MCTiled2dMapVectorTileOrigin)),
)
