// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from touch_handler.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTouchInterface", exact = true)
actual interface KMTouchInterface
{

    actual fun onTouchDown(posScreen: KMVec2F): Boolean

    actual fun onClickUnconfirmed(posScreen: KMVec2F): Boolean

    actual fun onClickConfirmed(posScreen: KMVec2F): Boolean

    actual fun onDoubleClick(posScreen: KMVec2F): Boolean

    actual fun onLongPress(posScreen: KMVec2F): Boolean

    actual fun onMove(deltaScreen: KMVec2F, confirmed: Boolean, doubleClick: Boolean): Boolean

    actual fun onMoveComplete(): Boolean

    actual fun onOneFingerDoubleClickMoveComplete(): Boolean

    actual fun onTwoFingerClick(posScreen1: KMVec2F, posScreen2: KMVec2F): Boolean

    actual fun onTwoFingerMove(posScreenOld: ArrayList<KMVec2F>, posScreenNew: ArrayList<KMVec2F>): Boolean

    actual fun onTwoFingerMoveComplete(): Boolean

    actual fun clearTouch()
}

private class KMTouchInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCTouchInterfaceProtocol) : KMTouchInterface
{

    override fun onTouchDown(posScreen: KMVec2F): Boolean {
        val result = nativeHandle.onTouchDown(posScreen.asPlatform())
        return result
    }

    override fun onClickUnconfirmed(posScreen: KMVec2F): Boolean {
        val result = nativeHandle.onClickUnconfirmed(posScreen.asPlatform())
        return result
    }

    override fun onClickConfirmed(posScreen: KMVec2F): Boolean {
        val result = nativeHandle.onClickConfirmed(posScreen.asPlatform())
        return result
    }

    override fun onDoubleClick(posScreen: KMVec2F): Boolean {
        val result = nativeHandle.onDoubleClick(posScreen.asPlatform())
        return result
    }

    override fun onLongPress(posScreen: KMVec2F): Boolean {
        val result = nativeHandle.onLongPress(posScreen.asPlatform())
        return result
    }

    override fun onMove(deltaScreen: KMVec2F, confirmed: Boolean, doubleClick: Boolean): Boolean {
        val result = nativeHandle.onMove(deltaScreen.asPlatform(), confirmed, doubleClick)
        return result
    }

    override fun onMoveComplete(): Boolean {
        val result = nativeHandle.onMoveComplete()
        return result
    }

    override fun onOneFingerDoubleClickMoveComplete(): Boolean {
        val result = nativeHandle.onOneFingerDoubleClickMoveComplete()
        return result
    }

    override fun onTwoFingerClick(posScreen1: KMVec2F, posScreen2: KMVec2F): Boolean {
        val result = nativeHandle.onTwoFingerClick(posScreen1.asPlatform(), posScreen2.asPlatform())
        return result
    }

    override fun onTwoFingerMove(posScreenOld: ArrayList<KMVec2F>, posScreenNew: ArrayList<KMVec2F>): Boolean {
        val result = nativeHandle.onTwoFingerMove(ArrayList(posScreenOld.map { it.asPlatform() }), ArrayList(posScreenNew.map { it.asPlatform() }))
        return result
    }

    override fun onTwoFingerMoveComplete(): Boolean {
        val result = nativeHandle.onTwoFingerMoveComplete()
        return result
    }

    override fun clearTouch() {
        nativeHandle.clearTouch()
    }
}

private class KMTouchInterfacePlatformProxy(private val delegate: KMTouchInterface) : NSObject(), MapCoreSharedModule.MCTouchInterfaceProtocol
{

    override fun onTouchDown(posScreen: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onTouchDown((posScreen as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onClickUnconfirmed(posScreen: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onClickUnconfirmed((posScreen as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onClickConfirmed(posScreen: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onClickConfirmed((posScreen as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onDoubleClick(posScreen: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onDoubleClick((posScreen as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onLongPress(posScreen: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onLongPress((posScreen as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onMove(deltaScreen: MapCoreSharedModule.MCVec2F, confirmed: Boolean, doubleClick: Boolean): Boolean {
        val result = delegate.onMove((deltaScreen as MapCoreSharedModule.MCVec2F).asKmp(), confirmed, doubleClick)
        return result
    }

    override fun onMoveComplete(): Boolean {
        val result = delegate.onMoveComplete()
        return result
    }

    override fun onOneFingerDoubleClickMoveComplete(): Boolean {
        val result = delegate.onOneFingerDoubleClickMoveComplete()
        return result
    }

    override fun onTwoFingerClick(posScreen1: MapCoreSharedModule.MCVec2F, posScreen2: MapCoreSharedModule.MCVec2F): Boolean {
        val result = delegate.onTwoFingerClick((posScreen1 as MapCoreSharedModule.MCVec2F).asKmp(), (posScreen2 as MapCoreSharedModule.MCVec2F).asKmp())
        return result
    }

    override fun onTwoFingerMove(posScreenOld: List<*>, posScreenNew: List<*>): Boolean {
        val result = delegate.onTwoFingerMove(ArrayList(((posScreenOld as? List<*>)?.map { (it as MapCoreSharedModule.MCVec2F).asKmp() } ?: (0 until (posScreenOld as platform.Foundation.NSArray).count.toInt()).map { idx -> ((posScreenOld as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MapCoreSharedModule.MCVec2F).asKmp() })), ArrayList(((posScreenNew as? List<*>)?.map { (it as MapCoreSharedModule.MCVec2F).asKmp() } ?: (0 until (posScreenNew as platform.Foundation.NSArray).count.toInt()).map { idx -> ((posScreenNew as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MapCoreSharedModule.MCVec2F).asKmp() })))
        return result
    }

    override fun onTwoFingerMoveComplete(): Boolean {
        val result = delegate.onTwoFingerMoveComplete()
        return result
    }

    override fun clearTouch() {
        delegate.clearTouch()
    }
}

internal fun KMTouchInterface.asPlatform(): MapCoreSharedModule.MCTouchInterfaceProtocol = when (this) {
    is KMTouchInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTouchInterfacePlatformProxy(this)
}
internal fun MapCoreSharedModule.MCTouchInterfaceProtocol.asKmp(): KMTouchInterface = KMTouchInterfacePlatformWrapper(this)
