// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMVectorLayerFeatureCoordInfo", exact = true)
actual class KMVectorLayerFeatureCoordInfo actual constructor(
    featureInfo: KMVectorLayerFeatureInfo,
    coordinates: KMCoord,
) {
    actual val featureInfo: KMVectorLayerFeatureInfo = featureInfo
    actual val coordinates: KMCoord = coordinates
}

internal fun KMVectorLayerFeatureCoordInfo.asPlatform(): MapCoreSharedModule.MCVectorLayerFeatureCoordInfo = MapCoreSharedModule.MCVectorLayerFeatureCoordInfo(
    featureInfo = featureInfo.asPlatform(),
    coordinates = coordinates.asPlatform(),
)
internal fun MapCoreSharedModule.MCVectorLayerFeatureCoordInfo.asKmp(): KMVectorLayerFeatureCoordInfo = KMVectorLayerFeatureCoordInfo(
    featureInfo = (this.featureInfo as MapCoreSharedModule.MCVectorLayerFeatureInfo).asKmp(),
    coordinates = (this.coordinates as MapCoreSharedModule.MCCoord).asKmp(),
)
