GROUP=io.openmobilemaps
POM_ARTIFACT_ID=mapscore-kmp
VERSION_NAME=4.0.0

POM_NAME=mapscore-kmp
POM_PACKAGING=aar
POM_DESCRIPTION=The KMP wrapper for the lightweight and modern Map SDK for Android 8.0+
POM_INCEPTION_YEAR=2026

POM_URL=https://github.com/openmobilemaps/maps-core
POM_SCM_URL=https://github.com/openmobilemaps/maps-core
POM_SCM_CONNECTION=scm:git@github.com:openmobilemaps/maps-core.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:openmobilemaps/maps-core.git

POM_LICENCE_NAME=Mozilla Public License 2.0
POM_LICENCE_URL=https://www.mozilla.org/en-US/MPL/2.0/
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=openmobilemaps
POM_DEVELOPER_NAME=Open Mobile Maps
POM_DEVELOPER_URL=https://github.com/openmobilemaps

SONATYPE_STAGING_PROFILE=io.openmobilemaps