// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map_helpers.djinni

import type { RectCoord } from "@djinni/maps-core/map/coordinates/coordinate_system"
import type { LoaderStatus } from "@djinni/maps-core/map/loader/loader"

export interface ErrorManager {
    addTiledLayerError(error: TiledLayerError): void;
    removeError(url: string): void;
    removeAllErrorsForLayer(layerName: string): void;
    clearAllErrors(): void;
    addErrorListener(listener: ErrorManagerListener): void;
    removeErrorListener(listener: ErrorManagerListener): void;
}
export interface ErrorManager_statics {
    create(): ErrorManager;
}

export interface ErrorManagerListener {
    onTiledLayerErrorStateChanged(errors: Array<TiledLayerError>): void;
}

export interface /*record*/ TiledLayerError {
    status: LoaderStatus;
    errorCode?: string;
    layerName: string;
    url: string;
    isRecoverable: boolean;
    bounds?: RectCoord;
}

export interface PerformanceLoggerInterface {
    getLoggerName(): string;
    startLog(id: string): void;
    endLog(id: string): void;
    getStatistics(id: string): LoggerData | undefined;
    getAllStatistics(): Array<LoggerData>;
    resetData(): void;
    setLoggingEnabled(enabled: boolean): void;
}

export interface OpenGlPerformanceLoggerInterface {
    asPerformanceLoggerInterface(): PerformanceLoggerInterface;
}
export interface OpenGlPerformanceLoggerInterface_statics {
    create(): OpenGlPerformanceLoggerInterface;
    createSpecifically(numBuckets: number, bucketSizeMs: bigint): OpenGlPerformanceLoggerInterface;
}

export interface CpuPerformanceLoggerInterface {
    asPerformanceLoggerInterface(): PerformanceLoggerInterface;
}
export interface CpuPerformanceLoggerInterface_statics {
    create(): CpuPerformanceLoggerInterface;
    createSpecifically(numBuckets: number, bucketSizeMs: bigint): CpuPerformanceLoggerInterface;
}

export interface /*record*/ LoggerData {
    id: string;
    buckets: Array<bigint>;
    bucketSizeMs: number;
    start: bigint;
    end: bigint;
    numSamples: bigint;
    average: number;
    variance: number;
    stdDeviation: number;
}

export interface MapHelpers_statics {
    ErrorManager: ErrorManager_statics;
    OpenGlPerformanceLoggerInterface: OpenGlPerformanceLoggerInterface_statics;
    CpuPerformanceLoggerInterface: CpuPerformanceLoggerInterface_statics;
}
