// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#pragma once

class SceneCallbackInterface {
public:
    virtual ~SceneCallbackInterface() {}

    virtual void invalidate() = 0;
};
