// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCCameraInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCVec3D

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMCameraInterface", exact = true)
actual interface KMCameraInterface
{

    actual fun getVpMatrix(): List<Float>

    actual fun getScalingFactor(): Double

    actual fun getOrigin(): io.openmobilemaps.mapscore.kmp.KMVec3D

    actual fun viewportSizeChanged()
}

private class KMCameraInterfacePlatformWrapper(internal val nativeHandle: MCCameraInterfaceProtocol) : KMCameraInterface
{

    override fun getVpMatrix(): List<Float> {
        val result = nativeHandle.getVpMatrix()
        return ArrayList(((result as? List<*>)?.map { (it as platform.Foundation.NSNumber).floatValue } ?: (0 until (result as platform.Foundation.NSArray).count.toInt()).map { idx -> ((result as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as platform.Foundation.NSNumber).floatValue }))
    }

    override fun getScalingFactor(): Double {
        val result = nativeHandle.getScalingFactor()
        return result
    }

    override fun getOrigin(): io.openmobilemaps.mapscore.kmp.KMVec3D {
        val result = nativeHandle.getOrigin()
        return (result as MCVec3D).asKmp()
    }

    override fun viewportSizeChanged() {
        nativeHandle.viewportSizeChanged()
    }
}

private class KMCameraInterfacePlatformProxy(private val delegate: KMCameraInterface) : NSObject(), MCCameraInterfaceProtocol
{

    override fun getVpMatrix(): List<*> {
        val result = delegate.getVpMatrix()
        return ArrayList(result.map { platform.Foundation.NSNumber(float = it) })
    }

    override fun getScalingFactor(): Double {
        val result = delegate.getScalingFactor()
        return result
    }

    override fun getOrigin(): MCVec3D {
        val result = delegate.getOrigin()
        return result.asPlatform()
    }

    override fun viewportSizeChanged() {
        delegate.viewportSizeChanged()
    }
}

public fun KMCameraInterface.asPlatform(): MCCameraInterfaceProtocol = when (this) {
    is KMCameraInterfacePlatformWrapper -> this.nativeHandle
    else -> KMCameraInterfacePlatformProxy(this)
}
public fun MCCameraInterfaceProtocol.asKmp(): KMCameraInterface = KMCameraInterfacePlatformWrapper(this)
