// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMCircleI", exact = true)
actual class KMCircleI actual public constructor(
    x: Int,
    y: Int,
    radius: Int,
) {
    actual val x: Int = x
    actual val y: Int = y
    actual val radius: Int = radius
}

internal fun KMCircleI.asPlatform(): MapCoreSharedModule.MCCircleI = MapCoreSharedModule.MCCircleI(
    x = x,
    y = y,
    radius = radius,
)
public fun MapCoreSharedModule.MCCircleI.asKmp(): KMCircleI = KMCircleI(
    x = this.x,
    y = this.y,
    radius = this.radius,
)
