// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMCircleD", exact = true)
actual class KMCircleD actual public constructor(
    x: Double,
    y: Double,
    radius: Double,
) {
    actual val x: Double = x
    actual val y: Double = y
    actual val radius: Double = radius
}

internal fun KMCircleD.asPlatform(): MapCoreSharedModule.MCCircleD = MapCoreSharedModule.MCCircleD(
    x = x,
    y = y,
    radius = radius,
)
public fun MapCoreSharedModule.MCCircleD.asKmp(): KMCircleD = KMCircleD(
    x = this.x,
    y = this.y,
    radius = this.radius,
)
