// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCColor

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMColor", exact = true)
actual class KMColor actual public constructor(
    r: Float,
    g: Float,
    b: Float,
    a: Float,
) {
    actual val r: Float = r
    actual val g: Float = g
    actual val b: Float = b
    actual val a: Float = a
}

public fun KMColor.asPlatform(): MCColor = MCColor(
    r = r,
    g = g,
    b = b,
    a = a,
)
public fun MCColor.asKmp(): KMColor = KMColor(
    r = this.r,
    g = this.g,
    b = this.b,
    a = this.a,
)
