// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCElevationInterpolationShaderInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCShaderProgramInterfaceProtocol

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMElevationInterpolationShaderInterface", exact = true)
actual class KMElevationInterpolationShaderInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MCElevationInterpolationShaderInterfaceProtocol

    actual fun asShaderProgramInterface(): KMShaderProgramInterface {
        val result = native.asShaderProgramInterface()
        return (result as MCShaderProgramInterfaceProtocol).asKmp()
    }
}

public fun KMElevationInterpolationShaderInterface.asPlatform(): MCElevationInterpolationShaderInterfaceProtocol = nativeHandle as MCElevationInterpolationShaderInterfaceProtocol
public fun MCElevationInterpolationShaderInterfaceProtocol.asKmp(): KMElevationInterpolationShaderInterface = KMElevationInterpolationShaderInterface(this)
