// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map_helpers.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMErrorManager", exact = true)
actual class KMErrorManager actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MapCoreSharedModule.MCErrorManager

    actual fun addTiledLayerError(error: KMTiledLayerError) {
        native.addTiledLayerError(error.asPlatform())
    }

    actual fun removeError(url: String) {
        native.removeError(url)
    }

    actual fun removeAllErrorsForLayer(layerName: String) {
        native.removeAllErrorsForLayer(layerName)
    }

    actual fun clearAllErrors() {
        native.clearAllErrors()
    }

    actual fun addErrorListener(listener: KMErrorManagerListener) {
        native.addErrorListener(listener.asPlatform())
    }

    actual fun removeErrorListener(listener: KMErrorManagerListener) {
        native.removeErrorListener(listener.asPlatform())
    }

    actual companion object
    {

        actual fun create(): KMErrorManager {
            val result = MapCoreSharedModule.MCErrorManager.create()
            return (result as MapCoreSharedModule.MCErrorManager).asKmp()
        }
    }
}

internal fun KMErrorManager.asPlatform(): MapCoreSharedModule.MCErrorManager = nativeHandle as MapCoreSharedModule.MCErrorManager
internal fun MapCoreSharedModule.MCErrorManager.asKmp(): KMErrorManager = KMErrorManager(this)
