// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMFeatureInfoValueFactory", exact = true)
actual class KMFeatureInfoValueFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MapCoreSharedModule.MCFeatureInfoValueFactory

    actual companion object
    {

        actual fun createString(value: String): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createString(value)
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createDouble(value: Double): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createDouble(value)
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createInt(value: Long): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createInt(value)
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createBool(value: Boolean): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createBool(value)
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createColor(value: KMColor): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createColor(value.asPlatform())
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createListFloat(value: ArrayList<Float>): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createListFloat(ArrayList(value.map { platform.Foundation.NSNumber(float = it) }))
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }

        actual fun createListString(value: ArrayList<String>): KMVectorLayerFeatureInfoValue {
            val result = MapCoreSharedModule.MCFeatureInfoValueFactory.createListString(ArrayList(value.map { it }))
            return (result as MapCoreSharedModule.MCVectorLayerFeatureInfoValue).asKmp()
        }
    }
}

internal fun KMFeatureInfoValueFactory.asPlatform(): MapCoreSharedModule.MCFeatureInfoValueFactory = nativeHandle as MapCoreSharedModule.MCFeatureInfoValueFactory
public fun MapCoreSharedModule.MCFeatureInfoValueFactory.asKmp(): KMFeatureInfoValueFactory = KMFeatureInfoValueFactory(this)
