// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCFormattedStringEntry

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMFormattedStringEntry", exact = true)
actual class KMFormattedStringEntry actual public constructor(
    text: String,
    scale: Float,
) {
    actual val text: String = text
    actual val scale: Float = scale
}

public fun KMFormattedStringEntry.asPlatform(): MCFormattedStringEntry = MCFormattedStringEntry(
    text = text,
    scale = scale,
)
public fun MCFormattedStringEntry.asKmp(): KMFormattedStringEntry = KMFormattedStringEntry(
    text = this.text,
    scale = this.scale,
)
