// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from geo_json_parser.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMGeoJsonLine", exact = true)
actual class KMGeoJsonLine actual public constructor(
    points: ArrayList<KMCoord>,
    featureInfo: KMVectorLayerFeatureInfo,
) {
    actual val points: ArrayList<KMCoord> = points
    actual val featureInfo: KMVectorLayerFeatureInfo = featureInfo
}

internal fun KMGeoJsonLine.asPlatform(): MapCoreSharedModule.MCGeoJsonLine = MapCoreSharedModule.MCGeoJsonLine(
    points = ArrayList(points.map { it.asPlatform() }),
    featureInfo = featureInfo.asPlatform(),
)
public fun MapCoreSharedModule.MCGeoJsonLine.asKmp(): KMGeoJsonLine = KMGeoJsonLine(
    points = ArrayList(((this.points as? List<*>)?.map { (it as MapCoreSharedModule.MCCoord).asKmp() } ?: (0 until (this.points as platform.Foundation.NSArray).count.toInt()).map { idx -> ((this.points as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MapCoreSharedModule.MCCoord).asKmp() })),
    featureInfo = (this.featureInfo as MapCoreSharedModule.MCVectorLayerFeatureInfo).asKmp(),
)
