// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCIconTextFit

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMIconTextFit", exact = true)
actual enum class KMIconTextFit(internal val platformValue: Long) {
    NONE(0L),
    WIDTH(1L),
    HEIGHT(2L),
    BOTH(3L),
    ;

    companion object {
        public fun fromPlatform(value: MCIconTextFit): KMIconTextFit {
            val raw: Long = value
            return when (raw) {
                0L -> KMIconTextFit.NONE
                1L -> KMIconTextFit.WIDTH
                2L -> KMIconTextFit.HEIGHT
                3L -> KMIconTextFit.BOTH
                else -> throw IllegalArgumentException("Unknown KMIconTextFit value: " + raw)
            }
        }
    }
}

public fun KMIconTextFit.asPlatform(): MCIconTextFit = platformValue
