// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCCoord
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCLineFactory
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCLineInfoInterface
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCLineStyle

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMLineFactory", exact = true)
actual class KMLineFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MCLineFactory

    actual companion object
    {

        actual fun createLine(identifier: String, coordinates: List<io.openmobilemaps.mapscore.kmp.KMCoord>, style: KMLineStyle): KMLineInfoInterface {
            val result = MCLineFactory.createLine(identifier, ArrayList(coordinates.map { it.asPlatform() }), style.asPlatform())
            return (result as MCLineInfoInterface).asKmp()
        }
    }
}

public fun KMLineFactory.asPlatform(): MCLineFactory = nativeHandle as MCLineFactory
public fun MCLineFactory.asKmp(): KMLineFactory = KMLineFactory(this)
