// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMPolygon2dInterface", exact = true)
actual interface KMPolygon2dInterface
{

    actual fun setVertices(vertices: KMSharedBytes, indices: KMSharedBytes, origin: KMVec3D)

    actual fun asGraphicsObject(): KMGraphicsObjectInterface

    actual fun asMaskingObject(): KMMaskingObjectInterface
}

private class KMPolygon2dInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCPolygon2dInterfaceProtocol) : KMPolygon2dInterface
{

    override fun setVertices(vertices: KMSharedBytes, indices: KMSharedBytes, origin: KMVec3D) {
        nativeHandle.setVertices(vertices.asPlatform(), indices.asPlatform(), origin.asPlatform())
    }

    override fun asGraphicsObject(): KMGraphicsObjectInterface {
        val result = nativeHandle.asGraphicsObject()
        return requireNotNull((result as MapCoreSharedModule.MCGraphicsObjectInterfaceProtocol)).asKmp()
    }

    override fun asMaskingObject(): KMMaskingObjectInterface {
        val result = nativeHandle.asMaskingObject()
        return requireNotNull((result as MapCoreSharedModule.MCMaskingObjectInterfaceProtocol)).asKmp()
    }
}

private class KMPolygon2dInterfacePlatformProxy(private val delegate: KMPolygon2dInterface) : NSObject(), MapCoreSharedModule.MCPolygon2dInterfaceProtocol
{

    override fun setVertices(vertices: MapCoreSharedModule.MCSharedBytes, indices: MapCoreSharedModule.MCSharedBytes, origin: MapCoreSharedModule.MCVec3D) {
        delegate.setVertices((vertices as MapCoreSharedModule.MCSharedBytes).asKmp(), (indices as MapCoreSharedModule.MCSharedBytes).asKmp(), (origin as MapCoreSharedModule.MCVec3D).asKmp())
    }

    override fun asGraphicsObject(): MapCoreSharedModule.MCGraphicsObjectInterfaceProtocol? {
        val result = delegate.asGraphicsObject()
        return result.asPlatform()
    }

    override fun asMaskingObject(): MapCoreSharedModule.MCMaskingObjectInterfaceProtocol? {
        val result = delegate.asMaskingObject()
        return result.asPlatform()
    }
}

internal fun KMPolygon2dInterface.asPlatform(): MapCoreSharedModule.MCPolygon2dInterfaceProtocol = when (this) {
    is KMPolygon2dInterfacePlatformWrapper -> this.nativeHandle
    else -> KMPolygon2dInterfacePlatformProxy(this)
}
internal fun MapCoreSharedModule.MCPolygon2dInterfaceProtocol.asKmp(): KMPolygon2dInterface = KMPolygon2dInterfacePlatformWrapper(this)
