// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMQuad2dStretchedInstancedInterface", exact = true)
actual interface KMQuad2dStretchedInstancedInterface
{

    actual fun setFrame(frame: KMQuad2dD, origin: KMVec3D, is3d: Boolean)

    actual fun setInstanceCount(count: Int)

    actual fun setPositions(positions: KMSharedBytes)

    actual fun setScales(scales: KMSharedBytes)

    actual fun setRotations(rotations: KMSharedBytes)

    actual fun setAlphas(values: KMSharedBytes)

    actual fun setStretchInfos(values: KMSharedBytes)

    actual fun setTextureCoordinates(textureCoordinates: KMSharedBytes)

    actual fun loadTexture(context: KMRenderingContextInterface, textureHolder: KMTextureHolderInterface)

    actual fun removeTexture()

    actual fun asGraphicsObject(): KMGraphicsObjectInterface

    actual fun asMaskingObject(): KMMaskingObjectInterface
}

private class KMQuad2dStretchedInstancedInterfacePlatformWrapper(internal val nativeHandle: MapCoreSharedModule.MCQuad2dStretchedInstancedInterfaceProtocol) : KMQuad2dStretchedInstancedInterface
{

    override fun setFrame(frame: KMQuad2dD, origin: KMVec3D, is3d: Boolean) {
        nativeHandle.setFrame(frame.asPlatform(), origin.asPlatform(), is3d)
    }

    override fun setInstanceCount(count: Int) {
        nativeHandle.setInstanceCount(count)
    }

    override fun setPositions(positions: KMSharedBytes) {
        nativeHandle.setPositions(positions.asPlatform())
    }

    override fun setScales(scales: KMSharedBytes) {
        nativeHandle.setScales(scales.asPlatform())
    }

    override fun setRotations(rotations: KMSharedBytes) {
        nativeHandle.setRotations(rotations.asPlatform())
    }

    override fun setAlphas(values: KMSharedBytes) {
        nativeHandle.setAlphas(values.asPlatform())
    }

    override fun setStretchInfos(values: KMSharedBytes) {
        nativeHandle.setStretchInfos(values.asPlatform())
    }

    override fun setTextureCoordinates(textureCoordinates: KMSharedBytes) {
        nativeHandle.setTextureCoordinates(textureCoordinates.asPlatform())
    }

    override fun loadTexture(context: KMRenderingContextInterface, textureHolder: KMTextureHolderInterface) {
        nativeHandle.loadTexture(context.asPlatform(), textureHolder.asPlatform())
    }

    override fun removeTexture() {
        nativeHandle.removeTexture()
    }

    override fun asGraphicsObject(): KMGraphicsObjectInterface {
        val result = nativeHandle.asGraphicsObject()
        return (result as MapCoreSharedModule.MCGraphicsObjectInterfaceProtocol).asKmp()
    }

    override fun asMaskingObject(): KMMaskingObjectInterface {
        val result = nativeHandle.asMaskingObject()
        return (result as MapCoreSharedModule.MCMaskingObjectInterfaceProtocol).asKmp()
    }
}

private class KMQuad2dStretchedInstancedInterfacePlatformProxy(private val delegate: KMQuad2dStretchedInstancedInterface) : NSObject(), MapCoreSharedModule.MCQuad2dStretchedInstancedInterfaceProtocol
{

    override fun setFrame(frame: MapCoreSharedModule.MCQuad2dD, origin: MapCoreSharedModule.MCVec3D, is3d: Boolean) {
        delegate.setFrame((frame as MapCoreSharedModule.MCQuad2dD).asKmp(), (origin as MapCoreSharedModule.MCVec3D).asKmp(), is3d)
    }

    override fun setInstanceCount(count: Int) {
        delegate.setInstanceCount(count)
    }

    override fun setPositions(positions: MapCoreSharedModule.MCSharedBytes) {
        delegate.setPositions((positions as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun setScales(scales: MapCoreSharedModule.MCSharedBytes) {
        delegate.setScales((scales as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun setRotations(rotations: MapCoreSharedModule.MCSharedBytes) {
        delegate.setRotations((rotations as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun setAlphas(values: MapCoreSharedModule.MCSharedBytes) {
        delegate.setAlphas((values as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun setStretchInfos(values: MapCoreSharedModule.MCSharedBytes) {
        delegate.setStretchInfos((values as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun setTextureCoordinates(textureCoordinates: MapCoreSharedModule.MCSharedBytes) {
        delegate.setTextureCoordinates((textureCoordinates as MapCoreSharedModule.MCSharedBytes).asKmp())
    }

    override fun loadTexture(context: MapCoreSharedModule.MCRenderingContextInterfaceProtocol?, textureHolder: MapCoreSharedModule.MCTextureHolderInterfaceProtocol?) {
        delegate.loadTexture((context as MapCoreSharedModule.MCRenderingContextInterfaceProtocol).asKmp(), (textureHolder as MapCoreSharedModule.MCTextureHolderInterfaceProtocol).asKmp())
    }

    override fun removeTexture() {
        delegate.removeTexture()
    }

    override fun asGraphicsObject(): MapCoreSharedModule.MCGraphicsObjectInterfaceProtocol? {
        val result = delegate.asGraphicsObject()
        return result.asPlatform()
    }

    override fun asMaskingObject(): MapCoreSharedModule.MCMaskingObjectInterfaceProtocol? {
        val result = delegate.asMaskingObject()
        return result.asPlatform()
    }
}

internal fun KMQuad2dStretchedInstancedInterface.asPlatform(): MapCoreSharedModule.MCQuad2dStretchedInstancedInterfaceProtocol = when (this) {
    is KMQuad2dStretchedInstancedInterfacePlatformWrapper -> this.nativeHandle
    else -> KMQuad2dStretchedInstancedInterfacePlatformProxy(this)
}
public fun MapCoreSharedModule.MCQuad2dStretchedInstancedInterfaceProtocol.asKmp(): KMQuad2dStretchedInstancedInterface = KMQuad2dStretchedInstancedInterfacePlatformWrapper(this)
