// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRasterShaderInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRasterShaderStyle
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCShaderProgramInterfaceProtocol

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRasterShaderInterface", exact = true)
actual class KMRasterShaderInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MCRasterShaderInterfaceProtocol

    actual fun setStyle(style: KMRasterShaderStyle) {
        native.setStyle(style.asPlatform())
    }

    actual fun asShaderProgramInterface(): KMShaderProgramInterface {
        val result = native.asShaderProgramInterface()
        return (result as MCShaderProgramInterfaceProtocol).asKmp()
    }
}

public fun KMRasterShaderInterface.asPlatform(): MCRasterShaderInterfaceProtocol = nativeHandle as MCRasterShaderInterfaceProtocol
public fun MCRasterShaderInterfaceProtocol.asKmp(): KMRasterShaderInterface = KMRasterShaderInterface(this)
