// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRectI", exact = true)
actual class KMRectI actual public constructor(
    x: Int,
    y: Int,
    width: Int,
    height: Int,
) {
    actual val x: Int = x
    actual val y: Int = y
    actual val width: Int = width
    actual val height: Int = height
}

internal fun KMRectI.asPlatform(): MapCoreSharedModule.MCRectI = MapCoreSharedModule.MCRectI(
    x = x,
    y = y,
    width = width,
    height = height,
)
public fun MapCoreSharedModule.MCRectI.asKmp(): KMRectI = KMRectI(
    x = this.x,
    y = this.y,
    width = this.width,
    height = this.height,
)
