// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCColor
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCOpenGlRenderingContextInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRectI
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderTargetInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderingContextInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderingCullMode
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCVec2I
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCVec3D

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRenderingContextInterface", exact = true)
actual interface KMRenderingContextInterface
{

    actual fun onSurfaceCreated()

    actual fun setViewportSize(size: io.openmobilemaps.mapscore.kmp.KMVec2I)

    actual fun getViewportSize(): io.openmobilemaps.mapscore.kmp.KMVec2I

    actual fun setBackgroundColor(color: io.openmobilemaps.mapscore.kmp.KMColor)

    actual fun setCulling(mode: KMRenderingCullMode)

    actual fun setupDrawFrame(vpMatrix: Long, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, screenPixelAsRealMeterFactor: Double)

    actual fun preRenderStencilMask()

    actual fun postRenderStencilMask()

    actual fun clearStencilMask(clearMask: Int)

    actual fun setupStencilWriteMask(writeMask: Int, reference: Int)

    actual fun applyScissorRect(scissorRect: io.openmobilemaps.mapscore.kmp.KMRectI?)

    actual fun getCreateOffscreenRenderTarget(name: String): KMRenderTargetInterface

    actual fun deleteOffscreenRenderTarget(name: String)

    actual fun getOffscreenRenderTargets(): List<KMRenderTargetInterface>

    actual fun asOpenGlRenderingContext(): KMOpenGlRenderingContextInterface?
}

private class KMRenderingContextInterfacePlatformWrapper(internal val nativeHandle: MCRenderingContextInterfaceProtocol) : KMRenderingContextInterface
{

    override fun onSurfaceCreated() {
        nativeHandle.onSurfaceCreated()
    }

    override fun setViewportSize(size: io.openmobilemaps.mapscore.kmp.KMVec2I) {
        nativeHandle.setViewportSize(size.asPlatform())
    }

    override fun getViewportSize(): io.openmobilemaps.mapscore.kmp.KMVec2I {
        val result = nativeHandle.getViewportSize()
        return (result as MCVec2I).asKmp()
    }

    override fun setBackgroundColor(color: io.openmobilemaps.mapscore.kmp.KMColor) {
        nativeHandle.setBackgroundColor(color.asPlatform())
    }

    override fun setCulling(mode: KMRenderingCullMode) {
        nativeHandle.setCulling(mode.asPlatform())
    }

    override fun setupDrawFrame(vpMatrix: Long, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, screenPixelAsRealMeterFactor: Double) {
        nativeHandle.setupDrawFrame(vpMatrix, origin.asPlatform(), screenPixelAsRealMeterFactor)
    }

    override fun preRenderStencilMask() {
        nativeHandle.preRenderStencilMask()
    }

    override fun postRenderStencilMask() {
        nativeHandle.postRenderStencilMask()
    }

    override fun clearStencilMask(clearMask: Int) {
        nativeHandle.clearStencilMask(clearMask)
    }

    override fun setupStencilWriteMask(writeMask: Int, reference: Int) {
        nativeHandle.setupStencilWriteMask(writeMask, reference)
    }

    override fun applyScissorRect(scissorRect: io.openmobilemaps.mapscore.kmp.KMRectI?) {
        nativeHandle.applyScissorRect(scissorRect?.let { it.asPlatform() })
    }

    override fun getCreateOffscreenRenderTarget(name: String): KMRenderTargetInterface {
        val result = nativeHandle.getCreateOffscreenRenderTarget(name)
        return (result as MCRenderTargetInterfaceProtocol).asKmp()
    }

    override fun deleteOffscreenRenderTarget(name: String) {
        nativeHandle.deleteOffscreenRenderTarget(name)
    }

    override fun getOffscreenRenderTargets(): List<KMRenderTargetInterface> {
        val result = nativeHandle.getOffscreenRenderTargets()
        return ArrayList(((result as? List<*>)?.map { (it as MCRenderTargetInterfaceProtocol).asKmp() } ?: (0 until (result as platform.Foundation.NSArray).count.toInt()).map { idx -> ((result as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MCRenderTargetInterfaceProtocol).asKmp() }))
    }

    override fun asOpenGlRenderingContext(): KMOpenGlRenderingContextInterface? {
        val result = nativeHandle.asOpenGlRenderingContext()
        return result?.let { (it as MCOpenGlRenderingContextInterfaceProtocol).asKmp() }
    }
}

private class KMRenderingContextInterfacePlatformProxy(private val delegate: KMRenderingContextInterface) : NSObject(), MCRenderingContextInterfaceProtocol
{

    override fun onSurfaceCreated() {
        delegate.onSurfaceCreated()
    }

    override fun setViewportSize(size: MCVec2I) {
        delegate.setViewportSize((size as MCVec2I).asKmp())
    }

    override fun getViewportSize(): MCVec2I {
        val result = delegate.getViewportSize()
        return result.asPlatform()
    }

    override fun setBackgroundColor(color: MCColor) {
        delegate.setBackgroundColor((color as MCColor).asKmp())
    }

    override fun setCulling(mode: MCRenderingCullMode) {
        delegate.setCulling(KMRenderingCullMode.fromPlatform((mode as MCRenderingCullMode)))
    }

    override fun setupDrawFrame(vpMatrix: Long, origin: MCVec3D, screenPixelAsRealMeterFactor: Double) {
        delegate.setupDrawFrame(vpMatrix, (origin as MCVec3D).asKmp(), screenPixelAsRealMeterFactor)
    }

    override fun preRenderStencilMask() {
        delegate.preRenderStencilMask()
    }

    override fun postRenderStencilMask() {
        delegate.postRenderStencilMask()
    }

    override fun clearStencilMask(clearMask: Int) {
        delegate.clearStencilMask(clearMask)
    }

    override fun setupStencilWriteMask(writeMask: Int, reference: Int) {
        delegate.setupStencilWriteMask(writeMask, reference)
    }

    override fun applyScissorRect(scissorRect: MCRectI?) {
        delegate.applyScissorRect(scissorRect?.let { (it as MCRectI).asKmp() })
    }

    override fun getCreateOffscreenRenderTarget(name: String): MCRenderTargetInterfaceProtocol? {
        val result = delegate.getCreateOffscreenRenderTarget(name)
        return result.asPlatform()
    }

    override fun deleteOffscreenRenderTarget(name: String) {
        delegate.deleteOffscreenRenderTarget(name)
    }

    override fun getOffscreenRenderTargets(): List<*> {
        val result = delegate.getOffscreenRenderTargets()
        return ArrayList(result.map { it.asPlatform() })
    }

    override fun asOpenGlRenderingContext(): MCOpenGlRenderingContextInterfaceProtocol? {
        val result = delegate.asOpenGlRenderingContext()
        return result?.let { it.asPlatform() }
    }
}

public fun KMRenderingContextInterface.asPlatform(): MCRenderingContextInterfaceProtocol = when (this) {
    is KMRenderingContextInterfacePlatformWrapper -> this.nativeHandle
    else -> KMRenderingContextInterfacePlatformProxy(this)
}
public fun MCRenderingContextInterfaceProtocol.asKmp(): KMRenderingContextInterface = KMRenderingContextInterfacePlatformWrapper(this)
