// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderPassConfig
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderTargetInterfaceProtocol

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRenderPassConfig", exact = true)
actual class KMRenderPassConfig actual public constructor(
    renderPassIndex: Int,
    isPassMasked: Boolean,
    renderTarget: KMRenderTargetInterface?,
    stencilReadMask: Int,
    stencilReadReference: Int,
    stencilWriteMask: Int,
    stencilWriteReference: Int,
) {
    actual val renderPassIndex: Int = renderPassIndex
    actual val isPassMasked: Boolean = isPassMasked
    actual val renderTarget: KMRenderTargetInterface? = renderTarget
    actual val stencilReadMask: Int = stencilReadMask
    actual val stencilReadReference: Int = stencilReadReference
    actual val stencilWriteMask: Int = stencilWriteMask
    actual val stencilWriteReference: Int = stencilWriteReference
}

public fun KMRenderPassConfig.asPlatform(): MCRenderPassConfig = MCRenderPassConfig(
    renderPassIndex = renderPassIndex,
    isPassMasked = isPassMasked,
    renderTarget = renderTarget?.let { it.asPlatform() },
    stencilReadMask = stencilReadMask,
    stencilReadReference = stencilReadReference,
    stencilWriteMask = stencilWriteMask,
    stencilWriteReference = stencilWriteReference,
)
public fun MCRenderPassConfig.asKmp(): KMRenderPassConfig = KMRenderPassConfig(
    renderPassIndex = this.renderPassIndex,
    isPassMasked = this.isPassMasked,
    renderTarget = this.renderTarget?.let { (it as MCRenderTargetInterfaceProtocol).asKmp() },
    stencilReadMask = this.stencilReadMask,
    stencilReadReference = this.stencilReadReference,
    stencilWriteMask = this.stencilWriteMask,
    stencilWriteReference = this.stencilWriteReference,
)
