// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderingCullMode

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRenderingCullMode", exact = true)
actual enum class KMRenderingCullMode(internal val platformValue: Long) {
    FRONT(0L),
    BACK(1L),
    NONE(2L),
    ;

    companion object {
        public fun fromPlatform(value: MCRenderingCullMode): KMRenderingCullMode {
            val raw: Long = value
            return when (raw) {
                0L -> KMRenderingCullMode.FRONT
                1L -> KMRenderingCullMode.BACK
                2L -> KMRenderingCullMode.NONE
                else -> throw IllegalArgumentException("Unknown KMRenderingCullMode value: " + raw)
            }
        }
    }
}

public fun KMRenderingCullMode.asPlatform(): MCRenderingCullMode = platformValue
