// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRectD

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMRectD", exact = true)
actual class KMRectD actual public constructor(
    x: Double,
    y: Double,
    width: Double,
    height: Double,
) {
    actual val x: Double = x
    actual val y: Double = y
    actual val width: Double = width
    actual val height: Double = height
}

public fun KMRectD.asPlatform(): MCRectD = MCRectD(
    x = x,
    y = y,
    width = width,
    height = height,
)
public fun MCRectD.asKmp(): KMRectD = KMRectD(
    x = this.x,
    y = this.y,
    width = this.width,
    height = this.height,
)
