// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCSceneCallbackInterfaceProtocol

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMSceneCallbackInterface", exact = true)
actual interface KMSceneCallbackInterface
{

    actual fun invalidate()
}

private class KMSceneCallbackInterfacePlatformWrapper(internal val nativeHandle: MCSceneCallbackInterfaceProtocol) : KMSceneCallbackInterface
{

    override fun invalidate() {
        nativeHandle.invalidate()
    }
}

private class KMSceneCallbackInterfacePlatformProxy(private val delegate: KMSceneCallbackInterface) : NSObject(), MCSceneCallbackInterfaceProtocol
{

    override fun invalidate() {
        delegate.invalidate()
    }
}

public fun KMSceneCallbackInterface.asPlatform(): MCSceneCallbackInterfaceProtocol = when (this) {
    is KMSceneCallbackInterfacePlatformWrapper -> this.nativeHandle
    else -> KMSceneCallbackInterfacePlatformProxy(this)
}
public fun MCSceneCallbackInterfaceProtocol.asKmp(): KMSceneCallbackInterface = KMSceneCallbackInterfacePlatformWrapper(this)
