// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCFontData
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCGraphicsObjectInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCQuad2dD
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCRenderingContextInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCSharedBytes
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTextInstancedInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTextureHolderInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCVec3D

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTextInstancedInterface", exact = true)
actual interface KMTextInstancedInterface
{

    actual fun setFrame(frame: io.openmobilemaps.mapscore.kmp.KMQuad2dD, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, is3d: Boolean)

    actual fun setInstanceCount(count: Int)

    actual fun setPositions(positions: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setReferencePositions(positions: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setTextureCoordinates(textureCoordinates: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setScales(scales: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setRotations(rotations: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setAlphas(alphas: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setStyleIndices(indices: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun setStyles(values: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    actual fun loadFont(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, fontData: io.openmobilemaps.mapscore.kmp.KMFontData, fontMsdfTexture: KMTextureHolderInterface)

    actual fun removeTexture()

    actual fun asGraphicsObject(): KMGraphicsObjectInterface
}

private class KMTextInstancedInterfacePlatformWrapper(internal val nativeHandle: MCTextInstancedInterfaceProtocol) : KMTextInstancedInterface
{

    override fun setFrame(frame: io.openmobilemaps.mapscore.kmp.KMQuad2dD, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, is3d: Boolean) {
        nativeHandle.setFrame(frame.asPlatform(), origin.asPlatform(), is3d)
    }

    override fun setInstanceCount(count: Int) {
        nativeHandle.setInstanceCount(count)
    }

    override fun setPositions(positions: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setPositions(positions.asPlatform())
    }

    override fun setReferencePositions(positions: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setReferencePositions(positions.asPlatform())
    }

    override fun setTextureCoordinates(textureCoordinates: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setTextureCoordinates(textureCoordinates.asPlatform())
    }

    override fun setScales(scales: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setScales(scales.asPlatform())
    }

    override fun setRotations(rotations: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setRotations(rotations.asPlatform())
    }

    override fun setAlphas(alphas: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setAlphas(alphas.asPlatform())
    }

    override fun setStyleIndices(indices: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setStyleIndices(indices.asPlatform())
    }

    override fun setStyles(values: io.openmobilemaps.mapscore.kmp.KMSharedBytes) {
        nativeHandle.setStyles(values.asPlatform())
    }

    override fun loadFont(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, fontData: io.openmobilemaps.mapscore.kmp.KMFontData, fontMsdfTexture: KMTextureHolderInterface) {
        nativeHandle.loadFont(context.asPlatform(), fontData.asPlatform(), fontMsdfTexture.asPlatform())
    }

    override fun removeTexture() {
        nativeHandle.removeTexture()
    }

    override fun asGraphicsObject(): KMGraphicsObjectInterface {
        val result = nativeHandle.asGraphicsObject()
        return (result as MCGraphicsObjectInterfaceProtocol).asKmp()
    }
}

private class KMTextInstancedInterfacePlatformProxy(private val delegate: KMTextInstancedInterface) : NSObject(), MCTextInstancedInterfaceProtocol
{

    override fun setFrame(frame: MCQuad2dD, origin: MCVec3D, is3d: Boolean) {
        delegate.setFrame((frame as MCQuad2dD).asKmp(), (origin as MCVec3D).asKmp(), is3d)
    }

    override fun setInstanceCount(count: Int) {
        delegate.setInstanceCount(count)
    }

    override fun setPositions(positions: MCSharedBytes) {
        delegate.setPositions((positions as MCSharedBytes).asKmp())
    }

    override fun setReferencePositions(positions: MCSharedBytes) {
        delegate.setReferencePositions((positions as MCSharedBytes).asKmp())
    }

    override fun setTextureCoordinates(textureCoordinates: MCSharedBytes) {
        delegate.setTextureCoordinates((textureCoordinates as MCSharedBytes).asKmp())
    }

    override fun setScales(scales: MCSharedBytes) {
        delegate.setScales((scales as MCSharedBytes).asKmp())
    }

    override fun setRotations(rotations: MCSharedBytes) {
        delegate.setRotations((rotations as MCSharedBytes).asKmp())
    }

    override fun setAlphas(alphas: MCSharedBytes) {
        delegate.setAlphas((alphas as MCSharedBytes).asKmp())
    }

    override fun setStyleIndices(indices: MCSharedBytes) {
        delegate.setStyleIndices((indices as MCSharedBytes).asKmp())
    }

    override fun setStyles(values: MCSharedBytes) {
        delegate.setStyles((values as MCSharedBytes).asKmp())
    }

    override fun loadFont(context: MCRenderingContextInterfaceProtocol?, fontData: MCFontData, fontMsdfTexture: MCTextureHolderInterfaceProtocol?) {
        delegate.loadFont((context as MCRenderingContextInterfaceProtocol).asKmp(), (fontData as MCFontData).asKmp(), (fontMsdfTexture as MCTextureHolderInterfaceProtocol).asKmp())
    }

    override fun removeTexture() {
        delegate.removeTexture()
    }

    override fun asGraphicsObject(): MCGraphicsObjectInterfaceProtocol? {
        val result = delegate.asGraphicsObject()
        return result.asPlatform()
    }
}

public fun KMTextInstancedInterface.asPlatform(): MCTextInstancedInterfaceProtocol = when (this) {
    is KMTextInstancedInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTextInstancedInterfacePlatformProxy(this)
}
public fun MCTextInstancedInterfaceProtocol.asKmp(): KMTextInstancedInterface = KMTextInstancedInterfacePlatformWrapper(this)
