// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCAnchor
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCCoord
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCFont
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCFormattedStringEntry
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTextFactory
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTextInfoInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTextJustify

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTextFactory", exact = true)
actual class KMTextFactory actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MCTextFactory

    actual companion object
    {

        actual fun createText(text: List<KMFormattedStringEntry>, coordinate: io.openmobilemaps.mapscore.kmp.KMCoord, font: io.openmobilemaps.mapscore.kmp.KMFont, textAnchor: KMAnchor, textJustify: KMTextJustify): KMTextInfoInterface {
            val result = MCTextFactory.createText(ArrayList(text.map { it.asPlatform() }), coordinate.asPlatform(), font.asPlatform(), textAnchor.asPlatform(), textJustify.asPlatform())
            return (result as MCTextInfoInterfaceProtocol).asKmp()
        }
    }
}

public fun KMTextFactory.asPlatform(): MCTextFactory = nativeHandle as MCTextFactory
public fun MCTextFactory.asKmp(): KMTextFactory = KMTextFactory(this)
