// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTiled2dMapVectorLayerInterface", exact = true)
actual class KMTiled2dMapVectorLayerInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MapCoreSharedModule.MCTiled2dMapVectorLayerInterface

    actual fun setSelectionDelegate(selectionDelegate: KMTiled2dMapVectorLayerSelectionCallbackInterface?) {
        native.setSelectionDelegate(selectionDelegate?.let { it.asPlatform() })
    }

    actual fun asLayerInterface(): KMLayerInterface {
        val result = native.asLayerInterface()
        return (result as MapCoreSharedModule.MCLayerInterfaceProtocol).asKmp()
    }

    actual fun setMinZoomLevelIdentifier(value: Int?) {
        native.setMinZoomLevelIdentifier(value?.let { platform.Foundation.NSNumber(int = it) })
    }

    actual fun getMinZoomLevelIdentifier(): Int? {
        val result = native.getMinZoomLevelIdentifier()
        return result?.let { (it as platform.Foundation.NSNumber).intValue }
    }

    actual fun setMaxZoomLevelIdentifier(value: Int?) {
        native.setMaxZoomLevelIdentifier(value?.let { platform.Foundation.NSNumber(int = it) })
    }

    actual fun getMaxZoomLevelIdentifier(): Int? {
        val result = native.getMaxZoomLevelIdentifier()
        return result?.let { (it as platform.Foundation.NSNumber).intValue }
    }

    actual fun getStyleMetadataJson(): String? {
        val result = native.getStyleMetadataJson()
        return result?.let { (it as String) }
    }

    actual fun setFeatureState(identifier: String, properties: HashMap<String, KMVectorLayerFeatureInfoValue>) {
        native.setFeatureState(identifier, HashMap(properties.map { it.key to it.value.asPlatform() }.toMap()))
    }

    actual fun setGlobalState(properties: HashMap<String, KMVectorLayerFeatureInfoValue>) {
        native.setGlobalState(HashMap(properties.map { it.key to it.value.asPlatform() }.toMap()))
    }

    actual fun getVisiblePointFeatureContexts(paddingPc: Float, sourceLayer: String?): ArrayList<KMVectorLayerFeatureCoordInfo> {
        val result = native.getVisiblePointFeatureContexts(paddingPc, sourceLayer?.let { it })
        return ArrayList(((result as? List<*>)?.map { (it as MapCoreSharedModule.MCVectorLayerFeatureCoordInfo).asKmp() } ?: (0 until (result as platform.Foundation.NSArray).count.toInt()).map { idx -> ((result as platform.Foundation.NSArray).objectAtIndex(idx.toULong()) as MapCoreSharedModule.MCVectorLayerFeatureCoordInfo).asKmp() }))
    }

    actual fun setReadyStateListener(listener: KMTiled2dMapReadyStateListener?) {
        native.setReadyStateListener(listener?.let { it.asPlatform() })
    }

    actual fun reloadDataSource(sourceName: String) {
        native.reloadDataSource(sourceName)
    }

    actual fun reloadLocalDataSource(sourceName: String, geoJson: String) {
        native.reloadLocalDataSource(sourceName, geoJson)
    }

    actual fun performClick(coord: KMCoord) {
        native.performClick(coord.asPlatform())
    }

    actual companion object
    {

        actual fun createFromStyleJson(layerName: String, styleJsonUrl: String, loaders: ArrayList<KMLoaderInterface>, fontLoader: KMFontLoaderInterface): KMTiled2dMapVectorLayerInterface {
            val result = MapCoreSharedModule.MCTiled2dMapVectorLayerInterface.createFromStyleJson(layerName, styleJsonUrl, ArrayList(loaders.map { it.asPlatform() }), fontLoader.asPlatform())
            return (result as MapCoreSharedModule.MCTiled2dMapVectorLayerInterface).asKmp()
        }

        actual fun createExplicitly(layerName: String, styleJson: String?, localStyleJson: Boolean?, loaders: ArrayList<KMLoaderInterface>, fontLoader: KMFontLoaderInterface, localDataProvider: KMTiled2dMapVectorLayerLocalDataProviderInterface?, customZoomInfo: KMTiled2dMapZoomInfo?, symbolDelegate: KMTiled2dMapVectorLayerSymbolDelegateInterface?, sourceUrlParams: HashMap<String, String>?): KMTiled2dMapVectorLayerInterface {
            val result = MapCoreSharedModule.MCTiled2dMapVectorLayerInterface.createExplicitly(layerName, styleJson?.let { it }, localStyleJson?.let { platform.Foundation.NSNumber(bool = it) }, ArrayList(loaders.map { it.asPlatform() }), fontLoader.asPlatform(), localDataProvider?.let { it.asPlatform() }, customZoomInfo?.let { it.asPlatform() }, symbolDelegate?.let { it.asPlatform() }, sourceUrlParams?.let { HashMap(it.map { it.key to it.value }.toMap()) })
            return (result as MapCoreSharedModule.MCTiled2dMapVectorLayerInterface).asKmp()
        }
    }
}

internal fun KMTiled2dMapVectorLayerInterface.asPlatform(): MapCoreSharedModule.MCTiled2dMapVectorLayerInterface = nativeHandle as MapCoreSharedModule.MCTiled2dMapVectorLayerInterface
internal fun MapCoreSharedModule.MCTiled2dMapVectorLayerInterface.asKmp(): KMTiled2dMapVectorLayerInterface = KMTiled2dMapVectorLayerInterface(this)
