// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from touch_handler.djinni

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)
@file:Suppress("RedundantCast", "RedundantCallOfConversionMethod", "UNCHECKED_CAST", "USELESS_CAST")

package io.openmobilemaps.mapscore.kmp

import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTouchEvent
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTouchHandlerInterfaceProtocol
import swiftPMImport.io.openmobilemaps.mapscore.kmp.MCTouchInterfaceProtocol

import kotlin.experimental.ExperimentalObjCName
import kotlin.native.ObjCName
import platform.darwin.NSObject

@OptIn(ExperimentalObjCName::class)
@ObjCName("KMTouchHandlerInterface", exact = true)
actual interface KMTouchHandlerInterface
{

    actual fun onTouchEvent(touchEvent: KMTouchEvent)

    actual fun insertListener(listener: KMTouchInterface, index: Int)

    actual fun addListener(listener: KMTouchInterface)

    actual fun removeListener(listener: KMTouchInterface)
}

private class KMTouchHandlerInterfacePlatformWrapper(internal val nativeHandle: MCTouchHandlerInterfaceProtocol) : KMTouchHandlerInterface
{

    override fun onTouchEvent(touchEvent: KMTouchEvent) {
        nativeHandle.onTouchEvent(touchEvent.asPlatform())
    }

    override fun insertListener(listener: KMTouchInterface, index: Int) {
        nativeHandle.insertListener(listener.asPlatform(), index)
    }

    override fun addListener(listener: KMTouchInterface) {
        nativeHandle.addListener(listener.asPlatform())
    }

    override fun removeListener(listener: KMTouchInterface) {
        nativeHandle.removeListener(listener.asPlatform())
    }
}

private class KMTouchHandlerInterfacePlatformProxy(private val delegate: KMTouchHandlerInterface) : NSObject(), MCTouchHandlerInterfaceProtocol
{

    override fun onTouchEvent(touchEvent: MCTouchEvent) {
        delegate.onTouchEvent((touchEvent as MCTouchEvent).asKmp())
    }

    override fun insertListener(listener: MCTouchInterfaceProtocol?, index: Int) {
        delegate.insertListener((listener as MCTouchInterfaceProtocol).asKmp(), index)
    }

    override fun addListener(listener: MCTouchInterfaceProtocol?) {
        delegate.addListener((listener as MCTouchInterfaceProtocol).asKmp())
    }

    override fun removeListener(listener: MCTouchInterfaceProtocol?) {
        delegate.removeListener((listener as MCTouchInterfaceProtocol).asKmp())
    }
}

public fun KMTouchHandlerInterface.asPlatform(): MCTouchHandlerInterfaceProtocol = when (this) {
    is KMTouchHandlerInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTouchHandlerInterfacePlatformProxy(this)
}
public fun MCTouchHandlerInterfaceProtocol.asKmp(): KMTouchHandlerInterface = KMTouchHandlerInterfacePlatformWrapper(this)
