// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMCoordinateConversionHelperInterface actual constructor(
    internal val nativeHandle: Any,
) {
    private val native = nativeHandle as io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface

    actual fun registerConverter(converter: KMCoordinateConverterInterface) {
        native.registerConverter(converter.asPlatform())
    }

    actual fun convert(to: Int, coordinate: KMCoord): KMCoord {
        val result = native.convert(to, coordinate.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp()
    }

    actual fun convertRect(to: Int, rect: KMRectCoord): KMRectCoord {
        val result = native.convertRect(to, rect.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp()
    }

    actual fun convertRectToRenderSystem(rect: KMRectCoord): KMRectCoord {
        val result = native.convertRectToRenderSystem(rect.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp()
    }

    actual fun convertQuad(to: Int, quad: KMQuadCoord): KMQuadCoord {
        val result = native.convertQuad(to, quad.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.QuadCoord).asKmp()
    }

    actual fun convertQuadToRenderSystem(quad: KMQuadCoord): KMQuadCoord {
        val result = native.convertQuadToRenderSystem(quad.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.QuadCoord).asKmp()
    }

    actual fun convertToRenderSystem(coordinate: KMCoord): KMCoord {
        val result = native.convertToRenderSystem(coordinate.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp()
    }

    actual companion object
    {

        actual fun independentInstance(): KMCoordinateConversionHelperInterface {
            val result = io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface.independentInstance()
            return requireNotNull((result as io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface)).asKmp()
        }
    }
}

internal fun KMCoordinateConversionHelperInterface.asPlatform(): io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface = nativeHandle as io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface
internal fun io.openmobilemaps.mapscore.shared.map.coordinates.CoordinateConversionHelperInterface.asKmp(): KMCoordinateConversionHelperInterface = KMCoordinateConversionHelperInterface(this)
