// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

actual typealias KMLayerReadyState = io.openmobilemaps.mapscore.shared.map.LayerReadyState

internal fun KMLayerReadyState.asPlatform(): io.openmobilemaps.mapscore.shared.map.LayerReadyState = this
internal fun io.openmobilemaps.mapscore.shared.map.LayerReadyState.asKmp(): KMLayerReadyState = this
