// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from task_scheduler.djinni

package io.openmobilemaps.mapscore.kmp

actual interface KMTaskInterface
{

    actual fun getConfig(): KMTaskConfig

    actual fun run()
}

private class KMTaskInterfacePlatformWrapper(internal val nativeHandle: io.openmobilemaps.mapscore.shared.map.scheduling.TaskInterface) : KMTaskInterface
{

    override fun getConfig(): KMTaskConfig {
        val result = nativeHandle.getConfig()
        return (result as io.openmobilemaps.mapscore.shared.map.scheduling.TaskConfig).asKmp()
    }

    override fun run() {
        nativeHandle.run()
    }
}

private class KMTaskInterfacePlatformProxy(private val delegate: KMTaskInterface) : io.openmobilemaps.mapscore.shared.map.scheduling.TaskInterface()
{

    override fun getConfig(): io.openmobilemaps.mapscore.shared.map.scheduling.TaskConfig {
        val result = delegate.getConfig()
        return result.asPlatform()
    }

    override fun run() {
        delegate.run()
    }
}

internal fun KMTaskInterface.asPlatform(): io.openmobilemaps.mapscore.shared.map.scheduling.TaskInterface = when (this) {
    is KMTaskInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTaskInterfacePlatformProxy(this)
}
internal fun io.openmobilemaps.mapscore.shared.map.scheduling.TaskInterface.asKmp(): KMTaskInterface = KMTaskInterfacePlatformWrapper(this)
