// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from textured_polygon_layer.djinni

import type { TextureHolderInterface } from "@djinni/maps-core/graphics/objects/graphicsobjects"
import type { PolygonCoord, RectCoord } from "@djinni/maps-core/map/coordinates/coordinate_system"
import type { LayerInterface } from "@djinni/maps-core/map/core"

export interface TexturedPolygonLayerInterface {
    /**
     * The polygon's coordinates are mapped to texture UV by their position within textureBounds:
     * textureBounds.top_left -> (0,0), textureBounds.bottom_right -> (1,1).
     */
    setPolygon(polygon: PolygonCoord, textureBounds: RectCoord): void;
    loadTexture(texture: TextureHolderInterface): void;
    setAlpha(alpha: number): void;
    setRenderPassIndex(index: number): void;
    asLayerInterface(): LayerInterface;
}
export interface TexturedPolygonLayerInterface_statics {
    create(): TexturedPolygonLayerInterface;
}

export interface TexturedPolygonLayer_statics {
    TexturedPolygonLayerInterface: TexturedPolygonLayerInterface_statics;
}
