// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from styling.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMColorStateList actual public constructor(
    normal: io.openmobilemaps.mapscore.kmp.KMColor,
    highlighted: io.openmobilemaps.mapscore.kmp.KMColor,
) {
    actual val normal: io.openmobilemaps.mapscore.kmp.KMColor = normal
    actual val highlighted: io.openmobilemaps.mapscore.kmp.KMColor = highlighted
}

public fun KMColorStateList.asPlatform(): io.openmobilemaps.mapscore.shared.map.layers.ColorStateList = io.openmobilemaps.mapscore.shared.map.layers.ColorStateList(
    normal = normal.asPlatform(),
    highlighted = highlighted.asPlatform(),
)
public fun io.openmobilemaps.mapscore.shared.map.layers.ColorStateList.asKmp(): KMColorStateList = KMColorStateList(
    normal = (this.normal as io.openmobilemaps.mapscore.shared.graphics.common.Color).asKmp(),
    highlighted = (this.highlighted as io.openmobilemaps.mapscore.shared.graphics.common.Color).asKmp(),
)
