// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from geo_json_parser.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMGeoJsonPoint actual public constructor(
    point: io.openmobilemaps.mapscore.kmp.KMCoord,
    featureInfo: io.openmobilemaps.mapscore.kmp.KMVectorLayerFeatureInfo,
) {
    actual val point: io.openmobilemaps.mapscore.kmp.KMCoord = point
    actual val featureInfo: io.openmobilemaps.mapscore.kmp.KMVectorLayerFeatureInfo = featureInfo
}

public fun KMGeoJsonPoint.asPlatform(): io.openmobilemaps.mapscore.shared.map.layers.tiled.GeoJsonPoint = io.openmobilemaps.mapscore.shared.map.layers.tiled.GeoJsonPoint(
    point = point.asPlatform(),
    featureInfo = featureInfo.asPlatform(),
)
public fun io.openmobilemaps.mapscore.shared.map.layers.tiled.GeoJsonPoint.asKmp(): KMGeoJsonPoint = KMGeoJsonPoint(
    point = (this.point as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp(),
    featureInfo = (this.featureInfo as io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.VectorLayerFeatureInfo).asKmp(),
)
