// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectFactoryInterface

actual interface KMGraphicsObjectFactoryInterface
{

    actual fun createQuad(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInterface

    actual fun createTexturedPolygon(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTexturedPolygonInterface

    actual fun createQuadTessellated(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInterface

    actual fun createQuadTessellatedDisplaced(): KMQuad2dInterface

    actual fun createPolygon(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygon2dInterface

    actual fun createPolygonTessellated(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygon2dInterface

    actual fun createIcosahedronObject(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMIcosahedronInterface

    actual fun createQuadInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInstancedInterface

    actual fun createQuadStretchedInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dStretchedInstancedInterface

    actual fun createLineGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMLineGroup2dInterface

    actual fun createPolygonGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygonGroup2dInterface

    actual fun createPolygonPatternGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygonPatternGroup2dInterface

    actual fun createQuadMask(is3d: Boolean): KMQuad2dInterface

    actual fun createPolygonMask(is3d: Boolean): KMPolygon2dInterface

    actual fun createPolygonMaskTessellated(is3d: Boolean): KMPolygon2dInterface

    actual fun createText(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTextInterface

    actual fun createTextInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTextInstancedInterface
}

private class KMGraphicsObjectFactoryInterfacePlatformWrapper(internal val nativeHandle: GraphicsObjectFactoryInterface) : KMGraphicsObjectFactoryInterface
{

    override fun createQuad(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInterface {
        val result = nativeHandle.createQuad(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface).asKmp()
    }

    override fun createTexturedPolygon(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTexturedPolygonInterface {
        val result = nativeHandle.createTexturedPolygon(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.TexturedPolygonInterface).asKmp()
    }

    override fun createQuadTessellated(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInterface {
        val result = nativeHandle.createQuadTessellated(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface).asKmp()
    }

    override fun createQuadTessellatedDisplaced(): KMQuad2dInterface {
        val result = nativeHandle.createQuadTessellatedDisplaced()
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface).asKmp()
    }

    override fun createPolygon(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygon2dInterface {
        val result = nativeHandle.createPolygon(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface).asKmp()
    }

    override fun createPolygonTessellated(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygon2dInterface {
        val result = nativeHandle.createPolygonTessellated(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface).asKmp()
    }

    override fun createIcosahedronObject(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMIcosahedronInterface {
        val result = nativeHandle.createIcosahedronObject(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.IcosahedronInterface).asKmp()
    }

    override fun createQuadInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dInstancedInterface {
        val result = nativeHandle.createQuadInstanced(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInstancedInterface).asKmp()
    }

    override fun createQuadStretchedInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMQuad2dStretchedInstancedInterface {
        val result = nativeHandle.createQuadStretchedInstanced(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dStretchedInstancedInterface).asKmp()
    }

    override fun createLineGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMLineGroup2dInterface {
        val result = nativeHandle.createLineGroup(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.LineGroup2dInterface).asKmp()
    }

    override fun createPolygonGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygonGroup2dInterface {
        val result = nativeHandle.createPolygonGroup(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.PolygonGroup2dInterface).asKmp()
    }

    override fun createPolygonPatternGroup(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMPolygonPatternGroup2dInterface {
        val result = nativeHandle.createPolygonPatternGroup(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.PolygonPatternGroup2dInterface).asKmp()
    }

    override fun createQuadMask(is3d: Boolean): KMQuad2dInterface {
        val result = nativeHandle.createQuadMask(is3d)
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface).asKmp()
    }

    override fun createPolygonMask(is3d: Boolean): KMPolygon2dInterface {
        val result = nativeHandle.createPolygonMask(is3d)
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface).asKmp()
    }

    override fun createPolygonMaskTessellated(is3d: Boolean): KMPolygon2dInterface {
        val result = nativeHandle.createPolygonMaskTessellated(is3d)
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface).asKmp()
    }

    override fun createText(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTextInterface {
        val result = nativeHandle.createText(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.TextInterface).asKmp()
    }

    override fun createTextInstanced(shader: io.openmobilemaps.mapscore.kmp.KMShaderProgramInterface): KMTextInstancedInterface {
        val result = nativeHandle.createTextInstanced(shader.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.TextInstancedInterface).asKmp()
    }
}

private class KMGraphicsObjectFactoryInterfacePlatformProxy(private val delegate: KMGraphicsObjectFactoryInterface) : GraphicsObjectFactoryInterface()
{

    override fun createQuad(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface {
        val result = delegate.createQuad((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createTexturedPolygon(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.TexturedPolygonInterface {
        val result = delegate.createTexturedPolygon((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createQuadTessellated(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface {
        val result = delegate.createQuadTessellated((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createQuadTessellatedDisplaced(): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface {
        val result = delegate.createQuadTessellatedDisplaced()
        return result.asPlatform()
    }

    override fun createPolygon(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface {
        val result = delegate.createPolygon((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createPolygonTessellated(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface {
        val result = delegate.createPolygonTessellated((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createIcosahedronObject(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.IcosahedronInterface {
        val result = delegate.createIcosahedronObject((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createQuadInstanced(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInstancedInterface {
        val result = delegate.createQuadInstanced((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createQuadStretchedInstanced(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dStretchedInstancedInterface {
        val result = delegate.createQuadStretchedInstanced((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createLineGroup(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.LineGroup2dInterface {
        val result = delegate.createLineGroup((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createPolygonGroup(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.PolygonGroup2dInterface {
        val result = delegate.createPolygonGroup((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createPolygonPatternGroup(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.PolygonPatternGroup2dInterface {
        val result = delegate.createPolygonPatternGroup((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createQuadMask(is3d: Boolean): io.openmobilemaps.mapscore.shared.graphics.objects.Quad2dInterface {
        val result = delegate.createQuadMask(is3d)
        return result.asPlatform()
    }

    override fun createPolygonMask(is3d: Boolean): io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface {
        val result = delegate.createPolygonMask(is3d)
        return result.asPlatform()
    }

    override fun createPolygonMaskTessellated(is3d: Boolean): io.openmobilemaps.mapscore.shared.graphics.objects.Polygon2dInterface {
        val result = delegate.createPolygonMaskTessellated(is3d)
        return result.asPlatform()
    }

    override fun createText(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.TextInterface {
        val result = delegate.createText((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }

    override fun createTextInstanced(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): io.openmobilemaps.mapscore.shared.graphics.objects.TextInstancedInterface {
        val result = delegate.createTextInstanced((shader as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface).asKmp())
        return result.asPlatform()
    }
}

public fun KMGraphicsObjectFactoryInterface.asPlatform(): GraphicsObjectFactoryInterface = when (this) {
    is KMGraphicsObjectFactoryInterfacePlatformWrapper -> this.nativeHandle
    else -> KMGraphicsObjectFactoryInterfacePlatformProxy(this)
}
public fun GraphicsObjectFactoryInterface.asKmp(): KMGraphicsObjectFactoryInterface = KMGraphicsObjectFactoryInterfacePlatformWrapper(this)
