// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

actual typealias KMMapCamera3dMode = io.openmobilemaps.mapscore.shared.map.MapCamera3dMode

public fun KMMapCamera3dMode.asPlatform(): io.openmobilemaps.mapscore.shared.map.MapCamera3dMode = this
public fun io.openmobilemaps.mapscore.shared.map.MapCamera3dMode.asKmp(): KMMapCamera3dMode = this
