// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMMapCoordinateSystem actual public constructor(
    identifier: Int,
    bounds: KMRectCoord,
    unitToScreenMeterFactor: Float,
) {
    actual val identifier: Int = identifier
    actual val bounds: KMRectCoord = bounds
    actual val unitToScreenMeterFactor: Float = unitToScreenMeterFactor
}

public fun KMMapCoordinateSystem.asPlatform(): io.openmobilemaps.mapscore.shared.map.coordinates.MapCoordinateSystem = io.openmobilemaps.mapscore.shared.map.coordinates.MapCoordinateSystem(
    identifier = identifier,
    bounds = bounds.asPlatform(),
    unitToScreenMeterFactor = unitToScreenMeterFactor,
)
public fun io.openmobilemaps.mapscore.shared.map.coordinates.MapCoordinateSystem.asKmp(): KMMapCoordinateSystem = KMMapCoordinateSystem(
    identifier = this.identifier,
    bounds = (this.bounds as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp(),
    unitToScreenMeterFactor = this.unitToScreenMeterFactor,
)
