// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.map.MapCameraInterface

actual class KMMapCameraInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as MapCameraInterface

    actual fun freeze(freeze: Boolean) {
        native.freeze(freeze)
    }

    actual fun moveToCenterPositionZoom(centerPosition: io.openmobilemaps.mapscore.kmp.KMCoord, zoom: Double, animated: Boolean) {
        native.moveToCenterPositionZoom(centerPosition.asPlatform(), zoom, animated)
    }

    actual fun moveToCenterPosition(centerPosition: io.openmobilemaps.mapscore.kmp.KMCoord, animated: Boolean) {
        native.moveToCenterPosition(centerPosition.asPlatform(), animated)
    }

    actual fun moveToBoundingBox(boundingBox: io.openmobilemaps.mapscore.kmp.KMRectCoord, paddingPc: Float, animated: Boolean, minZoom: Double?, maxZoom: Double?) {
        native.moveToBoundingBox(boundingBox.asPlatform(), paddingPc, animated, minZoom?.let { it }, maxZoom?.let { it })
    }

    actual fun getCenterPosition(): io.openmobilemaps.mapscore.kmp.KMCoord {
        val result = native.getCenterPosition()
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp()
    }

    actual fun setZoom(zoom: Double, animated: Boolean) {
        native.setZoom(zoom, animated)
    }

    actual fun getZoom(): Double {
        val result = native.getZoom()
        return result
    }

    actual fun setRotation(angle: Float, animated: Boolean) {
        native.setRotation(angle, animated)
    }

    actual fun getRotation(): Float {
        val result = native.getRotation()
        return result
    }

    actual fun setMinZoom(minZoom: Double) {
        native.setMinZoom(minZoom)
    }

    actual fun setMaxZoom(maxZoom: Double) {
        native.setMaxZoom(maxZoom)
    }

    actual fun getMinZoom(): Double {
        val result = native.getMinZoom()
        return result
    }

    actual fun getMaxZoom(): Double {
        val result = native.getMaxZoom()
        return result
    }

    actual fun setBounds(bounds: io.openmobilemaps.mapscore.kmp.KMRectCoord) {
        native.setBounds(bounds.asPlatform())
    }

    actual fun getBounds(): io.openmobilemaps.mapscore.kmp.KMRectCoord {
        val result = native.getBounds()
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp()
    }

    actual fun isInBounds(coords: io.openmobilemaps.mapscore.kmp.KMCoord): Boolean {
        val result = native.isInBounds(coords.asPlatform())
        return result
    }

    actual fun setPaddingLeft(padding: Float) {
        native.setPaddingLeft(padding)
    }

    actual fun setPaddingRight(padding: Float) {
        native.setPaddingRight(padding)
    }

    actual fun setPaddingTop(padding: Float) {
        native.setPaddingTop(padding)
    }

    actual fun setPaddingBottom(padding: Float) {
        native.setPaddingBottom(padding)
    }

    actual fun getVisibleRect(): io.openmobilemaps.mapscore.kmp.KMRectCoord {
        val result = native.getVisibleRect()
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp()
    }

    actual fun getPaddingAdjustedVisibleRect(): io.openmobilemaps.mapscore.kmp.KMRectCoord {
        val result = native.getPaddingAdjustedVisibleRect()
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp()
    }

    actual fun getScreenDensityPpi(): Float {
        val result = native.getScreenDensityPpi()
        return result
    }

    actual fun update() {
        native.update()
    }

    actual fun getInvariantModelMatrix(coordinate: io.openmobilemaps.mapscore.kmp.KMCoord, scaleInvariant: Boolean, rotationInvariant: Boolean): List<Float> {
        val result = native.getInvariantModelMatrix(coordinate.asPlatform(), scaleInvariant, rotationInvariant)
        return ArrayList(result.map { it })
    }

    actual fun addListener(listener: io.openmobilemaps.mapscore.kmp.KMMapCameraListenerInterface) {
        native.addListener(listener.asPlatform())
    }

    actual fun removeListener(listener: io.openmobilemaps.mapscore.kmp.KMMapCameraListenerInterface) {
        native.removeListener(listener.asPlatform())
    }

    actual fun notifyListenerBoundsChange() {
        native.notifyListenerBoundsChange()
    }

    actual fun coordFromScreenPosition(posScreen: io.openmobilemaps.mapscore.kmp.KMVec2F): io.openmobilemaps.mapscore.kmp.KMCoord {
        val result = native.coordFromScreenPosition(posScreen.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp()
    }

    actual fun coordFromScreenPositionZoom(posScreen: io.openmobilemaps.mapscore.kmp.KMVec2F, zoom: Float): io.openmobilemaps.mapscore.kmp.KMCoord {
        val result = native.coordFromScreenPositionZoom(posScreen.asPlatform(), zoom)
        return (result as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp()
    }

    actual fun screenPosFromCoord(coord: io.openmobilemaps.mapscore.kmp.KMCoord): io.openmobilemaps.mapscore.kmp.KMVec2F {
        val result = native.screenPosFromCoord(coord.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.graphics.common.Vec2F).asKmp()
    }

    actual fun screenPosFromCoordZoom(coord: io.openmobilemaps.mapscore.kmp.KMCoord, zoom: Float): io.openmobilemaps.mapscore.kmp.KMVec2F {
        val result = native.screenPosFromCoordZoom(coord.asPlatform(), zoom)
        return (result as io.openmobilemaps.mapscore.shared.graphics.common.Vec2F).asKmp()
    }

    actual fun createTrackedCoordinate(coordinate: io.openmobilemaps.mapscore.kmp.KMCoord, callback: KMTrackedCoordinateCallbackInterface): KMTrackedCoordinateInterface {
        val result = native.createTrackedCoordinate(coordinate.asPlatform(), callback.asPlatform())
        return (result as io.openmobilemaps.mapscore.shared.map.TrackedCoordinateInterface).asKmp()
    }

    actual fun mapUnitsFromPixels(distancePx: Double): Double {
        val result = native.mapUnitsFromPixels(distancePx)
        return result
    }

    actual fun getScalingFactor(): Double {
        val result = native.getScalingFactor()
        return result
    }

    actual fun coordIsVisibleOnScreen(coord: io.openmobilemaps.mapscore.kmp.KMCoord, paddingPc: Float): Boolean {
        val result = native.coordIsVisibleOnScreen(coord.asPlatform(), paddingPc)
        return result
    }

    actual fun setRotationEnabled(enabled: Boolean) {
        native.setRotationEnabled(enabled)
    }

    actual fun setSnapToNorthEnabled(enabled: Boolean) {
        native.setSnapToNorthEnabled(enabled)
    }

    actual fun setBoundsRestrictWholeVisibleRect(enabled: Boolean) {
        native.setBoundsRestrictWholeVisibleRect(enabled)
    }

    actual fun asCameraInterface(): io.openmobilemaps.mapscore.kmp.KMCameraInterface {
        val result = native.asCameraInterface()
        return (result as io.openmobilemaps.mapscore.shared.graphics.CameraInterface).asKmp()
    }

    actual fun getLastVpMatrixD(): List<Double>? {
        val result = native.getLastVpMatrixD()
        return result?.let { ArrayList(it.map { it }) }
    }

    actual fun getLastVpMatrix(): List<Float>? {
        val result = native.getLastVpMatrix()
        return result?.let { ArrayList(it.map { it }) }
    }

    actual fun getLastInverseVpMatrix(): List<Float>? {
        val result = native.getLastInverseVpMatrix()
        return result?.let { ArrayList(it.map { it }) }
    }

    actual fun getLastVpMatrixViewBounds(): io.openmobilemaps.mapscore.kmp.KMRectCoord? {
        val result = native.getLastVpMatrixViewBounds()
        return result?.let { (it as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp() }
    }

    actual fun getLastVpMatrixRotation(): Float? {
        val result = native.getLastVpMatrixRotation()
        return result?.let { it }
    }

    actual fun getLastVpMatrixZoom(): Float? {
        val result = native.getLastVpMatrixZoom()
        return result?.let { it }
    }

    actual fun getLastCameraPosition(): io.openmobilemaps.mapscore.kmp.KMVec3D? {
        val result = native.getLastCameraPosition()
        return result?.let { (it as io.openmobilemaps.mapscore.shared.graphics.common.Vec3D).asKmp() }
    }

    actual fun asMapCamera3d(): KMMapCamera3dInterface? {
        val result = native.asMapCamera3d()
        return result?.let { (it as io.openmobilemaps.mapscore.shared.map.MapCamera3dInterface).asKmp() }
    }

    actual companion object
    {

        actual fun create(mapInterface: KMMapInterface, screenDensityPpi: Float, is3D: Boolean): KMMapCameraInterface {
            val result = MapCameraInterface.create(mapInterface.asPlatform(), screenDensityPpi, is3D)
            return (result as io.openmobilemaps.mapscore.shared.map.MapCameraInterface).asKmp()
        }
    }
}

public fun KMMapCameraInterface.asPlatform(): MapCameraInterface = nativeHandle as MapCameraInterface
public fun MapCameraInterface.asKmp(): KMMapCameraInterface = KMMapCameraInterface(this)
