// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

actual interface KMMapReadyCallbackInterface
{

    actual fun stateDidUpdate(state: KMLayerReadyState)
}

private class KMMapReadyCallbackInterfacePlatformWrapper(internal val nativeHandle: io.openmobilemaps.mapscore.shared.map.MapReadyCallbackInterface) : KMMapReadyCallbackInterface
{

    override fun stateDidUpdate(state: KMLayerReadyState) {
        nativeHandle.stateDidUpdate(state.asPlatform())
    }
}

private class KMMapReadyCallbackInterfacePlatformProxy(private val delegate: KMMapReadyCallbackInterface) : io.openmobilemaps.mapscore.shared.map.MapReadyCallbackInterface()
{

    override fun stateDidUpdate(state: io.openmobilemaps.mapscore.shared.map.LayerReadyState) {
        delegate.stateDidUpdate((state as io.openmobilemaps.mapscore.shared.map.LayerReadyState).asKmp())
    }
}

internal fun KMMapReadyCallbackInterface.asPlatform(): io.openmobilemaps.mapscore.shared.map.MapReadyCallbackInterface = when (this) {
    is KMMapReadyCallbackInterfacePlatformWrapper -> this.nativeHandle
    else -> KMMapReadyCallbackInterfacePlatformProxy(this)
}
internal fun io.openmobilemaps.mapscore.shared.map.MapReadyCallbackInterface.asKmp(): KMMapReadyCallbackInterface = KMMapReadyCallbackInterfacePlatformWrapper(this)
