// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.graphics.objects.PolygonGroup2dInterface

actual interface KMPolygonGroup2dInterface
{

    actual fun setVertices(vertices: KMSharedBytes, indices: KMSharedBytes, origin: KMVec3D)

    actual fun asGraphicsObject(): KMGraphicsObjectInterface
}

private class KMPolygonGroup2dInterfacePlatformWrapper(internal val nativeHandle: PolygonGroup2dInterface) : KMPolygonGroup2dInterface
{

    override fun setVertices(vertices: KMSharedBytes, indices: KMSharedBytes, origin: KMVec3D) {
        nativeHandle.setVertices(vertices.asPlatform(), indices.asPlatform(), origin.asPlatform())
    }

    override fun asGraphicsObject(): KMGraphicsObjectInterface {
        val result = nativeHandle.asGraphicsObject()
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectInterface).asKmp()
    }
}

private class KMPolygonGroup2dInterfacePlatformProxy(private val delegate: KMPolygonGroup2dInterface) : PolygonGroup2dInterface()
{

    override fun setVertices(vertices: io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes, indices: io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes, origin: io.openmobilemaps.mapscore.shared.graphics.common.Vec3D) {
        delegate.setVertices((vertices as io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes).asKmp(), (indices as io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes).asKmp(), (origin as io.openmobilemaps.mapscore.shared.graphics.common.Vec3D).asKmp())
    }

    override fun asGraphicsObject(): io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectInterface {
        val result = delegate.asGraphicsObject()
        return result.asPlatform()
    }
}

internal fun KMPolygonGroup2dInterface.asPlatform(): PolygonGroup2dInterface = when (this) {
    is KMPolygonGroup2dInterfacePlatformWrapper -> this.nativeHandle
    else -> KMPolygonGroup2dInterfacePlatformProxy(this)
}
internal fun PolygonGroup2dInterface.asKmp(): KMPolygonGroup2dInterface = KMPolygonGroup2dInterfacePlatformWrapper(this)
