// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

package io.openmobilemaps.mapscore.kmp

actual typealias KMRectCoord = io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord

internal fun KMRectCoord.asPlatform(): io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord = this
public fun io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord.asKmp(): KMRectCoord = this
