// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMSceneInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as io.openmobilemaps.mapscore.shared.graphics.SceneInterface

    actual fun setCallbackHandler(callbackInterface: KMSceneCallbackInterface) {
        native.setCallbackHandler(callbackInterface.asPlatform())
    }

    actual fun setCamera(camera: KMCameraInterface) {
        native.setCamera(camera.asPlatform())
    }

    actual fun getCamera(): KMCameraInterface {
        val result = native.getCamera()
        return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.CameraInterface)).asKmp()
    }

    actual fun getRenderer(): KMRendererInterface {
        val result = native.getRenderer()
        return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.RendererInterface)).asKmp()
    }

    actual fun getRenderingContext(): KMRenderingContextInterface {
        val result = native.getRenderingContext()
        return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface)).asKmp()
    }

    actual fun getGraphicsFactory(): KMGraphicsObjectFactoryInterface {
        val result = native.getGraphicsFactory()
        return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectFactoryInterface)).asKmp()
    }

    actual fun getShaderFactory(): KMShaderFactoryInterface {
        val result = native.getShaderFactory()
        return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.shader.ShaderFactoryInterface)).asKmp()
    }

    actual fun prepare() {
        native.prepare()
    }

    actual fun drawFrame(target: KMRenderTargetInterface?) {
        native.drawFrame(target?.let { it.asPlatform() })
    }

    actual fun compute() {
        native.compute()
    }

    actual fun clear() {
        native.clear()
    }

    actual fun invalidate() {
        native.invalidate()
    }

    actual companion object
    {

        actual fun create(graphicsFactory: KMGraphicsObjectFactoryInterface, shaderFactory: KMShaderFactoryInterface, renderingContext: KMRenderingContextInterface): KMSceneInterface {
            val result = io.openmobilemaps.mapscore.shared.graphics.SceneInterface.create(graphicsFactory.asPlatform(), shaderFactory.asPlatform(), renderingContext.asPlatform())
            return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.SceneInterface)).asKmp()
        }

        actual fun createWithOpenGl(): KMSceneInterface {
            val result = io.openmobilemaps.mapscore.shared.graphics.SceneInterface.createWithOpenGl()
            return requireNotNull((result as io.openmobilemaps.mapscore.shared.graphics.SceneInterface)).asKmp()
        }
    }
}

internal fun KMSceneInterface.asPlatform(): io.openmobilemaps.mapscore.shared.graphics.SceneInterface = nativeHandle as io.openmobilemaps.mapscore.shared.graphics.SceneInterface
internal fun io.openmobilemaps.mapscore.shared.graphics.SceneInterface.asKmp(): KMSceneInterface = KMSceneInterface(this)
