// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.map.layers.text.TextLayerInterface

actual class KMTextLayerInterface actual public constructor(
    nativeHandle: Any,
) {
    internal val nativeHandle: Any = nativeHandle
    private val native = nativeHandle as TextLayerInterface

    actual fun setTexts(texts: List<KMTextInfoInterface>) {
        native.setTexts(ArrayList(texts.map { it.asPlatform() }))
    }

    actual fun asLayerInterface(): io.openmobilemaps.mapscore.kmp.KMLayerInterface {
        val result = native.asLayerInterface()
        return (result as io.openmobilemaps.mapscore.shared.map.LayerInterface).asKmp()
    }

    actual fun invalidate() {
        native.invalidate()
    }

    actual companion object
    {

        actual fun create(fontLoader: io.openmobilemaps.mapscore.kmp.KMFontLoaderInterface): KMTextLayerInterface {
            val result = TextLayerInterface.create(fontLoader.asPlatform())
            return (result as io.openmobilemaps.mapscore.shared.map.layers.text.TextLayerInterface).asKmp()
        }
    }
}

public fun KMTextLayerInterface.asPlatform(): TextLayerInterface = nativeHandle as TextLayerInterface
public fun TextLayerInterface.asKmp(): KMTextLayerInterface = KMTextLayerInterface(this)
