// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.graphics.objects.TexturedPolygonInterface

actual interface KMTexturedPolygonInterface
{

    actual fun setVertices(vertices: io.openmobilemaps.mapscore.kmp.KMSharedBytes, indices: io.openmobilemaps.mapscore.kmp.KMSharedBytes, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, is3d: Boolean)

    actual fun setSubdivisionFactor(factor: Int)

    actual fun setMinMagFilter(filterType: KMTextureFilterType)

    actual fun loadTexture(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, textureHolder: KMTextureHolderInterface)

    actual fun loadDualTexture(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, textureHolder: KMTextureHolderInterface, elevationHolder: KMTextureHolderInterface?)

    actual fun removeTexture()

    actual fun asGraphicsObject(): KMGraphicsObjectInterface
}

private class KMTexturedPolygonInterfacePlatformWrapper(internal val nativeHandle: TexturedPolygonInterface) : KMTexturedPolygonInterface
{

    override fun setVertices(vertices: io.openmobilemaps.mapscore.kmp.KMSharedBytes, indices: io.openmobilemaps.mapscore.kmp.KMSharedBytes, origin: io.openmobilemaps.mapscore.kmp.KMVec3D, is3d: Boolean) {
        nativeHandle.setVertices(vertices.asPlatform(), indices.asPlatform(), origin.asPlatform(), is3d)
    }

    override fun setSubdivisionFactor(factor: Int) {
        nativeHandle.setSubdivisionFactor(factor)
    }

    override fun setMinMagFilter(filterType: KMTextureFilterType) {
        nativeHandle.setMinMagFilter(filterType.asPlatform())
    }

    override fun loadTexture(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, textureHolder: KMTextureHolderInterface) {
        nativeHandle.loadTexture(context.asPlatform(), textureHolder.asPlatform())
    }

    override fun loadDualTexture(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, textureHolder: KMTextureHolderInterface, elevationHolder: KMTextureHolderInterface?) {
        nativeHandle.loadDualTexture(context.asPlatform(), textureHolder.asPlatform(), elevationHolder?.let { it.asPlatform() })
    }

    override fun removeTexture() {
        nativeHandle.removeTexture()
    }

    override fun asGraphicsObject(): KMGraphicsObjectInterface {
        val result = nativeHandle.asGraphicsObject()
        return (result as io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectInterface).asKmp()
    }
}

private class KMTexturedPolygonInterfacePlatformProxy(private val delegate: KMTexturedPolygonInterface) : TexturedPolygonInterface()
{

    override fun setVertices(vertices: io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes, indices: io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes, origin: io.openmobilemaps.mapscore.shared.graphics.common.Vec3D, is3d: Boolean) {
        delegate.setVertices((vertices as io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes).asKmp(), (indices as io.openmobilemaps.mapscore.shared.graphics.common.SharedBytes).asKmp(), (origin as io.openmobilemaps.mapscore.shared.graphics.common.Vec3D).asKmp(), is3d)
    }

    override fun setSubdivisionFactor(factor: Int) {
        delegate.setSubdivisionFactor(factor)
    }

    override fun setMinMagFilter(filterType: io.openmobilemaps.mapscore.shared.graphics.objects.TextureFilterType) {
        delegate.setMinMagFilter((filterType as io.openmobilemaps.mapscore.shared.graphics.objects.TextureFilterType).asKmp())
    }

    override fun loadTexture(context: io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface, textureHolder: io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface) {
        delegate.loadTexture((context as io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface).asKmp(), (textureHolder as io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface).asKmp())
    }

    override fun loadDualTexture(context: io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface, textureHolder: io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface, elevationHolder: io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface?) {
        delegate.loadDualTexture((context as io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface).asKmp(), (textureHolder as io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface).asKmp(), elevationHolder?.let { (it as io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface).asKmp() })
    }

    override fun removeTexture() {
        delegate.removeTexture()
    }

    override fun asGraphicsObject(): io.openmobilemaps.mapscore.shared.graphics.objects.GraphicsObjectInterface {
        val result = delegate.asGraphicsObject()
        return result.asPlatform()
    }
}

public fun KMTexturedPolygonInterface.asPlatform(): TexturedPolygonInterface = when (this) {
    is KMTexturedPolygonInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTexturedPolygonInterfacePlatformProxy(this)
}
public fun TexturedPolygonInterface.asKmp(): KMTexturedPolygonInterface = KMTexturedPolygonInterfacePlatformWrapper(this)
