// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_layer.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.map.layers.tiled.Tiled2dMapReadyStateListener

actual interface KMTiled2dMapReadyStateListener
{

    actual fun stateUpdate(state: KMLayerReadyState)
}

private class KMTiled2dMapReadyStateListenerPlatformWrapper(internal val nativeHandle: Tiled2dMapReadyStateListener) : KMTiled2dMapReadyStateListener
{

    override fun stateUpdate(state: KMLayerReadyState) {
        nativeHandle.stateUpdate(state.asPlatform())
    }
}

private class KMTiled2dMapReadyStateListenerPlatformProxy(private val delegate: KMTiled2dMapReadyStateListener) : Tiled2dMapReadyStateListener()
{

    override fun stateUpdate(state: io.openmobilemaps.mapscore.shared.map.LayerReadyState) {
        delegate.stateUpdate((state as io.openmobilemaps.mapscore.shared.map.LayerReadyState).asKmp())
    }
}

internal fun KMTiled2dMapReadyStateListener.asPlatform(): Tiled2dMapReadyStateListener = when (this) {
    is KMTiled2dMapReadyStateListenerPlatformWrapper -> this.nativeHandle
    else -> KMTiled2dMapReadyStateListenerPlatformProxy(this)
}
internal fun Tiled2dMapReadyStateListener.asKmp(): KMTiled2dMapReadyStateListener = KMTiled2dMapReadyStateListenerPlatformWrapper(this)
