// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

package io.openmobilemaps.mapscore.kmp

import io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.Tiled2dMapVectorLayerSelectionCallbackInterface

actual interface KMTiled2dMapVectorLayerSelectionCallbackInterface
{

    actual fun didSelectFeature(featureInfo: KMVectorLayerFeatureInfo, layerIdentifier: String, coord: KMCoord): Boolean

    actual fun didMultiSelectLayerFeatures(featureInfos: ArrayList<KMVectorLayerFeatureInfo>, layerIdentifier: String, coord: KMCoord): Boolean

    actual fun didClickBackgroundConfirmed(coord: KMCoord): Boolean
}

private class KMTiled2dMapVectorLayerSelectionCallbackInterfacePlatformWrapper(internal val nativeHandle: Tiled2dMapVectorLayerSelectionCallbackInterface) : KMTiled2dMapVectorLayerSelectionCallbackInterface
{

    override fun didSelectFeature(featureInfo: KMVectorLayerFeatureInfo, layerIdentifier: String, coord: KMCoord): Boolean {
        val result = nativeHandle.didSelectFeature(featureInfo.asPlatform(), layerIdentifier, coord.asPlatform())
        return result
    }

    override fun didMultiSelectLayerFeatures(featureInfos: ArrayList<KMVectorLayerFeatureInfo>, layerIdentifier: String, coord: KMCoord): Boolean {
        val result = nativeHandle.didMultiSelectLayerFeatures(ArrayList(featureInfos.map { it.asPlatform() }), layerIdentifier, coord.asPlatform())
        return result
    }

    override fun didClickBackgroundConfirmed(coord: KMCoord): Boolean {
        val result = nativeHandle.didClickBackgroundConfirmed(coord.asPlatform())
        return result
    }
}

private class KMTiled2dMapVectorLayerSelectionCallbackInterfacePlatformProxy(private val delegate: KMTiled2dMapVectorLayerSelectionCallbackInterface) : Tiled2dMapVectorLayerSelectionCallbackInterface()
{

    override fun didSelectFeature(featureInfo: io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.VectorLayerFeatureInfo, layerIdentifier: String, coord: io.openmobilemaps.mapscore.shared.map.coordinates.Coord): Boolean {
        val result = delegate.didSelectFeature((featureInfo as io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.VectorLayerFeatureInfo).asKmp(), layerIdentifier, (coord as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp())
        return result
    }

    override fun didMultiSelectLayerFeatures(featureInfos: ArrayList<io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.VectorLayerFeatureInfo>, layerIdentifier: String, coord: io.openmobilemaps.mapscore.shared.map.coordinates.Coord): Boolean {
        val result = delegate.didMultiSelectLayerFeatures(ArrayList(featureInfos.map { (it as io.openmobilemaps.mapscore.shared.map.layers.tiled.vector.VectorLayerFeatureInfo).asKmp() }), layerIdentifier, (coord as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp())
        return result
    }

    override fun didClickBackgroundConfirmed(coord: io.openmobilemaps.mapscore.shared.map.coordinates.Coord): Boolean {
        val result = delegate.didClickBackgroundConfirmed((coord as io.openmobilemaps.mapscore.shared.map.coordinates.Coord).asKmp())
        return result
    }
}

internal fun KMTiled2dMapVectorLayerSelectionCallbackInterface.asPlatform(): Tiled2dMapVectorLayerSelectionCallbackInterface = when (this) {
    is KMTiled2dMapVectorLayerSelectionCallbackInterfacePlatformWrapper -> this.nativeHandle
    else -> KMTiled2dMapVectorLayerSelectionCallbackInterfacePlatformProxy(this)
}
internal fun Tiled2dMapVectorLayerSelectionCallbackInterface.asKmp(): KMTiled2dMapVectorLayerSelectionCallbackInterface = KMTiled2dMapVectorLayerSelectionCallbackInterfacePlatformWrapper(this)
