// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wmts_capabilities.djinni

package io.openmobilemaps.mapscore.kmp

actual class KMWmtsLayerDescription actual public constructor(
    identifier: String,
    title: String?,
    abstractText: String?,
    dimensions: List<KMWmtsLayerDimension>,
    bounds: io.openmobilemaps.mapscore.kmp.KMRectCoord?,
    tileMatrixSetLink: String,
    resourceTemplate: String,
    resourceFormat: String,
) {
    actual val identifier: String = identifier
    actual val title: String? = title
    actual val abstractText: String? = abstractText
    actual val dimensions: List<KMWmtsLayerDimension> = dimensions
    actual val bounds: io.openmobilemaps.mapscore.kmp.KMRectCoord? = bounds
    actual val tileMatrixSetLink: String = tileMatrixSetLink
    actual val resourceTemplate: String = resourceTemplate
    actual val resourceFormat: String = resourceFormat
}

public fun KMWmtsLayerDescription.asPlatform(): io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription = io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription(
    identifier = identifier,
    title = title?.let { it },
    abstractText = abstractText?.let { it },
    dimensions = ArrayList(dimensions.map { it.asPlatform() }),
    bounds = bounds?.let { it.asPlatform() },
    tileMatrixSetLink = tileMatrixSetLink,
    resourceTemplate = resourceTemplate,
    resourceFormat = resourceFormat,
)
public fun io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDescription.asKmp(): KMWmtsLayerDescription = KMWmtsLayerDescription(
    identifier = this.identifier,
    title = this.title?.let { it },
    abstractText = this.abstractText?.let { it },
    dimensions = ArrayList(this.dimensions.map { (it as io.openmobilemaps.mapscore.shared.map.layers.tiled.raster.wmts.WmtsLayerDimension).asKmp() }),
    bounds = this.bounds?.let { (it as io.openmobilemaps.mapscore.shared.map.coordinates.RectCoord).asKmp() },
    tileMatrixSetLink = this.tileMatrixSetLink,
    resourceTemplate = this.resourceTemplate,
    resourceFormat = this.resourceFormat,
)
