name: ios

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: 'recursive'
    - name: Switch to Xcode 13.4.1
      run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app
    - name: Build
      run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
