// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

expect interface KMCameraInterface {

    fun getVpMatrix(): List<Float>

    fun getScalingFactor(): Double

    fun getOrigin(): io.openmobilemaps.mapscore.kmp.KMVec3D

    fun viewportSizeChanged()
}
