// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

expect interface KMComputePassInterface {

    fun getComputeObjects(): List<io.openmobilemaps.mapscore.kmp.KMComputeObjectInterface>
}
