// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from exception_logger.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMExceptionLoggerInterface constructor(nativeHandle: Any) {

    companion object
    {

        fun setLoggerDelegate(delegate: KMExceptionLoggerDelegateInterface)
    }
}
