// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from icon.djinni

package io.openmobilemaps.mapscore.kmp

expect enum class KMIconType {
    SCALE_INVARIANT,
    ROTATION_INVARIANT,
    INVARIANT,
    FIXED,
}
