// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMMapCameraInterface constructor(nativeHandle: Any) {

    fun freeze(freeze: Boolean)

    fun moveToCenterPositionZoom(centerPosition: io.openmobilemaps.mapscore.kmp.KMCoord, zoom: Double, animated: Boolean)

    fun moveToCenterPosition(centerPosition: io.openmobilemaps.mapscore.kmp.KMCoord, animated: Boolean)

    fun moveToBoundingBox(boundingBox: io.openmobilemaps.mapscore.kmp.KMRectCoord, paddingPc: Float, animated: Boolean, minZoom: Double?, maxZoom: Double?)

    fun getCenterPosition(): io.openmobilemaps.mapscore.kmp.KMCoord

    fun setZoom(zoom: Double, animated: Boolean)

    fun getZoom(): Double

    fun setRotation(angle: Float, animated: Boolean)

    fun getRotation(): Float

    fun setMinZoom(minZoom: Double)

    fun setMaxZoom(maxZoom: Double)

    fun getMinZoom(): Double

    fun getMaxZoom(): Double

    fun setBounds(bounds: io.openmobilemaps.mapscore.kmp.KMRectCoord)

    fun getBounds(): io.openmobilemaps.mapscore.kmp.KMRectCoord

    fun isInBounds(coords: io.openmobilemaps.mapscore.kmp.KMCoord): Boolean

    fun setPaddingLeft(padding: Float)

    fun setPaddingRight(padding: Float)

    fun setPaddingTop(padding: Float)

    fun setPaddingBottom(padding: Float)

    fun getVisibleRect(): io.openmobilemaps.mapscore.kmp.KMRectCoord

    fun getPaddingAdjustedVisibleRect(): io.openmobilemaps.mapscore.kmp.KMRectCoord

    fun getScreenDensityPpi(): Float

    fun update()

    fun getInvariantModelMatrix(coordinate: io.openmobilemaps.mapscore.kmp.KMCoord, scaleInvariant: Boolean, rotationInvariant: Boolean): List<Float>

    fun addListener(listener: io.openmobilemaps.mapscore.kmp.KMMapCameraListenerInterface)

    fun removeListener(listener: io.openmobilemaps.mapscore.kmp.KMMapCameraListenerInterface)

    fun notifyListenerBoundsChange()

    fun coordFromScreenPosition(posScreen: io.openmobilemaps.mapscore.kmp.KMVec2F): io.openmobilemaps.mapscore.kmp.KMCoord

    fun coordFromScreenPositionZoom(posScreen: io.openmobilemaps.mapscore.kmp.KMVec2F, zoom: Float): io.openmobilemaps.mapscore.kmp.KMCoord

    fun screenPosFromCoord(coord: io.openmobilemaps.mapscore.kmp.KMCoord): io.openmobilemaps.mapscore.kmp.KMVec2F

    fun screenPosFromCoordZoom(coord: io.openmobilemaps.mapscore.kmp.KMCoord, zoom: Float): io.openmobilemaps.mapscore.kmp.KMVec2F

    fun createTrackedCoordinate(coordinate: io.openmobilemaps.mapscore.kmp.KMCoord, callback: KMTrackedCoordinateCallbackInterface): KMTrackedCoordinateInterface

    fun mapUnitsFromPixels(distancePx: Double): Double

    fun getScalingFactor(): Double

    fun coordIsVisibleOnScreen(coord: io.openmobilemaps.mapscore.kmp.KMCoord, paddingPc: Float): Boolean

    fun setRotationEnabled(enabled: Boolean)

    fun setSnapToNorthEnabled(enabled: Boolean)

    fun setBoundsRestrictWholeVisibleRect(enabled: Boolean)

    fun asCameraInterface(): io.openmobilemaps.mapscore.kmp.KMCameraInterface

    fun getLastVpMatrixD(): List<Double>?

    fun getLastVpMatrix(): List<Float>?

    fun getLastInverseVpMatrix(): List<Float>?

    fun getLastVpMatrixViewBounds(): io.openmobilemaps.mapscore.kmp.KMRectCoord?

    fun getLastVpMatrixRotation(): Float?

    fun getLastVpMatrixZoom(): Float?

    fun getLastCameraPosition(): io.openmobilemaps.mapscore.kmp.KMVec3D?

    fun asMapCamera3d(): KMMapCamera3dInterface?

    companion object
    {

        fun create(mapInterface: KMMapInterface, screenDensityPpi: Float, is3D: Boolean): KMMapCameraInterface
    }
}
