// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from maps_core.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMMapsCoreSharedModule constructor(nativeHandle: Any) {

    companion object
    {

        fun version(): String
    }
}
