// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMPolygonPatternGroupShaderInterface constructor(nativeHandle: Any) {

    fun asShaderProgramInterface(): KMShaderProgramInterface
}
