// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from polygon.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMPolygonInfo(
    identifier: String,
    coordinates: io.openmobilemaps.mapscore.kmp.KMPolygonCoord,
    color: io.openmobilemaps.mapscore.kmp.KMColor,
    highlightColor: io.openmobilemaps.mapscore.kmp.KMColor,
) {
    val identifier: String
    val coordinates: io.openmobilemaps.mapscore.kmp.KMPolygonCoord
    val color: io.openmobilemaps.mapscore.kmp.KMColor
    val highlightColor: io.openmobilemaps.mapscore.kmp.KMColor
}
