// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMPolygonGroupShaderInterface constructor(nativeHandle: Any) {

    fun setStyles(styles: KMSharedBytes)

    fun asShaderProgramInterface(): KMShaderProgramInterface
}
