// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMRenderPassConfig(
    renderPassIndex: Int,
    isPassMasked: Boolean,
    renderTarget: KMRenderTargetInterface?,
) {
    val renderPassIndex: Int
    val isPassMasked: Boolean
    val renderTarget: KMRenderTargetInterface?
}
