// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.kmp

expect interface KMTextInterface {

    fun setTextsShared(vertices: io.openmobilemaps.mapscore.kmp.KMSharedBytes, indices: io.openmobilemaps.mapscore.kmp.KMSharedBytes)

    fun loadTexture(context: io.openmobilemaps.mapscore.kmp.KMRenderingContextInterface, textureHolder: KMTextureHolderInterface)

    fun removeTexture()

    fun asGraphicsObject(): KMGraphicsObjectInterface
}
