// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.kmp

expect interface KMTextInterface {

    fun setTextsShared(vertices: KMSharedBytes, indices: KMSharedBytes)

    fun loadTexture(context: KMRenderingContextInterface, textureHolder: KMTextureHolderInterface)

    fun removeTexture()

    fun asGraphicsObject(): KMGraphicsObjectInterface
}
