// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMVec2I(
    x: Int,
    y: Int,
) {
    val x: Int
    val y: Int
}
