// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#pragma once

#include <string>
#include <utility>

struct MapCoordinateSystem final {
    std::string identifier;
    float boundsLeft;
    float boundsTop;
    float boundsRight;
    float boundsBottom;
    float zoomMin;
    float zoomMax;
    float unitToMeterFactor;

    MapCoordinateSystem(std::string identifier_,
                        float boundsLeft_,
                        float boundsTop_,
                        float boundsRight_,
                        float boundsBottom_,
                        float zoomMin_,
                        float zoomMax_,
                        float unitToMeterFactor_)
    : identifier(std::move(identifier_))
    , boundsLeft(std::move(boundsLeft_))
    , boundsTop(std::move(boundsTop_))
    , boundsRight(std::move(boundsRight_))
    , boundsBottom(std::move(boundsBottom_))
    , zoomMin(std::move(zoomMin_))
    , zoomMax(std::move(zoomMax_))
    , unitToMeterFactor(std::move(unitToMeterFactor_))
    {}
};
