// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from loader.djinni

package io.openmobilemaps.mapscore.shared.map.loader

data class FontLoaderResult(
    var imageData: io.openmobilemaps.mapscore.shared.graphics.objects.TextureHolderInterface?,
    var fontData: FontData?,
    var status: LoaderStatus,
)