// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_object.djinni

#pragma once

#include "RenderConfigInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeRenderConfigInterface final : ::djinni::JniInterface<::RenderConfigInterface, NativeRenderConfigInterface> {
public:
    using CppType = std::shared_ptr<::RenderConfigInterface>;
    using CppOptType = std::shared_ptr<::RenderConfigInterface>;
    using JniType = jobject;

    using Boxed = NativeRenderConfigInterface;

    ~NativeRenderConfigInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeRenderConfigInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeRenderConfigInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeRenderConfigInterface();
    friend ::djinni::JniClass<NativeRenderConfigInterface>;
    friend ::djinni::JniInterface<::RenderConfigInterface, NativeRenderConfigInterface>;

};

}  // namespace djinni_generated
