// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from polygon.djinni

#pragma once

#include "PolygonMaskObject3dInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativePolygonMaskObject3dInterface final : ::djinni::JniInterface<::PolygonMaskObject3dInterface, NativePolygonMaskObject3dInterface> {
public:
    using CppType = std::shared_ptr<::PolygonMaskObject3dInterface>;
    using CppOptType = std::shared_ptr<::PolygonMaskObject3dInterface>;
    using JniType = jobject;

    using Boxed = NativePolygonMaskObject3dInterface;

    ~NativePolygonMaskObject3dInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativePolygonMaskObject3dInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativePolygonMaskObject3dInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativePolygonMaskObject3dInterface();
    friend ::djinni::JniClass<NativePolygonMaskObject3dInterface>;
    friend ::djinni::JniInterface<::PolygonMaskObject3dInterface, NativePolygonMaskObject3dInterface>;

};

} // namespace djinni_generated
