// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

#include "NativeRenderLineDescription.h"  // my header
#include "Marshal.hpp"
#include "NativeVec2D.h"

namespace djinni_generated {

NativeRenderLineDescription::NativeRenderLineDescription() = default;

NativeRenderLineDescription::~NativeRenderLineDescription() = default;

auto NativeRenderLineDescription::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeRenderLineDescription>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativeVec2D>::fromCpp(jniEnv, c.positions)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.styleIndex)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeRenderLineDescription::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeRenderLineDescription>::get();
    return {::djinni::List<::djinni_generated::NativeVec2D>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_positions)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_styleIndex))};
}

}  // namespace djinni_generated
