// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

#pragma once

#include "Quad2dInterface.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeQuad2dInterface final : ::djinni::JniInterface<::Quad2dInterface, NativeQuad2dInterface> {
public:
    using CppType = std::shared_ptr<::Quad2dInterface>;
    using CppOptType = std::shared_ptr<::Quad2dInterface>;
    using JniType = jobject;

    using Boxed = NativeQuad2dInterface;

    ~NativeQuad2dInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeQuad2dInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeQuad2dInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeQuad2dInterface();
    friend ::djinni::JniClass<NativeQuad2dInterface>;
    friend ::djinni::JniInterface<::Quad2dInterface, NativeQuad2dInterface>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Quad2dInterface
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void setFrame(const ::Quad2dD & frame, const ::RectD & textureCoordinates) override;
        void loadTexture(const std::shared_ptr<::TextureHolderInterface> & textureHolder) override;
        void removeTexture() override;
        std::shared_ptr<::GraphicsObjectInterface> asGraphicsObject() override;

    private:
        friend ::djinni::JniInterface<::Quad2dInterface, ::djinni_generated::NativeQuad2dInterface>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/openmobilemaps/mapscore/shared/graphics/objects/Quad2dInterface") };
    const jmethodID method_setFrame { ::djinni::jniGetMethodID(clazz.get(), "setFrame", "(Lio/openmobilemaps/mapscore/shared/graphics/common/Quad2dD;Lio/openmobilemaps/mapscore/shared/graphics/common/RectD;)V") };
    const jmethodID method_loadTexture { ::djinni::jniGetMethodID(clazz.get(), "loadTexture", "(Lio/openmobilemaps/mapscore/shared/graphics/objects/TextureHolderInterface;)V") };
    const jmethodID method_removeTexture { ::djinni::jniGetMethodID(clazz.get(), "removeTexture", "()V") };
    const jmethodID method_asGraphicsObject { ::djinni::jniGetMethodID(clazz.get(), "asGraphicsObject", "()Lio/openmobilemaps/mapscore/shared/graphics/objects/GraphicsObjectInterface;") };
};

}  // namespace djinni_generated
