// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from task_scheduler.djinni

package io.openmobilemaps.mapscore.shared.map.scheduling;

public final class TaskConfig {


    /*package*/ final String id;

    /*package*/ final long delay;

    /*package*/ final TaskPriority priority;

    /*package*/ final ExecutionEnvironment executionEnvironment;

    public TaskConfig(
            String id,
            long delay,
            TaskPriority priority,
            ExecutionEnvironment executionEnvironment) {
        this.id = id;
        this.delay = delay;
        this.priority = priority;
        this.executionEnvironment = executionEnvironment;
    }

    public String getId() {
        return id;
    }

    public long getDelay() {
        return delay;
    }

    public TaskPriority getPriority() {
        return priority;
    }

    public ExecutionEnvironment getExecutionEnvironment() {
        return executionEnvironment;
    }

    @Override
    public String toString() {
        return "TaskConfig{" +
                "id=" + id +
                "," + "delay=" + delay +
                "," + "priority=" + priority +
                "," + "executionEnvironment=" + executionEnvironment +
        "}";
    }

}
