// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from shader.djinni

package ch.ubique.mapscore.shared.graphics.shader;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ShaderFactoryInterface {
    public abstract AlphaShaderInterface createAlphaShader();

    public abstract ColorLineShaderInterface createColorLineShader();

    public abstract ColorShaderInterface createColorShader();

    private static final class CppProxy extends ShaderFactoryInterface
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public AlphaShaderInterface createAlphaShader()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createAlphaShader(this.nativeRef);
        }
        private native AlphaShaderInterface native_createAlphaShader(long _nativeRef);

        @Override
        public ColorLineShaderInterface createColorLineShader()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createColorLineShader(this.nativeRef);
        }
        private native ColorLineShaderInterface native_createColorLineShader(long _nativeRef);

        @Override
        public ColorShaderInterface createColorShader()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_createColorShader(this.nativeRef);
        }
        private native ColorShaderInterface native_createColorShader(long _nativeRef);
    }
}
