// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCCameraMode3d)
{
    MCCameraMode3dGLOBE = 0,
    MCCameraMode3dTILTED_ORBITAL = 1,
    MCCameraMode3dONBOARDING_ROTATING_GLOBE = 2,
    MCCameraMode3dONBOARDING_ROTATING_SEMI_GLOBE = 3,
    MCCameraMode3dONBOARDING_CLOSE_ORBITAL = 4,
    MCCameraMode3dONBOARDING_FOCUS_ZURICH = 5,
};
