// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#import <Foundation/Foundation.h>
@protocol MCShaderProgramInterface;


@protocol MCColorCircleShaderInterface

- (void)setColor:(float)red
           green:(float)green
            blue:(float)blue
           alpha:(float)alpha;

- (void)setCircleStyle:(float)fillRed
             fillGreen:(float)fillGreen
              fillBlue:(float)fillBlue
             fillAlpha:(float)fillAlpha
             strokeRed:(float)strokeRed
           strokeGreen:(float)strokeGreen
            strokeBlue:(float)strokeBlue
           strokeAlpha:(float)strokeAlpha
           innerRadius:(float)innerRadius;

- (nullable id<MCShaderProgramInterface>)asShaderProgramInterface;

@end
