// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from coordinate_system.djinni

#import "MCCoordinateSystemIdentifiers+Private.h"
#import "MCCoordinateSystemIdentifiers.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface MCCoordinateSystemIdentifiers ()

- (id)initWithCpp:(const std::shared_ptr<::CoordinateSystemIdentifiers>&)cppRef;

@end

@implementation MCCoordinateSystemIdentifiers {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::CoordinateSystemIdentifiers>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::CoordinateSystemIdentifiers>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)RENDERSYSTEM {
    try {
        auto objcpp_result_ = ::CoordinateSystemIdentifiers::RENDERSYSTEM();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSString *)EPSG3857 {
    try {
        auto objcpp_result_ = ::CoordinateSystemIdentifiers::EPSG3857();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSString *)EPSG4326 {
    try {
        auto objcpp_result_ = ::CoordinateSystemIdentifiers::EPSG4326();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (nonnull NSString *)EPSG2056 {
    try {
        auto objcpp_result_ = ::CoordinateSystemIdentifiers::EPSG2056();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto CoordinateSystemIdentifiers::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto CoordinateSystemIdentifiers::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<MCCoordinateSystemIdentifiers>(cpp);
}

}  // namespace djinni_generated

@end
