// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map_helpers.djinni

#import "MCErrorManagerListener+Private.h"
#import "MCErrorManagerListener.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "MCTiledLayerError+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface MCErrorManagerListenerCppProxy : NSObject<MCErrorManagerListener>

- (id)initWithCpp:(const std::shared_ptr<::ErrorManagerListener>&)cppRef;

@end

@implementation MCErrorManagerListenerCppProxy {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ErrorManagerListener>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ErrorManagerListener>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)onTiledLayerErrorStateChanged:(nonnull NSArray<MCTiledLayerError *> *)errors {
    try {
        _cppRefHandle.get()->onTiledLayerErrorStateChanged(::djinni::List<::djinni_generated::TiledLayerError>::toCpp(errors));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

class ErrorManagerListener::ObjcProxy final
: public ::ErrorManagerListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::ErrorManagerListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onTiledLayerErrorStateChanged(const std::vector<::TiledLayerError> & c_errors) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onTiledLayerErrorStateChanged:(::djinni::List<::djinni_generated::TiledLayerError>::fromCpp(c_errors))];
        }
    }
};

} // namespace djinni_generated

namespace djinni_generated {

auto ErrorManagerListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    if ([(id)objc isKindOfClass:[MCErrorManagerListenerCppProxy class]]) {
        return ((MCErrorManagerListenerCppProxy*)objc)->_cppRefHandle.get();
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ErrorManagerListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    if (auto cppPtr = dynamic_cast<ObjcProxy*>(cpp.get())) {
        return cppPtr->djinni_private_get_proxied_objc_object();
    }
    return ::djinni::get_cpp_proxy<MCErrorManagerListenerCppProxy>(cpp);
}

} // namespace djinni_generated

@end
