// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from task_scheduler.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCExecutionEnvironment)
{
    MCExecutionEnvironmentIO = 0,
    MCExecutionEnvironmentCOMPUTATION = 1,
    MCExecutionEnvironmentGRAPHICS = 2,
};
