// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loader.djinni

#import <Foundation/Foundation.h>

@interface MCFont : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name;
+ (nonnull instancetype)fontWithName:(nonnull NSString *)name;

@property (nonatomic, readonly, nonnull) NSString * name;

@end
