// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from loader.djinni

#import "MCVec2D.h"
#import <Foundation/Foundation.h>

@interface MCFontInfo : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                            ascender:(double)ascender
                           descender:(double)descender
                        spaceAdvance:(double)spaceAdvance
                          bitmapSize:(nonnull MCVec2D *)bitmapSize
                                size:(double)size;
+ (nonnull instancetype)fontInfoWithName:(nonnull NSString *)name
                                ascender:(double)ascender
                               descender:(double)descender
                            spaceAdvance:(double)spaceAdvance
                              bitmapSize:(nonnull MCVec2D *)bitmapSize
                                    size:(double)size;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) double ascender;

@property (nonatomic, readonly) double descender;

@property (nonatomic, readonly) double spaceAdvance;

@property (nonatomic, readonly, nonnull) MCVec2D * bitmapSize;

/** font size rendered in bitmap multiplied by dpFactor */
@property (nonatomic, readonly) double size;

@end
