// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from geo_json_parser.djinni
#ifdef __cplusplus

#import "MCGeoJsonLine.h"
#include "GeoJsonLine.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCGeoJsonLine;

namespace djinni_generated {

struct GeoJsonLine
{
    using CppType = ::GeoJsonLine;
    using ObjcType = MCGeoJsonLine*;

    using Boxed = GeoJsonLine;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif
