// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

#import "MCRenderPassConfig.h"
#import "MCRenderingContextInterface.h"
#import <Foundation/Foundation.h>


@protocol MCGraphicsObjectInterface

/** Returns true, if graphics object is ready to be drawn */
- (BOOL)isReady;

/** Ensure calling on graphics thread */
- (void)setup:(nullable id<MCRenderingContextInterface>)context;

/** Clear graphics object and invalidate isReady */
- (void)clear;

/**
 * by defaults objects if masked are only rendered where the mask is set
 * if setting this flag the masked is applied inversly
 */
- (void)setIsInverseMasked:(BOOL)inversed;

/** Render the graphics object; ensure calling on graphics thread */
- (void)setDebugLabel:(nonnull NSString *)label;

- (void)render:(nullable id<MCRenderingContextInterface>)context
    renderPass:(nonnull MCRenderPassConfig *)renderPass
      vpMatrix:(int64_t)vpMatrix
       mMatrix:(int64_t)mMatrix
      isMasked:(BOOL)isMasked
screenPixelAsRealMeterFactor:(double)screenPixelAsRealMeterFactor;

@end
