// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@protocol MCLayerInterface;


@protocol MCIndexedLayerInterface

- (nullable id<MCLayerInterface>)getLayerInterface;

- (int32_t)getIndex;

@end
