// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

#import <Foundation/Foundation.h>
@class MCLineInfoInterface;


@protocol MCLineLayerCallbackInterface

- (void)onLineClickConfirmed:(nullable MCLineInfoInterface *)line;

@end
