// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from shader.djinni
#ifdef __cplusplus

#include "LineGroupShaderInterface.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MCLineGroupShaderInterface;

namespace djinni_generated {

class LineGroupShaderInterface
{
public:
    using CppType = std::shared_ptr<::LineGroupShaderInterface>;
    using CppOptType = std::shared_ptr<::LineGroupShaderInterface>;
    using ObjcType = id<MCLineGroupShaderInterface>;

    using Boxed = LineGroupShaderInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

#endif
