// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#import "MCSharedBytes.h"
#import <Foundation/Foundation.h>
@protocol MCShaderProgramInterface;


@protocol MCLineGroupShaderInterface

- (void)setStyles:(nonnull MCSharedBytes *)styles;

- (nullable id<MCShaderProgramInterface>)asShaderProgramInterface;

@end
