// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

#import "MCQuad2dD.h"
#import "MCSharedBytes.h"
#import <Foundation/Foundation.h>
@protocol MCGraphicsObjectInterface;


@protocol MCLine2dInstancedInterface

- (void)setFrame:(nonnull MCQuad2dD *)frame;

- (void)setInstanceCount:(int32_t)count;

- (void)setPositions:(nonnull MCSharedBytes *)positions;

- (nullable id<MCGraphicsObjectInterface>)asGraphicsObject;

@end
