// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

#import "MCSharedBytes.h"
#import <Foundation/Foundation.h>
@protocol MCGraphicsObjectInterface;


@protocol MCLine2dInterface

- (void)setLine:(nonnull MCSharedBytes *)line
        indices:(nonnull MCSharedBytes *)indices;

- (nullable id<MCGraphicsObjectInterface>)asGraphicsObject;

@end
