// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from line.djinni
#ifdef __cplusplus

#import "MCLineInfo.h"
#include "LineInfo.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCLineInfo;

namespace djinni_generated {

struct LineInfo
{
    using CppType = ::LineInfo;
    using ObjcType = MCLineInfo*;

    using Boxed = LineInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
#endif
