// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera.djinni
#ifdef __cplusplus

#include "MapCameraListenerInterface.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MCMapCameraListenerInterface;

namespace djinni_generated {

class MapCameraListenerInterface
{
public:
    using CppType = std::shared_ptr<::MapCameraListenerInterface>;
    using CppOptType = std::shared_ptr<::MapCameraListenerInterface>;
    using ObjcType = id<MCMapCameraListenerInterface>;

    using Boxed = MapCameraListenerInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif
