// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from camera.djinni

#import "MCRectCoord.h"
#import <Foundation/Foundation.h>


@protocol MCMapCamera2dListenerInterface

- (void)onVisibleBoundsChanged:(nonnull MCRectCoord *)visibleBounds
                          zoom:(double)zoom;

- (void)onRotationChanged:(float)angle;

- (void)onMapInteraction;

@end
