// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

#import "MCOwnedBytes+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto OwnedBytes::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.address),
            ::djinni::I32::toCpp(obj.elementCount),
            ::djinni::I32::toCpp(obj.bytesPerElement)};
}

auto OwnedBytes::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCOwnedBytes alloc] initWithAddress:(::djinni::I64::fromCpp(cpp.address))
                                    elementCount:(::djinni::I32::fromCpp(cpp.elementCount))
                                 bytesPerElement:(::djinni::I32::fromCpp(cpp.bytesPerElement))];
}

} // namespace djinni_generated
