// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from polygon.djinni
#ifdef __cplusplus

#import "MCPolygon.h"
#include "Polygon.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCPolygon;

namespace djinni_generated {

struct Polygon
{
    using CppType = ::Polygon;
    using ObjcType = MCPolygon*;

    using Boxed = Polygon;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
#endif
