// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from polygon.djinni

#import "MCLayerInterface.h"
#import "MCPolygon.h"
#import <Foundation/Foundation.h>
@class MCPolygonLayerInterface;


@interface MCPolygonLayerInterface : NSObject

+ (nullable MCPolygonLayerInterface *)create;

- (void)setPolygons:(nonnull NSArray<MCPolygon *> *)polygons;

- (nonnull NSArray<MCPolygon *> *)getPolygons;

- (void)remove:(nonnull MCPolygon *)polygon;

- (void)add:(nonnull MCPolygon *)polygon;

- (void)clear;

- (nullable id<MCLayerInterface>)asLayerInterface;

@end
