// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from polygon.djinni

#import "MCColor.h"
#import "MCCoord.h"
#import <Foundation/Foundation.h>

@interface MCPolygonInfo : NSObject
- (nonnull instancetype)initWithIdentifier:(nonnull NSString *)identifier
                               coordinates:(nonnull NSArray<MCCoord *> *)coordinates
                                     holes:(nonnull NSArray<NSArray<MCCoord *> *> *)holes
                                     color:(nonnull MCColor *)color
                            highlightColor:(nonnull MCColor *)highlightColor;
+ (nonnull instancetype)polygonInfoWithIdentifier:(nonnull NSString *)identifier
                                      coordinates:(nonnull NSArray<MCCoord *> *)coordinates
                                            holes:(nonnull NSArray<NSArray<MCCoord *> *> *)holes
                                            color:(nonnull MCColor *)color
                                   highlightColor:(nonnull MCColor *)highlightColor;

@property (nonatomic, readonly, nonnull) NSString * identifier;

@property (nonatomic, readonly, nonnull) NSArray<MCCoord *> * coordinates;

@property (nonatomic, readonly, nonnull) NSArray<NSArray<MCCoord *> *> * holes;

@property (nonatomic, readonly, nonnull) MCColor * color;

@property (nonatomic, readonly, nonnull) MCColor * highlightColor;

@end
