// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from shader.djinni

#import "MCPolygonStyle.h"
#import <Foundation/Foundation.h>
@protocol MCShaderProgramInterface;


@protocol MCPolygonGroupShaderInterface

- (void)setStyles:(nonnull NSArray<MCPolygonStyle *> *)styles;

- (nullable id<MCShaderProgramInterface>)asShaderProgramInterface;

@end
