// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni
#ifdef __cplusplus

#import "MCQuadCoord.h"
#include "QuadCoord.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCQuadCoord;

namespace djinni_generated {

struct QuadCoord
{
    using CppType = ::QuadCoord;
    using ObjcType = MCQuadCoord*;

    using Boxed = QuadCoord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif
