// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni
#ifdef __cplusplus

#include "Quad2dInstancedInterface.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MCQuad2dInstancedInterface;

namespace djinni_generated {

class Quad2dInstancedInterface
{
public:
    using CppType = std::shared_ptr<::Quad2dInstancedInterface>;
    using CppOptType = std::shared_ptr<::Quad2dInstancedInterface>;
    using ObjcType = id<MCQuad2dInstancedInterface>;

    using Boxed = Quad2dInstancedInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif
