// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from network_activity_manager.djinni

#import "MCRemainingTasksInfo.h"


@implementation MCRemainingTasksInfo

- (nonnull instancetype)initWithLayerName:(nonnull NSString *)layerName
                                    count:(int32_t)count
{
    if (self = [super init]) {
        _layerName = [layerName copy];
        _count = count;
    }
    return self;
}

+ (nonnull instancetype)remainingTasksInfoWithLayerName:(nonnull NSString *)layerName
                                                  count:(int32_t)count
{
    return [(MCRemainingTasksInfo*)[self alloc] initWithLayerName:layerName
                                                            count:count];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p layerName:%@ count:%@>", self.class, (void *)self, self.layerName, @(self.count)];
}

@end
