// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from task_scheduler.djinni

#import <Foundation/Foundation.h>


@interface MCSchedulerGraphicsTaskCallbacks : NSObject

- (void)requestGraphicsTaskExecution;

@end
