// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from task_scheduler.djinni

#import "MCSchedulerGraphicsTaskCallbacks+Private.h"
#import "MCSchedulerGraphicsTaskCallbacks.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface MCSchedulerGraphicsTaskCallbacks ()

- (id)initWithCpp:(const std::shared_ptr<::SchedulerGraphicsTaskCallbacks>&)cppRef;

@end

@implementation MCSchedulerGraphicsTaskCallbacks {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SchedulerGraphicsTaskCallbacks>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SchedulerGraphicsTaskCallbacks>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (void)requestGraphicsTaskExecution {
    try {
        _cppRefHandle.get()->requestGraphicsTaskExecution();
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SchedulerGraphicsTaskCallbacks::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SchedulerGraphicsTaskCallbacks::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<MCSchedulerGraphicsTaskCallbacks>(cpp);
}

} // namespace djinni_generated

@end
