// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

#import "MCSharedBytes+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto SharedBytes::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.address),
            ::djinni::I32::toCpp(obj.elementCount),
            ::djinni::I32::toCpp(obj.bytesPerElement)};
}

auto SharedBytes::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCSharedBytes alloc] initWithAddress:(::djinni::I64::fromCpp(cpp.address))
                                     elementCount:(::djinni::I32::fromCpp(cpp.elementCount))
                                  bytesPerElement:(::djinni::I32::fromCpp(cpp.bytesPerElement))];
}

} // namespace djinni_generated
