// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni
#ifdef __cplusplus

#import "MCSharedBytes.h"
#include "SharedBytes.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCSharedBytes;

namespace djinni_generated {

struct SharedBytes
{
    using CppType = ::SharedBytes;
    using ObjcType = MCSharedBytes*;

    using Boxed = SharedBytes;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif
