// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sky_sphere.djinni
#ifdef __cplusplus

#include "SkySphereLayerInterface.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCSkySphereLayerInterface;

namespace djinni_generated {

class SkySphereLayerInterface
{
public:
    using CppType = std::shared_ptr<::SkySphereLayerInterface>;
    using CppOptType = std::shared_ptr<::SkySphereLayerInterface>;
    using ObjcType = MCSkySphereLayerInterface*;

    using Boxed = SkySphereLayerInterface;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated

#endif
