// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from task_scheduler.djinni

#import "MCTaskConfig.h"
#import <Foundation/Foundation.h>


@protocol MCTaskInterface

- (nonnull MCTaskConfig *)getConfig;

- (void)run;

@end
