// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from text.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCTextSymbolPlacement)
{
    MCTextSymbolPlacementPOINT,
    MCTextSymbolPlacementLINE,
    MCTextSymbolPlacementLINE_CENTER,
};
