// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCTessellationMode)
{
    MCTessellationModeNONE = 0,
    MCTessellationModeQUAD = 1,
    MCTessellationModeTRIANGLE = 2,
};
