// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

#import "MCGlyphDescription.h"
#import <Foundation/Foundation.h>

@interface MCTextDescription : NSObject
- (nonnull instancetype)initWithGlyphs:(nonnull NSArray<MCGlyphDescription *> *)glyphs;
+ (nonnull instancetype)textDescriptionWithGlyphs:(nonnull NSArray<MCGlyphDescription *> *)glyphs;

@property (nonatomic, readonly, nonnull) NSArray<MCGlyphDescription *> * glyphs;

@end
