// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MCTextJustify)
{
    MCTextJustifyAUTO = 0,
    MCTextJustifyLEFT = 1,
    MCTextJustifyCENTER = 2,
    MCTextJustifyRIGHT = 3,
};
