// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from task_scheduler.djinni
#ifdef __cplusplus

#include "ThreadPoolScheduler.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCThreadPoolScheduler;

namespace djinni_generated {

class ThreadPoolScheduler
{
public:
    using CppType = std::shared_ptr<::ThreadPoolScheduler>;
    using CppOptType = std::shared_ptr<::ThreadPoolScheduler>;
    using ObjcType = MCThreadPoolScheduler*;

    using Boxed = ThreadPoolScheduler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

#endif
