// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from touch_handler.djinni

#import "MCTouchEvent+Private.h"
#import "DJIMarshal+Private.h"
#import "MCTouchAction+Private.h"
#import "MCVec2F+Private.h"
#include <cassert>

namespace djinni_generated {

auto TouchEvent::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni_generated::Vec2F>::toCpp(obj.pointers),
            ::djinni::Enum<::TouchAction, MCTouchAction>::toCpp(obj.touchAction)};
}

auto TouchEvent::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCTouchEvent alloc] initWithPointers:(::djinni::List<::djinni_generated::Vec2F>::fromCpp(cpp.pointers))
                                      touchAction:(::djinni::Enum<::TouchAction, MCTouchAction>::fromCpp(cpp.touchAction))];
}

}  // namespace djinni_generated
