// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common.djinni

#import "MCVec2F+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Vec2F::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.x),
            ::djinni::F32::toCpp(obj.y)};
}

auto Vec2F::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCVec2F alloc] initWithX:(::djinni::F32::fromCpp(cpp.x))
                                    y:(::djinni::F32::fromCpp(cpp.y))];
}

}  // namespace djinni_generated
