// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from common.djinni

#import "MCVec3F+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Vec3F::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::F32::toCpp(obj.x),
            ::djinni::F32::toCpp(obj.y),
            ::djinni::F32::toCpp(obj.z)};
}

auto Vec3F::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MCVec3F alloc] initWithX:(::djinni::F32::fromCpp(cpp.x))
                                    y:(::djinni::F32::fromCpp(cpp.y))
                                    z:(::djinni::F32::fromCpp(cpp.z))];
}

}  // namespace djinni_generated
