// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni
#ifdef __cplusplus

#import "MCVectorLayerFeatureInfo.h"
#include "VectorLayerFeatureInfo.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCVectorLayerFeatureInfo;

namespace djinni_generated {

struct VectorLayerFeatureInfo
{
    using CppType = ::VectorLayerFeatureInfo;
    using ObjcType = MCVectorLayerFeatureInfo*;

    using Boxed = VectorLayerFeatureInfo;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

} // namespace djinni_generated
#endif
