// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#import <Foundation/Foundation.h>
@class MCWebMapCallbackInterface;
@protocol MCMapCallbackInterface;


/** Web only */
@interface MCWebMapCallbackInterface : NSObject

+ (nullable MCWebMapCallbackInterface *)create;

- (BOOL)getAndResetInvalid;

- (nullable id<MCMapCallbackInterface>)asCallbackInterface;

@end
