// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wmts.djinni
#ifdef __cplusplus

#include "WmtsTiled2dMapLayerConfigFactory.h"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MCWmtsTiled2dMapLayerConfigFactory;

namespace djinni_generated {

class WmtsTiled2dMapLayerConfigFactory
{
public:
    using CppType = std::shared_ptr<::WmtsTiled2dMapLayerConfigFactory>;
    using CppOptType = std::shared_ptr<::WmtsTiled2dMapLayerConfigFactory>;
    using ObjcType = MCWmtsTiled2dMapLayerConfigFactory*;

    using Boxed = WmtsTiled2dMapLayerConfigFactory;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

#endif
