// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_gps.djinni

#include "NativeGpsStyleInfo.h"  // my header
#include "Marshal.hpp"
#include "NativeColor.h"
#include "NativeTextureHolderInterface.h"

namespace djinni_generated {

NativeGpsStyleInfo::NativeGpsStyleInfo() = default;

NativeGpsStyleInfo::~NativeGpsStyleInfo() = default;

auto NativeGpsStyleInfo::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeGpsStyleInfo>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::fromCpp(jniEnv, c.pointTexture)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::fromCpp(jniEnv, c.headingTexture)),
                                                           ::djinni::get(::djinni_generated::NativeColor::fromCpp(jniEnv, c.accuracyColor)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeGpsStyleInfo::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeGpsStyleInfo>::get();
    return {::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_pointTexture)),
            ::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_headingTexture)),
            ::djinni_generated::NativeColor::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_accuracyColor))};
}

}  // namespace djinni_generated
