// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

import type { Color, RectI } from "@djinni/maps-core/graphics/common/common"
import type { TextureHolderInterface } from "@djinni/maps-core/graphics/objects/graphicsobjects"
import type { Coord } from "@djinni/maps-core/map/coordinates/coordinate_system"
import type { Tiled2dMapReadyStateListener, Tiled2dMapZoomInfo } from "@djinni/maps-core/map/layers/tiled/tiled_layer"
import type { DataLoaderResult, FontLoaderInterface, LoaderInterface, TextureLoaderResult } from "@djinni/maps-core/map/loader/loader"
import type { LayerInterface } from "@djinni/maps-core/map/core"

export interface Tiled2dMapVectorLayerInterface {
    setSelectionDelegate(selectionDelegate: Tiled2dMapVectorLayerSelectionCallbackInterface | undefined): void;
    asLayerInterface(): LayerInterface;
    setMinZoomLevelIdentifier(value: number | undefined): void;
    getMinZoomLevelIdentifier(): number | undefined;
    setMaxZoomLevelIdentifier(value: number | undefined): void;
    getMaxZoomLevelIdentifier(): number | undefined;
    getStyleMetadataJson(): string | undefined;
    setFeatureState(identifier: string, properties: Map<string, VectorLayerFeatureInfoValue>): void;
    setGlobalState(properties: Map<string, VectorLayerFeatureInfoValue>): void;
    getVisiblePointFeatureContexts(paddingPc: number, sourceLayer: string | undefined): Array<VectorLayerFeatureCoordInfo>;
    setReadyStateListener(listener: Tiled2dMapReadyStateListener | undefined): void;
    reloadDataSource(sourceName: string): void;
    reloadLocalDataSource(sourceName: string, geoJson: string): void;
    performClick(coord: Coord): void;
}
export interface Tiled2dMapVectorLayerInterface_statics {
    /** Creator method for a vector layer specified by a url to a style json and the compulsory loader interfaces */
    createFromStyleJson(layerName: string, styleJsonUrl: string, loaders: Array<LoaderInterface>, fontLoader: FontLoaderInterface): Tiled2dMapVectorLayerInterface;
    /**
     * Create a vector layer instance by fully providing a combination of properties, specifying the functionality of the layer. Non-optionals
     * are strictly needed in every case.
     * @param    layerName  name for the created layer
     * @param    styleJson  Optional string to specify a url to a style json or a style json string itself (see parameter "localStyleJson")
     * @param    localStyleJson  Optional flag to indicate whether parameter "styleJson" is local style json string or the url to a style json. Default is false.
     * @param    loaders Mandatory list of data loaders, which are used in the provided order
     * @param    fontLoader Mandatory interface to load font data
     * @param    localDataProvider When provided, the vector layer loads the style json, geojsons and the sprite infos via this interface
     * @param    customZoomInfo    Optionally specify a custom zoom info
     * @param    symbolDelegate Optional texture provider, when layers in the style use the flag "icon-image-custom-provider"
     * @return   the interface to the newly configured layer
     */
    createExplicitly(layerName: string, styleJson: string | undefined, localStyleJson: boolean | undefined, loaders: Array<LoaderInterface>, fontLoader: FontLoaderInterface, localDataProvider: Tiled2dMapVectorLayerLocalDataProviderInterface | undefined, customZoomInfo: Tiled2dMapZoomInfo | undefined, symbolDelegate: Tiled2dMapVectorLayerSymbolDelegateInterface | undefined, sourceUrlParams: Map<string, string> | undefined): Tiled2dMapVectorLayerInterface;
}

export interface /*record*/ VectorLayerFeatureInfoValue {
    stringVal?: string;
    doubleVal?: number;
    intVal?: bigint;
    boolVal?: boolean;
    colorVal?: Color;
    listFloatVal?: Array<number>;
    listStringVal?: Array<string>;
}

export interface FeatureInfoValueFactory {
}
export interface FeatureInfoValueFactory_statics {
    createString(value: string): VectorLayerFeatureInfoValue;
    createDouble(value: number): VectorLayerFeatureInfoValue;
    createInt(value: bigint): VectorLayerFeatureInfoValue;
    createBool(value: boolean): VectorLayerFeatureInfoValue;
    createColor(value: Color): VectorLayerFeatureInfoValue;
    createListFloat(value: Array<number>): VectorLayerFeatureInfoValue;
    createListString(value: Array<string>): VectorLayerFeatureInfoValue;
}

export interface /*record*/ VectorLayerFeatureCoordInfo {
    featureInfo: VectorLayerFeatureInfo;
    coordinates: Coord;
}

export interface /*record*/ VectorLayerFeatureInfo {
    identifier: string;
    properties: Map<string, VectorLayerFeatureInfoValue>;
}

export interface Tiled2dMapVectorLayerSelectionCallbackInterface {
    didSelectFeature(featureInfo: VectorLayerFeatureInfo, layerIdentifier: string, coord: Coord): boolean;
    didMultiSelectLayerFeatures(featureInfos: Array<VectorLayerFeatureInfo>, layerIdentifier: string, coord: Coord): boolean;
    didClickBackgroundConfirmed(coord: Coord): boolean;
}

export interface Tiled2dMapVectorLayerLocalDataProviderInterface {
    getStyleJson(): string | undefined;
    loadSpriteAsync(spriteId: string, url: string, scale: number): Promise<TextureLoaderResult>;
    loadSpriteJsonAsync(spriteId: string, url: string, scale: number): Promise<DataLoaderResult>;
    loadGeojson(sourceName: string, url: string): Promise<DataLoaderResult>;
}

export interface /*record*/ Tiled2dMapVectorAssetInfo {
    featureIdentifiersUv: Map<string, RectI>;
    texture?: TextureHolderInterface;
}

export interface Tiled2dMapVectorLayerSymbolDelegateInterface {
    getCustomAssetsFor(featureInfos: Array<VectorLayerFeatureInfo>, layerIdentifier: string): Array<Tiled2dMapVectorAssetInfo>;
}

export interface TiledVectorLayer_statics {
    Tiled2dMapVectorLayerInterface: Tiled2dMapVectorLayerInterface_statics;
    FeatureInfoValueFactory: FeatureInfoValueFactory_statics;
}
