// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

#include "NativeSimpleLineStyle.h"  // my header
#include "Marshal.hpp"
#include "NativeColorStateList.h"
#include "NativeLineCapType.h"
#include "NativeSizeType.h"

namespace djinni_generated {

NativeSimpleLineStyle::NativeSimpleLineStyle() = default;

NativeSimpleLineStyle::~NativeSimpleLineStyle() = default;

auto NativeSimpleLineStyle::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeSimpleLineStyle>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni_generated::NativeColorStateList::fromCpp(jniEnv, c.color)),
                                                           ::djinni::get(::djinni_generated::NativeSizeType::fromCpp(jniEnv, c.widthType)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.width)),
                                                           ::djinni::get(::djinni::List<::djinni::F32>::fromCpp(jniEnv, c.dashArray)),
                                                           ::djinni::get(::djinni_generated::NativeLineCapType::fromCpp(jniEnv, c.lineCap)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.offset)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.dotted)),
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.dottedSkew)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeSimpleLineStyle::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 9);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeSimpleLineStyle>::get();
    return {::djinni_generated::NativeColorStateList::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_color)),
            ::djinni_generated::NativeSizeType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_widthType)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_width)),
            ::djinni::List<::djinni::F32>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_dashArray)),
            ::djinni_generated::NativeLineCapType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_lineCap)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_offset)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_dotted)),
            ::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_dottedSkew))};
}

} // namespace djinni_generated
