// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

package io.openmobilemaps.mapscore.shared.map

data class MapConfig(
    val mapCoordinateSystem: io.openmobilemaps.mapscore.shared.map.coordinates.MapCoordinateSystem,
)