// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from sphere_effect.djinni

import type { LayerInterface } from "@djinni/maps-core/map/core"

export interface SphereEffectLayerInterface {
    asLayerInterface(): LayerInterface;
}
export interface SphereEffectLayerInterface_statics {
    create(): SphereEffectLayerInterface;
}

export interface SphereEffect_statics {
    SphereEffectLayerInterface: SphereEffectLayerInterface_statics;
}
