// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from layer_object.djinni

#pragma once

#include "GraphicsObjectInterface.h"
#include <cstdint>
#include <memory>

class RenderConfigInterface {
public:
    virtual ~RenderConfigInterface() {}

    virtual std::shared_ptr<::GraphicsObjectInterface> getGraphicsObject() = 0;

    virtual int32_t getRenderIndex() = 0;
};
