// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMColorShaderInterface constructor(nativeHandle: Any) {

    fun setColor(red: Float, green: Float, blue: Float, alpha: Float)

    fun asShaderProgramInterface(): KMShaderProgramInterface
}
