// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from loader.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMFontLoaderResult(
    imageData: KMTextureHolderInterface?,
    fontData: KMFontData?,
    status: KMLoaderStatus,
) {
    val imageData: KMTextureHolderInterface?
    val fontData: KMFontData?
    val status: KMLoaderStatus
}
