// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from shader.djinni

package io.openmobilemaps.mapscore.kmp

expect interface KMShaderFactoryInterface {

    fun createAlphaShader(): KMAlphaShaderInterface

    fun createUnitSphereAlphaShader(): KMAlphaShaderInterface

    fun createAlphaInstancedShader(): KMAlphaInstancedShaderInterface

    fun createUnitSphereAlphaInstancedShader(): KMAlphaInstancedShaderInterface

    fun createLineGroupShader(): KMLineGroupShaderInterface

    fun createUnitSphereLineGroupShader(): KMLineGroupShaderInterface

    fun createSimpleLineGroupShader(): KMLineGroupShaderInterface

    fun createUnitSphereSimpleLineGroupShader(): KMLineGroupShaderInterface

    fun createUnitSphereColorShader(): KMColorShaderInterface

    fun createColorShader(): KMColorShaderInterface

    fun createColorCircleShader(): KMColorCircleShaderInterface

    fun createUnitSphereColorCircleShader(): KMColorCircleShaderInterface

    fun createPolygonGroupShader(isStriped: Boolean, unitSphere: Boolean): KMPolygonGroupShaderInterface

    fun createPolygonPatternGroupShader(fadeInPattern: Boolean, unitSphere: Boolean): KMPolygonPatternGroupShaderInterface

    fun createTextShader(): KMTextShaderInterface

    fun createTextInstancedShader(): KMTextInstancedShaderInterface

    fun createUnitSphereTextInstancedShader(): KMTextInstancedShaderInterface

    fun createRasterShader(): KMRasterShaderInterface

    fun createUnitSphereRasterShader(): KMRasterShaderInterface

    fun createStretchShader(): KMStretchShaderInterface

    fun createStretchInstancedShader(unitSphere: Boolean): KMStretchInstancedShaderInterface

    fun createIcosahedronColorShader(): KMColorShaderInterface

    fun createSphereEffectShader(): KMSphereEffectShaderInterface

    fun createSkySphereShader(): KMSkySphereShaderInterface

    fun createElevationInterpolationShader(): KMElevationInterpolationShaderInterface
}
