// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from text.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMTextFactory constructor(nativeHandle: Any) {

    companion object
    {

        fun createText(text: ArrayList<KMFormattedStringEntry>, coordinate: KMCoord, font: KMFont, textAnchor: KMAnchor, textJustify: KMTextJustify): KMTextInfoInterface
    }
}
