// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

package io.openmobilemaps.mapscore.kmp

expect class KMVec2D(
    x: Double,
    y: Double,
) {
    val x: Double
    val y: Double
}
