// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.shared.graphics.objects

data class GlyphDescription(
    val frame: io.openmobilemaps.mapscore.shared.graphics.common.Quad2dD,
    val textureCoordinates: io.openmobilemaps.mapscore.shared.graphics.common.Quad2dD,
)