// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.shared.graphics.objects

import java.util.concurrent.atomic.AtomicBoolean

abstract class GraphicsObjectFactoryInterface {

    abstract fun createQuad(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Quad2dInterface

    abstract fun createLine(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Line2dInterface

    abstract fun createPolygon(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Polygon2dInterface

    abstract fun createQuadMask(): Quad2dInterface

    abstract fun createPolygonMask(): Polygon2dInterface

    private class CppProxy : GraphicsObjectFactoryInterface {
        private val nativeRef: Long
        private val destroyed: AtomicBoolean = AtomicBoolean(false)

        private constructor(nativeRef: Long) {
            if (nativeRef == 0L) error("nativeRef is zero")
            this.nativeRef = nativeRef
        }

        private external fun nativeDestroy(nativeRef: Long)
        fun _djinni_private_destroy() {
            val destroyed = this.destroyed.getAndSet(true)
            if (!destroyed) nativeDestroy(this.nativeRef)
        }
        protected fun finalize() {
            _djinni_private_destroy()
        }

        override fun createQuad(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Quad2dInterface {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            return native_createQuad(this.nativeRef, shader)
        }
        private external fun native_createQuad(_nativeRef: Long, shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Quad2dInterface

        override fun createLine(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Line2dInterface {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            return native_createLine(this.nativeRef, shader)
        }
        private external fun native_createLine(_nativeRef: Long, shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Line2dInterface

        override fun createPolygon(shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Polygon2dInterface {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            return native_createPolygon(this.nativeRef, shader)
        }
        private external fun native_createPolygon(_nativeRef: Long, shader: io.openmobilemaps.mapscore.shared.graphics.shader.ShaderProgramInterface): Polygon2dInterface

        override fun createQuadMask(): Quad2dInterface {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            return native_createQuadMask(this.nativeRef)
        }
        private external fun native_createQuadMask(_nativeRef: Long): Quad2dInterface

        override fun createPolygonMask(): Polygon2dInterface {
            assert(!this.destroyed.get()) { error("trying to use a destroyed object") }
            return native_createPolygonMask(this.nativeRef)
        }
        private external fun native_createPolygonMask(_nativeRef: Long): Polygon2dInterface
    }
}
