// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.shared.graphics.objects;

import com.snapchat.djinni.NativeObjectManager;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class Quad2dInterface {
    public abstract void setFrame(io.openmobilemaps.mapscore.shared.graphics.common.Quad2dD frame, io.openmobilemaps.mapscore.shared.graphics.common.RectD textureCoordinates);

    public abstract void loadTexture(io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface context, TextureHolderInterface textureHolder);

    public abstract void removeTexture();

    public abstract GraphicsObjectInterface asGraphicsObject();

    public abstract MaskingObjectInterface asMaskingObject();

    public static final class CppProxy extends Quad2dInterface
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
            NativeObjectManager.register(this, nativeRef);
        }
        public static native void nativeDestroy(long nativeRef);

        @Override
        public void setFrame(io.openmobilemaps.mapscore.shared.graphics.common.Quad2dD frame, io.openmobilemaps.mapscore.shared.graphics.common.RectD textureCoordinates)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setFrame(this.nativeRef, frame, textureCoordinates);
        }
        private native void native_setFrame(long _nativeRef, io.openmobilemaps.mapscore.shared.graphics.common.Quad2dD frame, io.openmobilemaps.mapscore.shared.graphics.common.RectD textureCoordinates);

        @Override
        public void loadTexture(io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface context, TextureHolderInterface textureHolder)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_loadTexture(this.nativeRef, context, textureHolder);
        }
        private native void native_loadTexture(long _nativeRef, io.openmobilemaps.mapscore.shared.graphics.RenderingContextInterface context, TextureHolderInterface textureHolder);

        @Override
        public void removeTexture()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_removeTexture(this.nativeRef);
        }
        private native void native_removeTexture(long _nativeRef);

        @Override
        public GraphicsObjectInterface asGraphicsObject()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_asGraphicsObject(this.nativeRef);
        }
        private native GraphicsObjectInterface native_asGraphicsObject(long _nativeRef);

        @Override
        public MaskingObjectInterface asMaskingObject()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_asMaskingObject(this.nativeRef);
        }
        private native MaskingObjectInterface native_asMaskingObject(long _nativeRef);
    }
}
