// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

package io.openmobilemaps.mapscore.shared.graphics.objects;

import java.util.ArrayList;

public final class RenderVerticesDescription {


    /*package*/ final ArrayList<io.openmobilemaps.mapscore.shared.graphics.common.Vec2D> vertices;

    /*package*/ final int styleIndex;

    public RenderVerticesDescription(
            ArrayList<io.openmobilemaps.mapscore.shared.graphics.common.Vec2D> vertices,
            int styleIndex) {
        this.vertices = vertices;
        this.styleIndex = styleIndex;
    }

    public ArrayList<io.openmobilemaps.mapscore.shared.graphics.common.Vec2D> getVertices() {
        return vertices;
    }

    public int getStyleIndex() {
        return styleIndex;
    }

    @Override
    public String toString() {
        return "RenderVerticesDescription{" +
                "vertices=" + vertices +
                "," + "styleIndex=" + styleIndex +
        "}";
    }

}
