// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from packer.djinni

#pragma once

#include "TextureAtlas.h"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeTextureAtlas final {
public:
    using CppType = ::TextureAtlas;
    using JniType = jobject;

    using Boxed = NativeTextureAtlas;

    ~NativeTextureAtlas();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTextureAtlas();
    friend ::djinni::JniClass<NativeTextureAtlas>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/openmobilemaps/mapscore/shared/graphics/TextureAtlas") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/HashMap;Lio/openmobilemaps/mapscore/shared/graphics/objects/TextureHolderInterface;)V") };
    const jfieldID field_uvMap { ::djinni::jniGetFieldID(clazz.get(), "uvMap", "Ljava/util/HashMap;") };
    const jfieldID field_texture { ::djinni::jniGetFieldID(clazz.get(), "texture", "Lio/openmobilemaps/mapscore/shared/graphics/objects/TextureHolderInterface;") };
};

} // namespace djinni_generated
