// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from touch_handler.djinni

#include "NativeDefaultTouchHandlerInterface.h"  // my header
#include "NativeSchedulerInterface.h"
#include "NativeTouchHandlerInterface.h"

namespace djinni_generated {

em::val NativeDefaultTouchHandlerInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
    });
    return methods;
}

em::val NativeDefaultTouchHandlerInterface::create(const em::val& w_scheduler,float w_density) {
    try {
        auto r = ::DefaultTouchHandlerInterface::create(::djinni_generated::NativeSchedulerInterface::toCpp(w_scheduler),
               ::djinni::F32::toCpp(w_density));
        return ::djinni_generated::NativeTouchHandlerInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeTouchHandlerInterface>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_default_touch_handler_interface) {
    em::class_<::DefaultTouchHandlerInterface>("DefaultTouchHandlerInterface")
        .smart_ptr<std::shared_ptr<::DefaultTouchHandlerInterface>>("DefaultTouchHandlerInterface")
        .function("nativeDestroy", &NativeDefaultTouchHandlerInterface::nativeDestroy)
        .class_function("create", NativeDefaultTouchHandlerInterface::create)
        ;
}

} // namespace djinni_generated
