// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from coordinate_system.djinni

#pragma once

#include "Coord.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeCoord
{
    using CppType = ::Coord;
    using JsType = em::val;
    using Boxed = NativeCoord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
