// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

#pragma once

#include "LineStyle.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeLineStyle
{
    using CppType = ::LineStyle;
    using JsType = em::val;
    using Boxed = NativeLineStyle;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
