// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from loader.djinni

#include "NativeGlobalLoaderInterface.h"  // my header
#include "Future_wasm.hpp"
#include "NativeDataLoaderResult.h"
#include "NativeFontLoaderInterface.h"
#include "NativeLoaderInterface.h"
#include "NativeTextureLoaderResult.h"

namespace djinni_generated {

em::val NativeGlobalLoaderInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "createLoader",
        "createFontLoader",
        "processLoadRequests",
        "enqueueDataLoadRequest",
        "enqueueTextureLoadRequest",
        "cancel",
    });
    return methods;
}

em::val NativeGlobalLoaderInterface::create() {
    try {
        auto r = ::GlobalLoaderInterface::create();
        return ::djinni_generated::NativeGlobalLoaderInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeGlobalLoaderInterface>::handleNativeException(e);
    }
}
em::val NativeGlobalLoaderInterface::createLoader(const CppType& self) {
    try {
        auto r = self->createLoader();
        return ::djinni_generated::NativeLoaderInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeLoaderInterface>::handleNativeException(e);
    }
}
em::val NativeGlobalLoaderInterface::createFontLoader(const CppType& self, const em::val& w_loader,const std::string& w_baseUrl) {
    try {
        auto r = self->createFontLoader(::djinni_generated::NativeLoaderInterface::toCpp(w_loader),
                         ::djinni::String::toCpp(w_baseUrl));
        return ::djinni_generated::NativeFontLoaderInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeFontLoaderInterface>::handleNativeException(e);
    }
}
void NativeGlobalLoaderInterface::processLoadRequests(const CppType& self) {
    try {
        self->processLoadRequests();
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
em::val NativeGlobalLoaderInterface::enqueueDataLoadRequest(const CppType& self, const std::string& w_url,const em::val& w_etag) {
    try {
        auto r = self->enqueueDataLoadRequest(::djinni::String::toCpp(w_url),
                               ::djinni::Optional<std::optional, ::djinni::String>::toCpp(w_etag));
        return ::djinni::FutureAdaptor<::djinni_generated::NativeDataLoaderResult>::fromCpp(std::move(r));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::FutureAdaptor<::djinni_generated::NativeDataLoaderResult>>::handleNativeException(e);
    }
}
em::val NativeGlobalLoaderInterface::enqueueTextureLoadRequest(const CppType& self, const std::string& w_url,const em::val& w_etag) {
    try {
        auto r = self->enqueueTextureLoadRequest(::djinni::String::toCpp(w_url),
                                  ::djinni::Optional<std::optional, ::djinni::String>::toCpp(w_etag));
        return ::djinni::FutureAdaptor<::djinni_generated::NativeTextureLoaderResult>::fromCpp(std::move(r));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::FutureAdaptor<::djinni_generated::NativeTextureLoaderResult>>::handleNativeException(e);
    }
}
void NativeGlobalLoaderInterface::cancel(const CppType& self, const std::string& w_url) {
    try {
        self->cancel(::djinni::String::toCpp(w_url));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_global_loader_interface) {
    em::class_<::GlobalLoaderInterface>("GlobalLoaderInterface")
        .smart_ptr<std::shared_ptr<::GlobalLoaderInterface>>("GlobalLoaderInterface")
        .function("nativeDestroy", &NativeGlobalLoaderInterface::nativeDestroy)
        .class_function("create", NativeGlobalLoaderInterface::create)
        .function("createLoader", NativeGlobalLoaderInterface::createLoader)
        .function("createFontLoader", NativeGlobalLoaderInterface::createFontLoader)
        .function("processLoadRequests", NativeGlobalLoaderInterface::processLoadRequests)
        .function("enqueueDataLoadRequest", NativeGlobalLoaderInterface::enqueueDataLoadRequest)
        .function("enqueueTextureLoadRequest", NativeGlobalLoaderInterface::enqueueTextureLoadRequest)
        .function("cancel", NativeGlobalLoaderInterface::cancel)
        ;
}

} // namespace djinni_generated
