// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from geo_json_parser.djinni

#pragma once

#include "GeoJsonLine.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeGeoJsonLine
{
    using CppType = ::GeoJsonLine;
    using JsType = em::val;
    using Boxed = NativeGeoJsonLine;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
