// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from common.djinni

#pragma once

#include "Vec3F.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeVec3F
{
    using CppType = ::Vec3F;
    using JsType = em::val;
    using Boxed = NativeVec3F;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
