// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from loader.djinni

#pragma once

#include "LoaderStatus.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeLoaderStatus: ::djinni::WasmEnum<::LoaderStatus> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
