// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#include "NativeRenderingCullMode.h"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__rendering_cull_mode_consts, (), {
        Module.RenderingCullMode =  {
            FRONT : 0,
            BACK : 1,
            NONE : 2,
        }
    })
}

void NativeRenderingCullMode::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__rendering_cull_mode_consts();
    });
}

EMSCRIPTEN_BINDINGS(_rendering_cull_mode) {
    NativeRenderingCullMode::staticInitializeConstants();
}

} // namespace djinni_generated
