// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

#pragma once

#include "TextDescription.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeTextDescription
{
    using CppType = ::TextDescription;
    using JsType = em::val;
    using Boxed = NativeTextDescription;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

} // namespace djinni_generated
