// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from polygon.djinni

#include "NativePolygonLayerCallbackInterface.h"  // my header
#include "NativePolygonInfo.h"

namespace djinni_generated {

em::val NativePolygonLayerCallbackInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "onClickConfirmed",
        "onClickUnconfirmed",
    });
    return methods;
}

bool NativePolygonLayerCallbackInterface::onClickConfirmed(const CppType& self, const em::val& w_polygon) {
    try {
        auto r = self->onClickConfirmed(::djinni_generated::NativePolygonInfo::toCpp(w_polygon));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}
bool NativePolygonLayerCallbackInterface::onClickUnconfirmed(const CppType& self, const em::val& w_polygon) {
    try {
        auto r = self->onClickUnconfirmed(::djinni_generated::NativePolygonInfo::toCpp(w_polygon));
        return ::djinni::Bool::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::Bool>::handleNativeException(e);
    }
}

bool NativePolygonLayerCallbackInterface::JsProxy::onClickConfirmed(const ::PolygonInfo & polygon) {
    auto ret = callMethod("onClickConfirmed", ::djinni_generated::NativePolygonInfo::fromCpp(polygon));
    checkError(ret);
    return ::djinni::Bool::toCpp(ret.as<bool>());
}

bool NativePolygonLayerCallbackInterface::JsProxy::onClickUnconfirmed(const ::PolygonInfo & polygon) {
    auto ret = callMethod("onClickUnconfirmed", ::djinni_generated::NativePolygonInfo::fromCpp(polygon));
    checkError(ret);
    return ::djinni::Bool::toCpp(ret.as<bool>());
}

EMSCRIPTEN_BINDINGS(_polygon_layer_callback_interface) {
    em::class_<::PolygonLayerCallbackInterface>("PolygonLayerCallbackInterface")
        .smart_ptr<std::shared_ptr<::PolygonLayerCallbackInterface>>("PolygonLayerCallbackInterface")
        .function("nativeDestroy", &NativePolygonLayerCallbackInterface::nativeDestroy)
        .function("onClickConfirmed", NativePolygonLayerCallbackInterface::onClickConfirmed)
        .function("onClickUnconfirmed", NativePolygonLayerCallbackInterface::onClickUnconfirmed)
        ;
}

} // namespace djinni_generated
