// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from geo_json_parser.djinni

#include "NativeGeoJsonPoint.h"  // my header
#include "NativeCoord.h"
#include "NativeVectorLayerFeatureInfo.h"

namespace djinni_generated {

auto NativeGeoJsonPoint::toCpp(const JsType& j) -> CppType {
    return {::djinni_generated::NativeCoord::Boxed::toCpp(j["point"]),
            ::djinni_generated::NativeVectorLayerFeatureInfo::Boxed::toCpp(j["featureInfo"])};
}
auto NativeGeoJsonPoint::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("point", ::djinni_generated::NativeCoord::Boxed::fromCpp(c.point));
    js.set("featureInfo", ::djinni_generated::NativeVectorLayerFeatureInfo::Boxed::fromCpp(c.featureInfo));
    return js;
}

} // namespace djinni_generated
