// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from graphicsobjects.djinni

#include "NativeTextInterface.h"  // my header
#include "NativeGraphicsObjectInterface.h"
#include "NativeRenderingContextInterface.h"
#include "NativeSharedBytes.h"
#include "NativeTextureHolderInterface.h"

namespace djinni_generated {

em::val NativeTextInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "setTextsShared",
        "loadTexture",
        "removeTexture",
        "asGraphicsObject",
    });
    return methods;
}

void NativeTextInterface::setTextsShared(const CppType& self, const em::val& w_vertices,const em::val& w_indices) {
    try {
        self->setTextsShared(::djinni_generated::NativeSharedBytes::toCpp(w_vertices),
                       ::djinni_generated::NativeSharedBytes::toCpp(w_indices));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
void NativeTextInterface::loadTexture(const CppType& self, const em::val& w_context,const em::val& w_textureHolder) {
    try {
        self->loadTexture(::djinni_generated::NativeRenderingContextInterface::toCpp(w_context),
                    ::djinni_generated::NativeTextureHolderInterface::toCpp(w_textureHolder));
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
void NativeTextInterface::removeTexture(const CppType& self) {
    try {
        self->removeTexture();
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<void>::handleNativeException(e);
    }
}
em::val NativeTextInterface::asGraphicsObject(const CppType& self) {
    try {
        auto r = self->asGraphicsObject();
        return ::djinni_generated::NativeGraphicsObjectInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeGraphicsObjectInterface>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_text_interface) {
    em::class_<::TextInterface>("TextInterface")
        .smart_ptr<std::shared_ptr<::TextInterface>>("TextInterface")
        .function("nativeDestroy", &NativeTextInterface::nativeDestroy)
        .function("setTextsShared", NativeTextInterface::setTextsShared)
        .function("loadTexture", NativeTextInterface::loadTexture)
        .function("removeTexture", NativeTextInterface::removeTexture)
        .function("asGraphicsObject", NativeTextInterface::asGraphicsObject)
        ;
}

} // namespace djinni_generated
