// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tiled_vector_layer.djinni

#pragma once

#include "Tiled2dMapVectorLayerLocalDataProviderInterface.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeTiled2dMapVectorLayerLocalDataProviderInterface : ::djinni::JsInterface<::Tiled2dMapVectorLayerLocalDataProviderInterface, NativeTiled2dMapVectorLayerLocalDataProviderInterface> {
    using CppType = std::shared_ptr<::Tiled2dMapVectorLayerLocalDataProviderInterface>;
    using CppOptType = std::shared_ptr<::Tiled2dMapVectorLayerLocalDataProviderInterface>;
    using JsType = em::val;
    using Boxed = NativeTiled2dMapVectorLayerLocalDataProviderInterface;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "NativeTiled2dMapVectorLayerLocalDataProviderInterface::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val getStyleJson(const CppType& self);
    static em::val loadSpriteAsync(const CppType& self, int32_t w_scale);
    static em::val loadSpriteJsonAsync(const CppType& self, int32_t w_scale);
    static em::val loadGeojson(const CppType& self, const std::string& w_sourceName,const std::string& w_url);

};

} // namespace djinni_generated
