// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from line.djinni

#pragma once

#include "LineJoinType.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeLineJoinType: ::djinni::WasmEnum<::LineJoinType> {
    static void staticInitializeConstants();
};

} // namespace djinni_generated
