// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from packer.djinni

#include "NativeTextureAtlas.h"  // my header
#include "NativeRectI.h"
#include "NativeTextureHolderInterface.h"

namespace djinni_generated {

auto NativeTextureAtlas::toCpp(const JsType& j) -> CppType {
    return {::djinni::Map<::djinni::String, ::djinni_generated::NativeRectI>::Boxed::toCpp(j["uvMap"]),
            ::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::Boxed::toCpp(j["texture"])};
}
auto NativeTextureAtlas::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("uvMap", ::djinni::Map<::djinni::String, ::djinni_generated::NativeRectI>::Boxed::fromCpp(c.uvMap));
    js.set("texture", ::djinni::Optional<std::optional, ::djinni_generated::NativeTextureHolderInterface>::Boxed::fromCpp(c.texture));
    return js;
}

} // namespace djinni_generated
