// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from wmts_capabilities.djinni

#include "NativeWmtsTileMatrix.h"  // my header

namespace djinni_generated {

auto NativeWmtsTileMatrix::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["identifier"]),
            ::djinni::F64::Boxed::toCpp(j["scaleDenominator"]),
            ::djinni::F64::Boxed::toCpp(j["topLeftCornerX"]),
            ::djinni::F64::Boxed::toCpp(j["topLeftCornerY"]),
            ::djinni::I32::Boxed::toCpp(j["tileWidth"]),
            ::djinni::I32::Boxed::toCpp(j["tileHeight"]),
            ::djinni::I32::Boxed::toCpp(j["matrixWidth"]),
            ::djinni::I32::Boxed::toCpp(j["matrixHeight"])};
}
auto NativeWmtsTileMatrix::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("identifier", ::djinni::String::Boxed::fromCpp(c.identifier));
    js.set("scaleDenominator", ::djinni::F64::Boxed::fromCpp(c.scaleDenominator));
    js.set("topLeftCornerX", ::djinni::F64::Boxed::fromCpp(c.topLeftCornerX));
    js.set("topLeftCornerY", ::djinni::F64::Boxed::fromCpp(c.topLeftCornerY));
    js.set("tileWidth", ::djinni::I32::Boxed::fromCpp(c.tileWidth));
    js.set("tileHeight", ::djinni::I32::Boxed::fromCpp(c.tileHeight));
    js.set("matrixWidth", ::djinni::I32::Boxed::fromCpp(c.matrixWidth));
    js.set("matrixHeight", ::djinni::I32::Boxed::fromCpp(c.matrixHeight));
    return js;
}

} // namespace djinni_generated
