// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from core.djinni

#include "NativeIndexedLayerInterface.h"  // my header
#include "NativeLayerInterface.h"

namespace djinni_generated {

em::val NativeIndexedLayerInterface::cppProxyMethods() {
    static const em::val methods = em::val::array(std::vector<std::string> {
        "getLayerInterface",
        "getIndex",
    });
    return methods;
}

em::val NativeIndexedLayerInterface::getLayerInterface(const CppType& self) {
    try {
        auto r = self->getLayerInterface();
        return ::djinni_generated::NativeLayerInterface::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni_generated::NativeLayerInterface>::handleNativeException(e);
    }
}
int32_t NativeIndexedLayerInterface::getIndex(const CppType& self) {
    try {
        auto r = self->getIndex();
        return ::djinni::I32::fromCpp(r);
    }
    catch(const std::exception& e) {
        return ::djinni::ExceptionHandlingTraits<::djinni::I32>::handleNativeException(e);
    }
}

EMSCRIPTEN_BINDINGS(_indexed_layer_interface) {
    em::class_<::IndexedLayerInterface>("IndexedLayerInterface")
        .smart_ptr<std::shared_ptr<::IndexedLayerInterface>>("IndexedLayerInterface")
        .function("nativeDestroy", &NativeIndexedLayerInterface::nativeDestroy)
        .function("getLayerInterface", NativeIndexedLayerInterface::getLayerInterface)
        .function("getIndex", NativeIndexedLayerInterface::getIndex)
        ;
}

} // namespace djinni_generated
