// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from map_helpers.djinni

#pragma once

#include "OpenGlPerformanceLoggerInterface.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct NativeOpenGlPerformanceLoggerInterface : ::djinni::JsInterface<::OpenGlPerformanceLoggerInterface, NativeOpenGlPerformanceLoggerInterface> {
    using CppType = std::shared_ptr<::OpenGlPerformanceLoggerInterface>;
    using CppOptType = std::shared_ptr<::OpenGlPerformanceLoggerInterface>;
    using JsType = em::val;
    using Boxed = NativeOpenGlPerformanceLoggerInterface;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "NativeOpenGlPerformanceLoggerInterface::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create();
    static em::val createSpecifically(int32_t w_numBuckets,int64_t w_bucketSizeMs);
    static em::val asPerformanceLoggerInterface(const CppType& self);

};

} // namespace djinni_generated
