// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from global_loader.djinni

#pragma once

#include "GlobalLoaderInterface.h"
#include "djinni_wasm.hpp"

namespace djinni_generated {

struct GlobalLoaderInterface : ::djinni::JsInterface<::GlobalLoaderInterface, GlobalLoaderInterface> {
    using CppType = std::shared_ptr<::GlobalLoaderInterface>;
    using CppOptType = std::shared_ptr<::GlobalLoaderInterface>;
    using JsType = em::val;
    using Boxed = GlobalLoaderInterface;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "GlobalLoaderInterface::fromCpp");
        return fromCppOpt(c);
    }

    static em::val cppProxyMethods();

    static em::val create();
    static em::val createLoader(const CppType& self);
    static em::val createFontLoader(const CppType& self, const em::val& w_loader,const std::string& w_baseUrl);
    static void processLoadRequests(const CppType& self);
    static em::val enqueueDataLoadRequest(const CppType& self, const std::string& w_url,const em::val& w_etag);
    static em::val enqueueTextureLoadRequest(const CppType& self, const std::string& w_url,const em::val& w_etag);
    static void cancel(const CppType& self, const std::string& w_url);

};

} // namespace djinni_generated
