name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12.4
      run: sudo xcode-select --switch /Applications/Xcode_12.4.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
